'use strict';
const $=id=>document.getElementById(id), draftKey='ggp-sinjin-feedback-v1';
let manifest, current=0;
const draft={topic:'general',text:''};
try{Object.assign(draft,JSON.parse(localStorage.getItem(draftKey)||'{}'));}catch{}
$('thought').value=draft.text||'';
function saveDraft(){draft.topic=$('topic').value;draft.text=$('thought').value;try{localStorage.setItem(draftKey,JSON.stringify(draft));}catch{}updateFeedbackLinks();}
function feedbackMessage(){const topic=$('topic').value;const slide=manifest?.slides.find(s=>s.id===topic);const subject='Sinjin + GGP: '+(slide?slide.title:'a thought on the graduate scholars plan');const anchor=slide?'#'+slide.id:'#feedback';return{subject,body:($('thought').value.trim()||'My thought:')+'\n\nAbout: '+(slide?slide.title:'The whole plan')+'\nPresentation: '+location.href.split('#')[0]+anchor+'\nEdition: '+(manifest?.updatedLabel||'latest')+'\n\nSinjin'};}
function updateFeedbackLinks(){const m=feedbackMessage(),to=manifest?.feedbackEmail||'gbellamyAI@gmail.com';$('gmail').href='https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(to)+'&su='+encodeURIComponent(m.subject)+'&body='+encodeURIComponent(m.body);}
function showSlide(index,hash=true){current=Math.max(0,Math.min(index,manifest.slides.length-1));const s=manifest.slides[current];$('slide').src=s.image;$('slide').alt=s.title+' (slide '+(current+1)+' of '+manifest.slides.length+')';$('outline').value=String(current);$('prev').disabled=current===0;$('next').disabled=current===manifest.slides.length-1;$('slide-text').replaceChildren(...s.text.map(t=>{const p=document.createElement('p');p.textContent=t;return p;}));if(hash)history.replaceState(null,'','#'+s.id);if(current+1<manifest.slides.length){const preload=new Image();preload.src=manifest.slides[current+1].image;}}
function applyManifest(data,changed){const previousId=manifest?.slides[current]?.id;const selectedTopic=$('topic').value||draft.topic;manifest=data;for(const [id,key] of [['cohort-count','cohort'],['additional-count','additional'],['mentor-count','mentors']])$(id).textContent=data.headlineFacts?.[key]||'See deck';$('scenario').textContent=data.summary;$('updated').textContent='Updated '+data.updatedLabel;for(const id of ['download','pdf-link']){$(id).href=data.pdf;$(id).download='GGP-Sinjin-Graduate-Impact.pdf';}$('outline').replaceChildren(...data.slides.map((s,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=(i+1)+' / '+data.slides.length+' · '+s.title;return o;}));$('topic').replaceChildren(Object.assign(document.createElement('option'),{value:'general',textContent:'The whole plan'}),...data.slides.map((s,i)=>Object.assign(document.createElement('option'),{value:s.id,textContent:(i+1)+'. '+s.title})));$('topic').value=data.slides.some(s=>s.id===selectedTopic)?selectedTopic:('general');if(!changed&&draft.topic&&data.slides.some(s=>s.id===draft.topic))$('topic').value=draft.topic;const hashId=location.hash.slice(1);let index=data.slides.findIndex(s=>s.id===(changed?previousId:hashId));showSlide(index<0?0:index,false);updateFeedbackLinks();if(changed)$('update-note').textContent='A new edition is here. Your feedback draft is still saved.';}
async function refresh(){try{const r=await fetch('presentation.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!Array.isArray(data.slides)||!data.slides.length)throw Error('No slides');if(!manifest||data.version!==manifest.version)applyManifest(data,Boolean(manifest));}catch(err){if(!manifest){$('scenario').textContent='The presentation could not load. Please refresh this page.';$('updated').textContent='Please refresh';}}}
$('prev').addEventListener('click',()=>showSlide(current-1));$('next').addEventListener('click',()=>showSlide(current+1));$('outline').addEventListener('change',e=>showSlide(Number(e.target.value)));window.addEventListener('hashchange',()=>{if(!manifest)return;const i=manifest.slides.findIndex(s=>'#'+s.id===location.hash);if(i>=0)showSlide(i,false);});document.addEventListener('keydown',e=>{if(!manifest||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.metaKey||e.ctrlKey||e.altKey)return;if(e.key==='ArrowRight'){e.preventDefault();showSlide(current+1);}if(e.key==='ArrowLeft'){e.preventDefault();showSlide(current-1);}});
$('expand').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('viewer').requestFullscreen();}catch{$('update-note').textContent='Use your browser’s full-screen view to enlarge the presentation.';}});
$('comment-slide').addEventListener('click',()=>{if(!manifest)return;$('topic').value=manifest.slides[current].id;saveDraft();$('feedback').scrollIntoView({behavior:'smooth'});$('thought').focus({preventScroll:true});});$('thought').addEventListener('input',saveDraft);$('topic').addEventListener('change',saveDraft);
$('feedback-form').addEventListener('submit',e=>{e.preventDefault();if(!$('thought').value.trim()){ $('thought').focus();return;}saveDraft();const m=feedbackMessage();location.href='mailto:'+manifest.feedbackEmail+'?subject='+encodeURIComponent(m.subject)+'&body='+encodeURIComponent(m.body);$('form-status').textContent='Your email app will open. Review your note and press Send there. If it does not open, choose Use Gmail or Copy note.';});$('gmail').addEventListener('click',e=>{if(!$('thought').value.trim()){e.preventDefault();$('thought').focus();$('form-status').textContent='Add your thought first.';return;}saveDraft();$('form-status').textContent='Review your note in Gmail and press Send there.';});$('copy').addEventListener('click',async()=>{const m=feedbackMessage();try{await navigator.clipboard.writeText('To: '+manifest.feedbackEmail+'\nSubject: '+m.subject+'\n\n'+m.body);$('form-status').textContent='Copied. Paste into an email to Darby when you are ready.';}catch{$('form-status').textContent='Select your note above and copy it, then email Darby.';}});
refresh();setInterval(()=>{if(!document.hidden)refresh();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
