'use strict';const dirs={'field-guide':'Field Guide','high-ground':'High Ground','basecamp':'Basecamp',mix:'A mix of the directions'};const $=s=>document.querySelector(s);let preview='field-guide';
function select(d,restoreMix=false){if(!dirs[d]||d==='mix')return;preview=d;document.querySelectorAll('.choice').forEach(b=>{const yes=b.dataset.direction===d;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);b.querySelector('.choice-check').textContent=yes?'✓':'↗'});$('#preview-name').textContent=dirs[d];$('#site-preview').src='../?direction='+d;$('#site-preview').title='Interactive '+dirs[d]+' design preview';$('#open-full').href='../?direction='+d;$('#choose').innerHTML='Choose '+dirs[d]+' <span>↓</span>';$('#chosen').value=restoreMix?'mix':d;history.replaceState(null,'','?direction='+d+location.hash);persist()}
function persist(){try{localStorage.setItem('gryphus-design-review',JSON.stringify({direction:$('#chosen').value,note:$('#note').value,merch:$('#merch-choice').value,preview}))}catch{$('#feedback-status').textContent='This browser could not save your choices. Download or copy your feedback to keep it.'}updateEmail()}
function message(){return 'Gryphus 2027 design feedback\n\nMy choice: '+dirs[$('#chosen').value]+'\nMerchandise: '+$('#merch-choice').selectedOptions[0].text+'\n\n'+($('#note').value.trim()||'I like this direction. Let’s keep developing it.')+'\n\nPreview: '+((location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname))?'https://gordonusc.github.io/the-cabinet/gryphus/':location.origin+location.pathname.replace(/design\/(index.html)?$/,''))+'?direction='+preview}
function updateEmail(){$('#email-feedback').href='mailto:gbellamy@gmail.com?subject='+encodeURIComponent('Gryphus design feedback')+'&body='+encodeURIComponent(message())}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>select(b.dataset.direction));$('#chosen').onchange=()=>{if($('#chosen').value!=='mix')select($('#chosen').value);persist()};$('#note').oninput=persist;$('#merch-choice').onchange=persist;
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([message()],{type:'text/plain;charset=utf-8'}));a.download='Gryphus-design-feedback.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#feedback-status').textContent='Your feedback copy has been downloaded.'}
$('#download-review').onclick=download;$('#feedback-form').onsubmit=async e=>{e.preventDefault();try{await navigator.clipboard.writeText(message());$('#feedback-status').textContent='Copied. Paste your reply to Gordon, or use Email to Gordon.'}catch{download()}};
let remembered;try{remembered=JSON.parse(localStorage.getItem('gryphus-design-review')||'null')}catch{}if(remembered){$('#note').value=remembered.note||'';$('#merch-choice').value=remembered.merch||'undecided'}const requestedMerch=new URLSearchParams(location.search).get('merch');if(['field-kit','high-ground','camp-club','mix'].includes(requestedMerch))$('#merch-choice').value=requestedMerch;const initial=new URLSearchParams(location.search).get('direction')||remembered?.preview||'field-guide';select(dirs[initial]?initial:'field-guide',remembered?.direction==='mix');updateEmail();

for(const a of document.querySelectorAll('.resource')){fetch(a.href,{method:'HEAD'}).then(r=>{if(!r.ok)a.hidden=true}).catch(()=>{});}

function syncMerch(){document.querySelectorAll('[data-merch]').forEach(b=>{const yes=b.dataset.merch===$('#merch-choice').value;b.setAttribute('aria-pressed',yes);b.classList.toggle('selected',yes);b.querySelector('strong').textContent=yes?'Selected ✓':'Choose this collection ↗'})}document.querySelectorAll('[data-merch]').forEach(b=>b.onclick=()=>{$('#merch-choice').value=b.dataset.merch;persist();syncMerch();$('#feedback-status').textContent='Merchandise choice saved. Add any thoughts, then copy or email your feedback.'});$('#merch-choice').addEventListener('change',syncMerch);syncMerch();
