(()=>{'use strict';
const $=s=>document.querySelector(s), D=window.AFTERHOURS_DATA, DEPTH=window.ARTIST_DEPTH||{}, dialog=$('#experienceDialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const isPast=e=>!!e.date&&(e.endDate||e.date)<today;let selected=D.events.find(e=>!isPast(e)&&e.date)||D.events[0],person=D.people[0],currentMedia=null,dialogMode='',lastFocus=null,toastTimer,motion=matchMedia('(prefers-reduced-motion: reduce)').matches,seen=[],jamState;
try{seen=JSON.parse(localStorage.getItem('afterhours-lights')||'[]').filter(x=>D.events.some(e=>e.id===x));const s=localStorage.getItem('afterhours-pattern');if(s)jamState=JSON.parse(s);motion=motion||localStorage.getItem('afterhours-motion')==='paused';}catch{}
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
const themes={portola:['#5140c9','#deff81','piers'],zeds:['#071b29','#b9e8ec','bass'],niteharts:['#ab392c','#f8e5ad','hearts'],latenite:['#261747','#f5aade','moon'],pokemon:['#efc850','#152761','pixels'],pride:['#924c66','#ffefab','rays'],summit:['#ccd4bc','#162e27','stairs'],stevie:['#6a281c','#ffd686','records'],countdown:['#18293b','#e8d69a','orbit'],gryphus:['#733d27','#f0e7c1','sun'],edc:['#544983','#ffcfa2','dawn'],shambhala:['#1c4d36','#e1eca9','forest'],olympics:['#005348','#d4ff83','court'],comedy:['#812930','#fbce98','curtain'],blizzcon:['#263761','#aee7fb','portal'],foundry:['#21241b','#ccff58','grid']};
function art(id){let [bg,ac,m]=themes[id]||themes.edc;let g='';const line=(x,y,x2,y2,w=2)=>`<path d="M${x} ${y}L${x2} ${y2}" stroke="${ac}" stroke-width="${w}"/>`;
if(m==='piers')for(let i=0;i<11;i++)g+=`<path d="M${530+i*39} -150 Q${230+i*62} 180 ${660+i*48} 670" stroke="${ac}" stroke-width="${i%3===0?18:3}" fill="none" opacity="${.12+i*.026}"/>`;
if(m==='bass')for(let i=0;i<20;i++)g+=`<ellipse cx="820" cy="300" rx="${55+i*24}" ry="${38+i*17}" fill="none" stroke="${ac}" stroke-width="${i%4===0?5:1}" opacity="${.5-i*.02}"/>`;
if(m==='hearts')for(let i=0;i<5;i++)g+=`<path d="M0 90 C-190 -60,-100 -180,0 -90 C100 -180,190 -60,0 90Z" transform="translate(${780-i*22} ${270+i*15}) scale(${3.8-i*.65}) rotate(-15)" fill="none" stroke="${ac}" stroke-width="2" opacity=".3"/>`;
if(m==='moon'){g+=`<circle cx="810" cy="240" r="188" fill="${ac}" opacity=".7"/><circle cx="735" cy="193" r="184" fill="${bg}"/>`;for(let i=0;i<28;i++)g+=`<circle cx="${450+(i*83)%650}" cy="${30+(i*53)%560}" r="${i%3+1}" fill="${ac}" opacity=".6"/>`}
if(m==='pixels')for(let i=0;i<56;i++){let x=550+(i*131)%640,y=(i*67)%630;g+=`<rect x="${x}" y="${y}" width="${i%3===0?70:24}" height="${i%3===0?70:24}" fill="${ac}" opacity="${i%4*.07+.06}" transform="rotate(12 ${x} ${y})"/>`}
if(m==='rays')for(let i=0;i<20;i++)g+=`<path d="M870 380L${870+800*Math.cos(i*.314)} ${380+800*Math.sin(i*.314)}" stroke="${['#ffdd84','#d6aac9','#e68753','#99cdb0'][i%4]}" stroke-width="32" opacity=".43"/>`;
if(m==='stairs')for(let i=0;i<13;i++)g+=`<path d="M${550+i*40} 640V${550-i*46}H1250" fill="none" stroke="${ac}" opacity=".23" stroke-width="${i%3===0?10:2}"/>`;
if(m==='records')for(let i=0;i<22;i++)g+=`<circle cx="920" cy="280" r="${60+i*17}" fill="none" stroke="${ac}" stroke-width="${i%4===0?5:1}" opacity=".28"/>`;
if(m==='orbit'){for(let i=0;i<7;i++)g+=`<ellipse cx="830" cy="300" rx="${90+i*55}" ry="${230+i*30}" fill="none" stroke="${ac}" opacity=".3" transform="rotate(${i*25} 830 300)"/>`;g+=`<circle cx="830" cy="300" r="50" fill="${ac}" opacity=".6"/>`}
if(m==='sun'||m==='dawn'){for(let i=0;i<13;i++)g+=`<path d="M${800-220+i*15} ${210+i*16}H${800+220-i*15}" stroke="${ac}" stroke-width="10" opacity=".5"/>`;for(let i=0;i<5;i++)g+=`<path d="M0 ${610-i*22}Q540 ${340+i*45} 1200 ${540-i*33}" fill="none" stroke="${ac}" stroke-width="2" opacity=".3"/>`}
if(m==='forest')for(let i=0;i<18;i++){let x=500+i*43,y=30+(i*91)%190;g+=`<path d="M${x} 650V${y} M${x-50} ${y+165}L${x} ${y+55}L${x+50} ${y+165}M${x-36} ${y+100}L${x} ${y+10}L${x+36} ${y+100}" fill="none" stroke="${ac}" stroke-width="5" opacity="${.1+(i%4)*.07}"/>`}
if(m==='court'){g+=`<g transform="translate(640 45) rotate(17 230 220)" fill="none" stroke="${ac}" opacity=".5"><rect width="430" height="550" stroke-width="4"/><path d="M0 180H430M215 180V550M0 450H430" stroke-width="3"/><circle cx="340" cy="290" r="23" fill="${ac}"/></g>`}
if(m==='curtain')for(let i=0;i<18;i++)g+=`<path d="M${420+i*47} 0Q${300+i*70} 250 ${530+i*39} 680" stroke="${ac}" fill="none" stroke-width="14" opacity=".1"/>`;
if(m==='portal')for(let i=0;i<7;i++)g+=`<rect x="${680-i*30}" y="${70-i*30}" width="${230+i*60}" height="${420+i*60}" rx="${115+i*30}" fill="none" stroke="${ac}" stroke-width="3" opacity="${.5-i*.06}"/>`;
if(m==='grid')for(let i=0;i<22;i++){g+=line(500+i*32,0,500+i*32,700,1);g+=line(490,i*35,1250,i*35,1)}
return `<svg viewBox="0 0 1200 650" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="sceneFade"><stop stop-color="${bg}"/><stop offset=".52" stop-color="${bg}" stop-opacity=".05"/></linearGradient></defs>${g}<rect width="1200" height="650" fill="url(#sceneFade)"/></svg>`}
function filtered(){let f=$('#showFilter').value;return D.events.filter(e=>f==='all'||(f==='past'?isPast(e):!isPast(e)))}
function setHash(hash){history.replaceState(null,'',hash)}
function choose(id,update=true){const e=D.events.find(e=>e.id===id);if(!e)return;selected=e;if(!filtered().includes(e))$('#showFilter').value='all';renderNight();if(update)$('#showRail [aria-pressed=true]')?.scrollIntoView({block:'nearest',inline:'center',behavior:motion?'instant':'smooth'});if(update)setHash('#'+id)}
function renderRail(){const list=filtered();$('#showRail').innerHTML=list.map(e=>`<button class="show-tab" data-event="${e.id}" aria-pressed="${e.id===selected.id}">${esc(e.name)}<small>${esc(e.stamp)}${isPast(e)?' · PAST DATE':''}</small></button>`).join('');$('#showRail').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.event));$('#emptyShows').hidden=!!list.length;$('#showScene').hidden=!list.length;$('.below-scene').hidden=!list.length}
function renderNight(){renderRail();let [bg,ac]=themes[selected.id],ink=selected.id==='pokemon'||selected.id==='summit'?'#14231a':'#f7f0df';$('#showScene').style.setProperty('--scene-bg',bg);$('#showScene').style.setProperty('--scene-accent',ac);$('#showScene').style.setProperty('--scene-ink',ink);$('#showScene').dataset.event=selected.id;$('#sceneArt').innerHTML=art(selected.id);$('#showStamp').textContent=selected.stamp+(isPast(selected)?' / PAST DATE':'');$('#showCity').textContent=selected.city;$('#showCrew').textContent=selected.crew;$('#showTitle').textContent=selected.name;$('#showLine').textContent=selected.line;$('#showVenue').textContent=selected.venue;$('#wonderLabel').textContent=window.AfterHoursWonders?.label(selected.id)||'Find a little magic';let list=filtered();$('#showNumber').textContent=String(list.indexOf(selected)+1).padStart(2,'0')+' / '+String(list.length).padStart(2,'0')}
function open(mode,kicker,html){if(!dialog.open)lastFocus=document.activeElement;stopAll();window.AfterHoursWonders?.destroy();dialogMode=mode;dialog.dataset.mode=mode;$('#dialogKicker').textContent=kicker;$('#dialogBody').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';$('#closeDialog').focus();}
function close(){stopAll();window.AfterHoursWonders?.destroy();dialog.close();document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus();}
function transport(label){$('#transportLabel').textContent=label;$('#transport').hidden=false}
function stopOther(except){document.querySelectorAll('video,audio').forEach(v=>{if(v!==except)v.pause()});document.querySelectorAll('.media-frame').forEach(f=>f.remove());$('#transport').hidden=true;window.AfterHoursWonders?.stopSound();}
function stopAll(){stopOther();window.AfterHoursInstrument?.stop();}
function bindMedia(){document.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>playMedia(b.dataset.media))}
function mediaChoices(ids){return ids.map(id=>{let m=D.media.find(m=>m.id===id);return m?`<button class="media-choice" data-media="${m.id}"><span><small>${esc(m.label)}</small><strong>${esc(m.artist)}</strong><span>${esc(m.title)}</span></span><span class="disc">▶</span></button>`:''}).join('')}
const eventMedia={portola:['dogblood','portola-playlist'],zeds:['zeds-set'],niteharts:['isoknock'],latenite:['alison'],pokemon:['alison'],pride:['galantis'],summit:['summit-set'],stevie:['stevie-catalog'],countdown:['galantis'],gryphus:['joyful'],edc:['alison'],shambhala:['shambhala-film'],foundry:['portola-playlist'],blizzcon:['joyful'],comedy:[],olympics:[]};
function story(){const e=selected,d=DEPTH[e.id];open('story',`${e.stamp} / ${e.city}`,`<h2 id="dialogTitle">${esc(e.name)}</h2><p class="dialog-lead">${esc(e.note)}</p><p class="dialog-sub">${esc(e.crew)} · ${esc(e.venue)}${isPast(e)?' · Past date; the date alone does not confirm attendance.':''}</p><div id="storyPlayer"></div>${mediaChoices(eventMedia[e.id]||[])}${d?.personalHistory?`<div class="story-personal"><p class="eyebrow">MY THREAD THROUGH THE MUSIC</p>${esc(d.personalHistory)}</div>`:''}<div class="story-grid">${(d?.chapters||[{label:'THE INVITATION',title:e.line,text:e.blurb,url:e.url,linkLabel:'Explore the official event'}]).map(c=>`<article class="story-chapter"><p class="eyebrow">${esc(c.label)}</p><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p>${c.url?`<a class="source-link" href="${esc(c.url)}" target="_blank" rel="noopener">${esc(c.linkLabel||'Go deeper at the source')} ↗</a>`:''}</article>`).join('')}</div>${e.id==='portola'?`<details class="story-chapter"><summary>Our Saturday, without overplanning it</summary><p>3:40–4:30 oskar med k · 7:10–8:10 Robyn · 9:00–10:15 Dog Blood. All on the Pier stage. Soulwax starts at 9:55; catching that opening means leaving Dog Blood early and allowing time to walk.</p><a class="source-link" target="_blank" rel="noopener" href="https://portolamusicfestival.com/set-times/">Check the official set times ↗</a><br><a class="source-link" target="_blank" rel="noopener" href="https://www.jambase.com/festival/portola-2026?utm_source=mcp&utm_medium=chatgpt&utm_campaign=tool-result&utm_content=searchEvents">Explore the full bill on JamBase ↗</a></details>`:''}<div class="dialog-actions"><a href="${esc(e.url)}" target="_blank" rel="noopener">Official event & latest details ↗</a><button id="storyShare">Share this chapter ↗</button><button id="storyWonder">Find its little wonder ✳</button></div><p class="eyebrow">FOLLOW THE THREAD</p><div class="related">${(d?.related||[]).map(id=>D.events.find(x=>x.id===id)).filter(Boolean).map(x=>`<button data-related="${x.id}">${esc(x.name)} ↗</button>`).join('')}</div>`);bindMedia();$('#storyShare').onclick=()=>shareUrl(urlWith('#'+e.id));$('#storyWonder').onclick=wonder;document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>{choose(b.dataset.related);story()})}
function playMedia(id){let m=D.media.find(x=>x.id===id);if(!m)return;currentMedia=m;open('media',m.label,`<h2 id="dialogTitle">${esc(m.artist)}</h2><p class="dialog-lead">${esc(m.title)}</p><div class="provider-door"><a class="primary" href="${esc(m.url)}" target="_blank" rel="noopener">${m.type==='youtube'?'Watch on YouTube':m.type==='spotify'?'Listen on Spotify':'Listen on SoundCloud'} <span>↗</span></a><button id="loadEmbed">Play here ▶</button></div><div id="playerHost" class="player-poster" style="${m.type==='youtube'?'background-image:url(https://i.ytimg.com/vi/'+m.key+'/hqdefault.jpg)':''}"><span>THE SOUND & THE STORY</span></div><p class="player-note"><span>${esc(m.note)}</span><a href="${esc(m.url)}" target="_blank" rel="noopener">Open at the source ↗</a></p><div class="dialog-actions"><button id="backStory">← Back to ${esc(selected.name)}</button><button id="mediaStop">Stop playback</button></div>`);if(m.preview){$('#playerHost').classList.remove('player-poster');$('#playerHost').innerHTML=`<div class="album-preview"><img src="${esc(m.cover)}" alt="${esc(m.title)} album artwork"><div><p class="eyebrow">ALBUM PREVIEW · SPOTIFY</p><audio controls preload="none" src="${esc(m.preview)}" aria-label="${esc(m.title)} preview"></audio></div></div>`;const a=$('#playerHost audio');a.onplay=()=>{stopOther(a);window.AfterHoursInstrument?.stop();transport(m.title+' · preview')};a.onpause=()=>$('#transport').hidden=true;a.onended=a.onpause;}let iframe=document.createElement('iframe');iframe.className='media-frame'+(m.type==='spotify'?' spotify':'');iframe.title=m.artist+' — '+m.title;iframe.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.src=m.type==='spotify'?`https://open.spotify.com/embed/${m.entity||'playlist'}/${m.key}?utm_source=generator&theme=0`:m.type==='soundcloud'?`https://w.soundcloud.com/player/?url=${encodeURIComponent(m.key)}&auto_play=true&show_comments=false&visual=true`:`https://www.youtube-nocookie.com/embed/${m.key}?autoplay=1&playsinline=1&rel=0`;$('#loadEmbed').onclick=()=>{stopAll();$('#playerHost').replaceChildren(iframe);$('#playerHost').classList.remove('player-poster');$('#loadEmbed').textContent='Player opened below';transport('Player open · '+m.artist);};$('#backStory').onclick=story;$('#mediaStop').onclick=()=>{stopAll();$('#playerHost').innerHTML='<p>Playback stopped. Open the source link below to keep listening.</p>'}}
function memory(){open('memory','FROM MY EDC ARCHIVE',`<h2 id="dialogTitle">A little of being there.</h2><video id="memoryVideo" class="memory-film" controls playsinline preload="auto" poster="assets/edc-film-poster.webp"><source src="assets/edc-memory.mp4" type="video/mp4"><track kind="captions" src="assets/edc-captions.vtt" srclang="en" label="Sound descriptions"></video><p class="player-note"><span>My own 20-second EDC memory. Music, lights, a crowd in motion.</span><a href="assets/edc-memory.mp4" target="_blank">Open the film ↗</a></p><div class="dialog-actions"><button id="memorySet">Stay for Alison’s full EDC set ↗</button><button id="memoryPeople">The people behind the feeling ↘</button></div>`);const v=$('#memoryVideo');v.volume=.55;v.play().then(()=>transport('My EDC memory')).catch(()=>notify('Tap play on the film to bring in the sound.'));v.onended=()=>{$('#transport').hidden=true};v.onplay=()=>transport('My EDC memory');v.onpause=()=>{$('#transport').hidden=true};$('#memorySet').onclick=()=>playMedia('alison');$('#memoryPeople').onclick=()=>{close();$('#people').scrollIntoView({behavior:motion?'instant':'smooth'})}}
function light(id){if(!seen.includes(id)){seen.push(id);try{localStorage.setItem('afterhours-lights',JSON.stringify(seen))}catch{}renderLights();renderThreads();}}
function renderLights(){$('#sparkCount').textContent=seen.length?`${seen.length} little ${seen.length===1?'wonder':'wonders'} found. Your constellation is growing.`:'Every little wonder you find leaves a light.';$('#constellation').innerHTML=seen.map((id,i)=>`<i style="left:${62+(i*17)%35}%;top:${(i*29)%90}%" title="${esc(id)}"></i>`).join('')}
function renderThreads(){const pairs=[{ids:['portola','niteharts'],title:'Brennan · across the crowd',go:'portola'},{ids:['zeds','olympics'],title:'Foster · a rain check, a birthday',go:'olympics'},{ids:['edc','pokemon'],title:'Alison · the thread keeps glowing',go:'pokemon'}];$('#threadsFound').innerHTML=pairs.filter(p=>p.ids.every(id=>seen.includes(id))).map(p=>`<button data-thread="${p.go}"><small>TWO LIGHTS. ONE THREAD.</small>${p.title} ↗</button>`).join('');$('#threadsFound').querySelectorAll('button').forEach(b=>b.onclick=()=>{choose(b.dataset.thread);story()})}
function wonder(){open('wonder',selected.name+' / A LITTLE WONDER',`<h2 id="dialogTitle">${esc(window.AfterHoursWonders.label(selected.id))}</h2><div id="wonderRoot"></div><div class="dialog-actions"><button id="wonderStory">Dig into the sound & story ↗</button><button id="wonderJam">Carry the feeling into your own loop ↗</button></div>`);window.AfterHoursWonders.mount($('#wonderRoot'),selected,{reducedMotion:motion,onComplete:()=>light(selected.id),onSound:()=>{window.AfterHoursInstrument?.stop();document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('iframe.media-frame').forEach(f=>f.remove());transport('Original sound · '+selected.name)}});$('#wonderStory').onclick=story;$('#wonderJam').onclick=()=>{jamState=patternFromWonder(selected.id,window.AfterHoursWonders.snapshot());play()}}
function patternFromWonder(id,s={}){const group=['zeds','niteharts','pokemon','olympics'].includes(id)?'dnb174':['portola','foundry','pride','summit','countdown'].includes(id)?'house128':'warm112';const seed=D.events.findIndex(e=>e.id===id)+(s?.mode||0)+(s?.chosen?.length||0);return {version:1,preset:group,bpm:{warm112:112,house128:128,dnb174:174}[group],volume:.12,tracks:Array.from({length:4},(_,t)=>Array.from({length:16},(_,i)=>+(t===0?(group==='dnb174'?[0,6,8,14].includes(i):i%4===0):t===1?i%8===4:t===2?(i+seed)%3===0:(i+seed)%8===0)))};}
function play(){open('play','A LITTLE ORIGINAL SOUND / FROM US',`<h2 id="dialogTitle">Your turn to play.</h2><p class="dialog-sub">Tap a few lights. Change the feeling. Pass your loop to someone you love.</p><div id="jam"></div><div class="dialog-actions"><button id="shareLoop">Send this loop ↗</button><button id="resetLoop">Start with a fresh pattern</button></div><p class="dialog-sub">Original synthesized music. Your loop travels in its link; no account or live connection needed.</p>`);window.AfterHoursInstrument.mount($('#jam'),{reducedMotion:motion,onStart:()=>{stopOther();transport('Your original loop')},onChange:s=>{jamState=s;try{localStorage.setItem('afterhours-pattern',JSON.stringify(s))}catch{}}});if(jamState&&!window.AfterHoursInstrument.restore(jamState)){notify('That shared loop could not be read. A fresh pattern is ready.');jamState=null;}$('#jam').addEventListener('click',e=>{if(e.target.closest('.jam-play')?.getAttribute('aria-pressed')==='false')$('#transport').hidden=true});$('#shareLoop').onclick=()=>{const s=window.AfterHoursInstrument.serialize();shareUrl(urlWith('#play?loop='+encodeURIComponent(btoa(JSON.stringify(s))))) };$('#resetLoop').onclick=()=>{jamState=null;window.AfterHoursInstrument.restore({version:1,preset:'warm112',bpm:112,volume:.12,tracks:[[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0],[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],[1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0],[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]]});notify('A fresh little beginning.')}}
function renderPerson(){const p=person;$('#personTabs').innerHTML=D.people.map(p=>`<button data-person="${p.id}" aria-pressed="${p.id===person.id}">${esc(p.name)}</button>`).join('');$('#personKicker').textContent=p.kicker;$('#personTitle').textContent=p.title;$('#personBody').textContent=p.body;$('#personMemory').textContent=p.memory;document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{person=D.people.find(p=>p.id===b.dataset.person);renderPerson();setHash('#people/'+person.id)});$('#personNext').onclick=()=>{choose(p.next);$('#nights').scrollIntoView({behavior:motion?'instant':'smooth'})};$('#personMusic').onclick=()=>{choose(p.next);if(p.id==='foster')wonder();else playMedia(p.media)};$('#personMusic').textContent=p.id==='foster'?'Foster’s drop ✳':'A little of the feeling ▶'}
function urlWith(hash){return location.origin+location.pathname+hash}
async function shareUrl(url){open('share','PASS THE FEELING ON',`<h2 id="dialogTitle">A little invitation.</h2><p class="dialog-lead">Send a night, a memory, or a little music to someone you love.</p><label for="shareText">Your shareable link</label><input id="shareText" class="share-field" readonly value="${esc(url)}"><div class="dialog-actions"><button id="copyShare">Copy link ↗</button></div><p id="shareStatus" role="status" class="dialog-sub">This link opens the same chapter or musical pattern.</p>`);$('#shareText').onclick=()=>$('#shareText').select();$('#copyShare').onclick=async()=>{try{await navigator.clipboard.writeText(url);$('#shareStatus').textContent='Link copied. Ready to send with a little love.'}catch{$('#shareText').select();$('#shareStatus').textContent='Select and copy the link above.'}};}

function credits(){open('credits','MADE WITH LOVE',`<h2 id="dialogTitle">A life well danced.</h2><p class="dialog-lead">I made this for the people who turn music into memories with me. The night is a beginning. The friendship is the part I keep.</p><p>My real EDC and Ultra photographs and EDC film live here beside an imagined sunrise created with Higgsfield. The original little instruments and visual worlds are made for play. Artist recordings always come from their own players and sources.</p><p>Memories and upcoming plans are kept distinct. Dates and lineups can change; every chapter has a link to the official event. Your patterns and discovered lights stay in this browser unless you choose to copy a sharing link.</p><p class="dialog-sub">Creative direction: Gordon. Built in collaboration with Codex and Darby. Music discovery with Spotify; event cross-checks with JamBase.</p><a class="source-link" href="https://open.spotify.com/playlist/28hgvKjRRH5cDOHgz2Qn7G?utm_source=openai&utm_medium=chatgpt" target="_blank" rel="noopener">Explore EDM Joyful Adventures With Friends on Spotify ↗</a>`)}
function route(){let h;try{h=decodeURIComponent(location.hash.slice(1));}catch{return;}if(h.startsWith('play')){const q=new URLSearchParams(h.split('?')[1]||'');try{if(q.get('loop'))jamState=JSON.parse(atob(q.get('loop')))}catch{notify('That shared loop could not be read. Here is a fresh one.')}play();return}if(h.startsWith('people/')){person=D.people.find(p=>p.id===h.split('/')[1])||D.people[0];renderPerson();$('#people').scrollIntoView();return}if(D.events.some(e=>e.id===h)){choose(h,false);$('#nights').scrollIntoView()}}
$('#showFilter').onchange=()=>{const list=filtered();if(list.length&&!list.includes(selected))selected=list[0];renderNight()};$('#prevShow').onclick=()=>{const l=filtered();choose(l[(l.indexOf(selected)-1+l.length)%l.length].id)};$('#nextShow').onclick=()=>{const l=filtered();choose(l[(l.indexOf(selected)+1)%l.length].id)};$('#openStory').onclick=story;$('#openWonder').onclick=wonder;$('#shareNight').onclick=()=>shareUrl(urlWith('#'+selected.id));$('#shareHome').onclick=()=>shareUrl(urlWith('#home'));$('#playMemory').onclick=memory;$('#closeDialog').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});$('#dialogStop').onclick=()=>{stopAll();notify('A little quiet.')};$('#stopAll').onclick=()=>{stopAll();notify('A little quiet.')};document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='play'?play():credits());$('#fullPhoto').onclick=()=>open('photo','ULTRA MIAMI / MY PHOTO ALBUM','<h2 id="dialogTitle">Keep this feeling.</h2><img class="photo-full" src="assets/ultra-miami-1600.webp" alt="Full photograph from Gordon’s Ultra Miami archive">');
function setMotion(){document.body.classList.toggle('motion-paused',motion);$('#motionToggle').setAttribute('aria-pressed',String(motion));$('#motionToggle').textContent=motion?'Motion paused':'Pause motion';if(motion)$('#dawnFilm').pause()}
$('#motionToggle').onclick=()=>{motion=!motion;setMotion();try{localStorage.setItem('afterhours-motion',motion?'paused':'on')}catch{}};$('#filmToggle').onclick=()=>{const v=$('#dawnFilm');if(v.paused){v.play().then(()=>$('#filmToggle').textContent='Pause the dawn film').catch(()=>notify('The film could not start. The sunrise is still here.'))}else{v.pause();$('#filmToggle').textContent='Play the dawn film'}};$('#dawnFilm').onpause=()=>$('#filmToggle').textContent='Play the dawn film';document.addEventListener('wonder-sound-ended',()=>{$('#transport').hidden=true});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(dialog.open&&dialogMode==='wonder')close();else stopAll()}});window.addEventListener('hashchange',()=>{if(dialog.open)close();route()});
const next=D.events.find(e=>!isPast(e)&&e.date);if(next){$('#nextNight').href='#'+next.id;$('#nextNight').innerHTML='NEXT UP / '+esc(next.name)+' <span>↘</span>';$('#nextNight').onclick=()=>{choose(next.id,false);$('#nights').scrollIntoView({behavior:motion?'instant':'smooth'})}}renderNight();renderPerson();renderLights();renderThreads();setMotion();route();
})();
