(()=>{'use strict';
const $=s=>document.querySelector(s), D=window.AFTERHOURS_DATA, DEPTH=window.ARTIST_DEPTH||{}, dialog=$('#experienceDialog');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const isPast=e=>!!e.date&&(e.endDate||e.date)<today;let selected=D.events.find(e=>!isPast(e)&&e.date)||D.events[0],person=D.people[0],currentMedia=null,dialogMode='',lastFocus=null,toastTimer,motion=matchMedia('(prefers-reduced-motion: reduce)').matches,seen=[],jamState;
try{seen=JSON.parse(localStorage.getItem('afterhours-lights')||'[]').filter(x=>D.events.some(e=>e.id===x));const s=localStorage.getItem('afterhours-pattern');if(s)jamState=JSON.parse(s);motion=motion||localStorage.getItem('afterhours-motion')==='paused';}catch{}
function notify(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
const PHOTOS=window.PHOTO_MEMORIES||[],ARTISTS=window.AFTERHOURS_ARTISTS||{};
let albumContext='all',cinemaTimer=null,cinemaPause=null;
const ALBUMS={'shambhala':'Shambhala','gryphus':'Gryphus','countdown':'Countdown','summit':'John Summit','ggp-games':'Zero Proof','ggp-mixer':'GGP @ GDC','sincity':'Sin City','early-nights':'The earlier nights'};
const albumName=k=>ALBUMS[k]||D.events.find(e=>e.id===k)?.name||'All our albums';
const albumList=k=>k==='all'?PHOTOS:PHOTOS.filter(m=>m.album===k||m.events.includes(k));
function stopCinema(){clearInterval(cinemaTimer);cinemaTimer=null;}

const themes={folsom:['#392338','#ffc4f0','street'],'ggp-games':['#554029','#f7dba6','table'],'ggp-mixer':['#263249','#a6ead6','decks'],'fang-live':['#54302a','#f4b785','windows'],sincity:['#722f38','#ffc798','dodge'],portola:['#5140c9','#deff81','piers'],zeds:['#071b29','#b9e8ec','bass'],niteharts:['#ab392c','#f8e5ad','hearts'],latenite:['#261747','#f5aade','moon'],pokemon:['#efc850','#152761','pixels'],pride:['#924c66','#ffefab','rays'],summit:['#243b30','#d4e4af','stairs'],stevie:['#6a281c','#ffd686','records'],countdown:['#18293b','#e8d69a','orbit'],gryphus:['#733d27','#f0e7c1','sun'],edc:['#544983','#ffcfa2','dawn'],shambhala:['#1c4d36','#e1eca9','forest'],olympics:['#005348','#d4ff83','court'],comedy:['#812930','#fbce98','curtain'],blizzcon:['#263761','#aee7fb','portal'],foundry:['#21241b','#ccff58','grid']};
function art(id){let [bg,ac,m]=themes[id]||themes.edc;let g='';const line=(x,y,x2,y2,w=2)=>`<path d="M${x} ${y}L${x2} ${y2}" stroke="${ac}" stroke-width="${w}"/>`;
if(m==='street'){for(let j=0;j<4;j++)g+=`<path d="M${580+j*100} 0L${720+j*125} 650" fill="none" stroke="${ac}" stroke-width="3" opacity=".18"/>`;for(let j=0;j<7;j++)g+=`<path d="M460 ${80+j*85}Q850 ${150+j*65} 1260 ${50+j*85}" fill="none" stroke="${ac}" stroke-width="2" opacity=".3"/>`;for(let j=0;j<16;j++)g+=`<circle cx="${580+(j*97)%550}" cy="${65+(j*131)%500}" r="${5+j%4}" fill="${ac}" opacity=".7"/>`}
if(m==='piers')for(let i=0;i<11;i++)g+=`<path d="M${530+i*39} -150 Q${230+i*62} 180 ${660+i*48} 670" stroke="${ac}" stroke-width="${i%3===0?18:3}" fill="none" opacity="${.12+i*.026}"/>`;
if(m==='bass')for(let i=0;i<20;i++)g+=`<ellipse cx="820" cy="300" rx="${55+i*24}" ry="${38+i*17}" fill="none" stroke="${ac}" stroke-width="${i%4===0?5:1}" opacity="${.5-i*.02}"/>`;
if(m==='hearts')for(let i=0;i<5;i++)g+=`<path d="M0 90 C-190 -60,-100 -180,0 -90 C100 -180,190 -60,0 90Z" transform="translate(${780-i*22} ${270+i*15}) scale(${3.8-i*.65}) rotate(-15)" fill="none" stroke="${ac}" stroke-width="2" opacity=".3"/>`;
if(m==='moon'){g+=`<circle cx="810" cy="240" r="188" fill="${ac}" opacity=".7"/><circle cx="735" cy="193" r="184" fill="${bg}"/>`;for(let i=0;i<28;i++)g+=`<circle cx="${450+(i*83)%650}" cy="${30+(i*53)%560}" r="${i%3+1}" fill="${ac}" opacity=".6"/>`}
if(m==='pixels')for(let i=0;i<56;i++){let x=550+(i*131)%640,y=(i*67)%630;g+=`<rect x="${x}" y="${y}" width="${i%3===0?70:24}" height="${i%3===0?70:24}" fill="${ac}" opacity="${i%4*.07+.06}" transform="rotate(12 ${x} ${y})"/>`}
if(m==='rays')for(let i=0;i<20;i++)g+=`<path d="M870 380L${870+800*Math.cos(i*.314)} ${380+800*Math.sin(i*.314)}" stroke="${['#ffdd84','#d6aac9','#e68753','#99cdb0'][i%4]}" stroke-width="32" opacity=".43"/>`;
if(m==='stairs')for(let i=0;i<13;i++)g+=`<path d="M${550+i*40} 640V${550-i*46}H1250" fill="none" stroke="${ac}" opacity=".23" stroke-width="${i%3===0?10:2}"/>`;
if(m==='records')for(let i=0;i<22;i++)g+=`<circle cx="920" cy="280" r="${60+i*17}" fill="none" stroke="${ac}" stroke-width="${i%4===0?5:1}" opacity=".28"/>`;
if(m==='orbit'){for(let i=0;i<7;i++)g+=`<ellipse cx="830" cy="300" rx="${90+i*55}" ry="${230+i*30}" fill="none" stroke="${ac}" opacity=".3" transform="rotate(${i*25} 830 300)"/>`;g+=`<circle cx="830" cy="300" r="50" fill="${ac}" opacity=".6"/>`}
if(m==='sun'||m==='dawn'){for(let i=0;i<13;i++)g+=`<path d="M${800-220+i*15} ${210+i*16}H${800+220-i*15}" stroke="${ac}" stroke-width="10" opacity=".5"/>`;for(let i=0;i<5;i++)g+=`<path d="M0 ${610-i*22}Q540 ${340+i*45} 1200 ${540-i*33}" fill="none" stroke="${ac}" stroke-width="2" opacity=".3"/>`}
if(m==='forest')for(let i=0;i<18;i++){let x=500+i*43,y=30+(i*91)%190;g+=`<path d="M${x} 650V${y} M${x-50} ${y+165}L${x} ${y+55}L${x+50} ${y+165}M${x-36} ${y+100}L${x} ${y+10}L${x+36} ${y+100}" fill="none" stroke="${ac}" stroke-width="5" opacity="${.1+(i%4)*.07}"/>`}
if(m==='dodge'){g+=`<g transform="translate(610 70) rotate(-12 230 220)" fill="none" stroke="${ac}"><rect width="470" height="490" stroke-width="3" opacity=".5"/><path d="M0 245H470M155 0V490M310 0V490" opacity=".3"/><circle cx="340" cy="180" r="73" fill="${ac}" opacity=".8"/><path d="M210 290L285 235M190 275L270 218M226 310L300 253" stroke-width="8" opacity=".35"/></g>`}
if(m==='court'){g+=`<g transform="translate(640 45) rotate(17 230 220)" fill="none" stroke="${ac}" opacity=".5"><rect width="430" height="550" stroke-width="4"/><path d="M0 180H430M215 180V550M0 450H430" stroke-width="3"/><circle cx="340" cy="290" r="23" fill="${ac}"/></g>`}
if(m==='curtain')for(let i=0;i<18;i++)g+=`<path d="M${420+i*47} 0Q${300+i*70} 250 ${530+i*39} 680" stroke="${ac}" fill="none" stroke-width="14" opacity=".1"/>`;
if(m==='portal')for(let i=0;i<7;i++)g+=`<rect x="${680-i*30}" y="${70-i*30}" width="${230+i*60}" height="${420+i*60}" rx="${115+i*30}" fill="none" stroke="${ac}" stroke-width="3" opacity="${.5-i*.06}"/>`;
if(m==='table'){g+=`<circle cx="820" cy="325" r="245" fill="none" stroke="${ac}" opacity=".25" stroke-width="4"/>`;for(let i=0;i<6;i++)g+=`<rect x="${640+i*43}" y="${140+(i%3)*115}" width="85" height="110" rx="9" fill="${ac}" opacity=".25" transform="rotate(${i*13-25} 820 325)"/>`}
if(m==='decks'){g+=`<circle cx="740" cy="240" r="170" fill="none" stroke="#e9a8c6" stroke-width="25" opacity=".4"/><circle cx="960" cy="420" r="170" fill="none" stroke="${ac}" stroke-width="25" opacity=".4"/><path d="M650 570H1030" stroke="${ac}" stroke-width="3"/><path d="M840 550V590" stroke="${ac}" stroke-width="14"/>`}
if(m==='windows'){for(let i=0;i<3;i++)g+=`<path d="M${630+i*150} 520V220a55 55 0 0 1 110 0V520Z" fill="${ac}" opacity="${.12+i*.08}"/><path d="M${630+i*150} 330H${740+i*150}M${685+i*150} 165V520" stroke="${bg}" stroke-width="5"/>`}
if(m==='grid')for(let i=0;i<22;i++){g+=line(500+i*32,0,500+i*32,700,1);g+=line(490,i*35,1250,i*35,1)}
return `<svg viewBox="0 0 1200 650" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="sceneFade"><stop stop-color="${bg}"/><stop offset=".52" stop-color="${bg}" stop-opacity=".05"/></linearGradient></defs>${g}<rect width="1200" height="650" fill="url(#sceneFade)"/></svg>`}
function filtered(){let f=$('#showFilter').value;return D.events.filter(e=>f==='all'||(f==='past'?isPast(e):!isPast(e)))}
function setHash(hash){history.replaceState(null,'',hash)}
function choose(id,update=true){const e=D.events.find(e=>e.id===id);if(!e)return;selected=e;if(!filtered().includes(e))$('#showFilter').value='all';renderNight();if(update)$('#showRail [aria-pressed=true]')?.scrollIntoView({block:'nearest',inline:'center',behavior:motion?'instant':'smooth'});if(update)setHash('#'+id)}
function renderRail(){const list=filtered();$('#showRail').innerHTML=list.map(e=>`<button class="show-tab" data-event="${e.id}" aria-pressed="${e.id===selected.id}">${esc(e.name)}<small>${esc(e.stamp)}${isPast(e)?' · PAST DATE':''}</small></button>`).join('');$('#showRail').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.event));$('#emptyShows').hidden=!!list.length;$('#showScene').hidden=!list.length;$('.below-scene').hidden=!list.length}
/* Fourteen events had no picture at all and fell back to a flat colour panel.
   Each now has its own poster, drawn from that event's real place: Pier 80's
   cranes, the Foundry's steel sash windows, the Palm Springs ridge, the speedway
   at dawn. The seven events that carry Gordon's own photographs are NOT in this
   set and never will be: a made picture does not stand in front of a real memory. */
const KEYART=new Set(['blizzcon','comedy','portola','folsom','foundry','zeds','niteharts',
  'latenite','pokemon','pride','stevie','edc','fang-live','olympics']);
function renderNight(){renderRail();let [bg,ac]=themes[selected.id],ink=selected.id==='pokemon'?'#14231a':'#f7f0df';$('#showScene').style.setProperty('--scene-bg',bg);$('#showScene').style.setProperty('--scene-accent',ac);$('#showScene').style.setProperty('--scene-ink',ink);$('#showScene').dataset.event=selected.id;const cover=PHOTOS.find(m=>m.id===selected.cover);const key=!cover&&KEYART.has(selected.id);$('#showScene').classList.toggle('has-archive',!!cover||key);$('#showScene').classList.toggle('has-keyart',key);$('#sceneArt').innerHTML=cover?`<img class="scene-archive" src="${cover.src}" alt=""><div class="archive-shade"></div><span class="scene-photo-credit">${esc(selected.coverLabel)}</span>`:key?`<img class="scene-archive scene-keyart" src="assets/keyart/${selected.id}.webp" alt="An imagined poster for ${esc(selected.name)}" loading="lazy" width="1280" height="716"><div class="archive-shade"></div><div class="keyart-grain" aria-hidden="true"></div><span class="scene-photo-credit">IMAGINED POSTER \u00b7 NOT A PHOTOGRAPH</span>`:art(selected.id);$('#showStamp').textContent=selected.stamp+(isPast(selected)?' / PAST DATE':'');$('#showCity').textContent=selected.city;$('#showCrew').textContent=selected.crew;$('#showTitle').textContent=selected.name;$('#showLine').textContent=selected.line;$('#showVenue').textContent=selected.venue;const n=PHOTOS.filter(m=>m.events.includes(selected.id)).length;$('#showAlbum').hidden=!n;$('#showAlbum').textContent=`Our album · ${n} photographs ↗`;$('#showAlbum').onclick=()=>photoBox(selected.id);$('#wonderLabel').textContent=window.AfterHoursWonders?.label(selected.id)||'Find a little magic';let list=filtered();$('#showNumber').textContent=String(list.indexOf(selected)+1).padStart(2,'0')+' / '+String(list.length).padStart(2,'0')}
function open(mode,kicker,html){stopCinema();cinemaPause=null;if(!dialog.open)lastFocus=document.activeElement;stopAll();window.AfterHoursWonders?.destroy();window.AfterHoursArtists?.destroy();dialogMode=mode;dialog.dataset.mode=mode;$('#dialogKicker').textContent=kicker;$('#dialogBody').innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';$('#closeDialog').focus();}
function close(){stopCinema();cinemaPause=null;stopAll();window.AfterHoursWonders?.destroy();window.AfterHoursArtists?.destroy();dialog.close();document.body.style.overflow='';if(lastFocus?.isConnected)lastFocus.focus();}
function transport(label){$('#transportLabel').textContent=label;$('#transport').hidden=false}
function stopOther(except){document.querySelectorAll('video,audio').forEach(v=>{if(v!==except&&!(Array.isArray(except)&&except.includes(v)))v.pause()});document.querySelectorAll('.media-frame').forEach(f=>f.remove());$('#transport').hidden=true;window.AfterHoursWonders?.stopSound();}
function stopAll(){stopOther();window.AfterHoursInstrument?.stop();window.AfterHoursArtists?.stop();}
function bindMedia(){document.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>playMedia(b.dataset.media))}
function mediaChoices(ids){return ids.map(id=>{let m=D.media.find(m=>m.id===id);return m?`<button class="media-choice" data-media="${m.id}"><span><small>${esc(m.label)}</small><strong>${esc(m.artist)}</strong><span>${esc(m.title)}</span></span><span class="disc">▶</span></button>`:''}).join('')}
const eventMedia={portola:['dogblood','portola-playlist'],zeds:['zeds-set'],niteharts:['isoknock'],latenite:['alison'],pokemon:['alison'],pride:['galantis'],summit:['summit-set'],stevie:['stevie-catalog'],countdown:['galantis'],gryphus:['ranch-recordings'],edc:['alison'],shambhala:['shambhala-film'],foundry:['portola-playlist'],blizzcon:['joyful'],comedy:[],olympics:['la28-world'],sincity:[],'ggp-games':['ggp-film'],'ggp-mixer':['ggp-film'],'fang-live':[]};
function photoCards(list){return list.map(m=>`<button class="photo-card" data-memory="${m.id}" aria-label="Open ${esc(m.title)}, ${esc(m.date)}, ${esc(m.time)}"><img src="${m.thumb}" alt="${esc(m.alt)}" loading="lazy" width="600" height="600"><span><strong>${esc(m.line)}</strong><small>${esc(m.title)} · ${esc(m.date)}</small></span><i aria-hidden="true">↗</i></button>`).join('')}
function bindPhotos(context='all'){document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>{albumContext=context;photoView(b.dataset.memory)});document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>photoBox(b.dataset.album));document.querySelectorAll('[data-film]').forEach(b=>b.onclick=()=>archiveFilm(b.dataset.film));}
function photoStrip(id){const list=PHOTOS.filter(m=>m.events.includes(id));return list.length?`<section class="story-photos" aria-label="Photographs from earlier chapters"><div class="album-heading"><p class="eyebrow">BEFORE THE NEXT NIGHT · OUR ALBUM</p><button data-album="${id}">All ${list.length} photographs ↗</button></div><div class="photo-strip">${photoCards(list.slice(0,6))}</div></section>`:''}
function filmDoor(key){return key==='ggp-mixer'?`<button class="film-door" data-film="ggp"><img src="assets/ggp-film-poster.webp" alt="The lights and dance floor at our 2026 GGP mixer"><span><small>FROM MY CAMERA · MARCH 2026</small><strong>Hear the room come alive.</strong><em>▶ 19 seconds · original sound</em></span></button>`:''}
function photoBox(key='all'){if(!ALBUMS[key]&&!D.events.some(e=>e.id===key))key='all';albumContext=key;const list=albumList(key);const tabs=`<nav class="album-tabs" aria-label="Choose a photo album"><button data-album="all" aria-pressed="${key==='all'}">All our albums</button>${Object.entries(ALBUMS).filter(([k])=>albumList(k).length).map(([k,title])=>`<button data-album="${k}" aria-pressed="${key===k}">${title} <small>${albumList(k).length}</small></button>`).join('')}</nav>`;const grid=key==='all'?`<div class="album-collection">${Object.entries(ALBUMS).filter(([k])=>albumList(k).length).map(([k,title])=>{const ms=albumList(k),m=ms.find(x=>x.id===({'shambhala':'shambhala-2025-together','gryphus':'gryphus-cale-2026','countdown':'countdown-2022-together','ggp-games':'zero-proof-friends','ggp-mixer':'ggp-2026-blue','summit':'summit-together-2025'}[k]))||ms[0];return `<button class="album-cover" data-album="${k}"><img src="${m.src}" alt="${esc(m.alt)}" loading="lazy"><span><small>${ms.length} PHOTOGRAPHS / FROM MY LIFE</small><strong>${title}</strong><i>Come back here ↗</i></span></button>`}).join('')}</div>`:`${filmDoor(key)}<div class="photo-grid">${photoCards(list)}</div>`;open('album','THE MOMENTS WE KEEP',`<h2 id="dialogTitle">${key==='all'?'We were here.':esc(albumName(key))+'. With you.'}</h2><div class="album-intro"><p class="dialog-sub">${key==='all'?'The people. The little looks. The part that comes home with us.':'A few of the moments I am glad we made time for.'}</p><button class="primary" id="unfoldAlbum">Let it unfold ▶</button></div>${tabs}${grid}<div class="dialog-actions"><button id="shareAlbum">Share this album ↗</button></div>`);bindPhotos(key);$('#shareAlbum').onclick=()=>shareUrl(urlWith('#photos/'+key));$('#unfoldAlbum').onclick=()=>photoCinema(key);}
function photoView(id){const m=PHOTOS.find(p=>p.id===id);if(!m)return;let list=albumList(albumContext);if(!list.includes(m)){albumContext=m.album||'all';list=albumList(albumContext)}const i=list.indexOf(m);open('photo',m.title+' / '+m.date,`<h2 id="dialogTitle">${esc(m.line)}</h2><figure class="archive-print"><img class="photo-full" src="${m.src}" alt="${esc(m.alt)}"><figcaption><span>${esc(m.title)} · ${esc(m.date)}</span><span>CAPTURED ${esc(m.time)}</span></figcaption></figure><div class="photo-nav"><button id="photoPrev" aria-label="Previous photograph">←</button><span>${i+1} / ${list.length}</span><button id="photoNext" aria-label="Next photograph">→</button></div><div class="dialog-actions"><button id="photoAll">← ${esc(albumName(albumContext))}</button><button id="photoUnfold">Let this album unfold ▶</button><button id="photoShare">Share this memory ↗</button></div><p class="eyebrow">WHERE THE STORY GOES NEXT</p><div class="related">${m.events.map(id=>D.events.find(e=>e.id===id)).filter(Boolean).map(e=>`<button data-photo-event="${e.id}">${esc(e.name)} ↗</button>`).join('')}</div>`);$('#photoPrev').onclick=()=>photoView(list[(i-1+list.length)%list.length].id);$('#photoNext').onclick=()=>photoView(list[(i+1)%list.length].id);$('#photoAll').onclick=()=>photoBox(albumContext);$('#photoUnfold').onclick=()=>photoCinema(albumContext);$('#photoShare').onclick=()=>shareUrl(urlWith('#memory/'+m.id));document.querySelectorAll('[data-photo-event]').forEach(b=>b.onclick=()=>{choose(b.dataset.photoEvent);story()});}
function photoCinema(key){const list=albumList(key);if(!list.length)return;let i=0,playing=!motion,active=0,request=0;open('cinema',albumName(key)+' / A LITTLE TIME TO REMEMBER',`<h2 id="dialogTitle" class="cinema-title">Stay a little.</h2><div class="memory-screen"><div class="memory-glow"></div><img class="memory-frame on" alt=""><img class="memory-frame" alt="" aria-hidden="true"></div><div class="cinema-caption"><div><p class="eyebrow" id="cinemaDate"></p><h3 id="cinemaLine"></h3></div><span id="cinemaCount"></span></div><div class="cinema-controls"><button id="cinemaPrev" aria-label="Previous memory">←</button><button id="cinemaPlay">${playing?'Pause the memories':'Play the memories'}</button><button id="cinemaNext" aria-label="Next memory">→</button><button id="cinemaAlbum">Browse this album ↗</button></div><p class="cinema-note">Pictures in motion. A little room to remember.</p>${filmDoor(key)}`);const frames=[...document.querySelectorAll('.memory-frame')];function show(first=false){const m=list[i],token=++request,next=first?0:1-active,img=frames[next];img.onload=()=>{if(!img.isConnected||token!==request)return;frames[active].classList.remove('on');frames[active].setAttribute('aria-hidden','true');img.classList.add('on');img.removeAttribute('aria-hidden');active=next;$('.memory-glow').style.backgroundImage=`url("${m.src}")`;$('#cinemaDate').textContent=m.title+' / '+m.date;$('#cinemaLine').textContent=m.line;$('#cinemaCount').textContent=String(i+1).padStart(2,'0')+' / '+list.length;};img.onerror=()=>{if(img.isConnected&&token===request)notify('This photograph could not load. The next memory is ready when you are.');};img.src=m.src;img.alt=m.alt;}
cinemaPause=()=>{playing=false;if($('#cinemaPlay'))$('#cinemaPlay').textContent='Play the memories';};function tick(){i=(i+1)%list.length;show()}function clock(){stopCinema();if(playing)cinemaTimer=setInterval(tick,6500)}show(true);clock();$('#cinemaPrev').onclick=()=>{i=(i-1+list.length)%list.length;show();clock()};$('#cinemaNext').onclick=()=>{tick();clock()};$('#cinemaPlay').onclick=()=>{playing=!playing;$('#cinemaPlay').textContent=playing?'Pause the memories':'Play the memories';clock()};$('#cinemaAlbum').onclick=()=>photoBox(key);bindPhotos(key);}
function archiveFilm(id){if(id!=='ggp')return;open('film','GGP @ GDC · THE 2026 MIXER',`<h2 id="dialogTitle">This is how it felt.</h2><video id="archiveVideo" class="memory-film" controls playsinline preload="metadata" poster="assets/ggp-film-poster.webp"><source src="assets/ggp-mixer-memory.mp4" type="video/mp4"><track kind="captions" src="assets/ggp-captions.vtt" srclang="en" label="Sound descriptions"></video><p class="player-note"><span>My camera. Our room. 19 seconds from DNA Lounge, after midnight at the March 11, 2026 mixer. Original sound.</span></p><div class="dialog-actions"><button id="filmAlbum">Back to the photographs ↗</button><button id="filmNextChapter">Foster + Sam · the next mixer ↗</button><button id="filmShare">Share this little film ↗</button></div>`);const v=$('#archiveVideo');v.volume=.5;v.onplay=()=>transport('Our GGP mixer · 2026');v.onpause=()=>$('#transport').hidden=true;v.onended=v.onpause;v.play().catch(()=>{});$('#filmShare').onclick=()=>shareUrl(urlWith('#film/ggp'));$('#filmAlbum').onclick=()=>photoBox('ggp-mixer');$('#filmNextChapter').onclick=()=>{choose('ggp-mixer');story()};}
function foundryPlace(id){const games=id==='ggp-games';return `<section class="foundry-place ${games?'is-table':'is-floor'}" aria-label="The Foundry SF, home to both GGP nights"><div class="foundry-heading"><p class="eyebrow">ONE ADDRESS · TWO NIGHTS TOGETHER</p><h3>The Foundry SF.</h3><p>1425 Folsom Street at 10th · SoMa</p></div><div class="foundry-nights"><button data-related="ggp-games" aria-current="${games?'true':'false'}"><small>MONDAY · MARCH 1</small><strong>Pull up a chair.</strong><span>4th Annual Zero Proof Board Game Night ↗</span></button><button data-related="ggp-mixer" aria-current="${!games?'true':'false'}"><small>TUESDAY · MARCH 2</small><strong>Meet us on the floor.</strong><span>21st Annual GGP @ GDC Mixer ↗</span></button></div><p class="foundry-feeling">${games?'A familiar room, a new round. Bring your curiosity; we’ll make room at the table.':'Fang Speare B2B Capnsmak. Foster and Sam behind the decks, our people all around them.'}</p><div class="foundry-links"><a href="https://www.google.com/maps/search/?api=1&query=The+Foundry+SF+1425+Folsom+Street+San+Francisco" target="_blank" rel="noopener">Find the front door ↗</a><a href="https://www.thefoundry.club/booking" target="_blank" rel="noopener">See the real space ↗</a></div><details class="foundry-history"><summary>Get to know the room</summary><p>A 1936 industrial building with steel-sash windows and exposed trusses. The floor can change with the gathering; the venue describes acoustic treatment and a high-fidelity sound system. People from The Faight and Same Same But Different Fest are behind its current music chapter.</p><p>Zero Proof brought us here in 2025 and 2026. Now both of our 2027 nights share this address. Event hours will follow.</p><a class="source-link" href="https://www.thefoundry.club/floor/ninety-years-on-folsom" target="_blank" rel="noopener">The building’s story ↗</a> · <a class="source-link" href="https://www.thefoundry.club/floor/who-we-are" target="_blank" rel="noopener">The people behind the venue ↗</a></details></section>`}
const SELF_PORTRAIT = ["I make room in my life for music, play, and the people I want to share them with. A dance floor, a board game, a road trip, a ridiculous little bass drop: I love the moments when we stop explaining ourselves and just enjoy being together.", "I am curious. I want to know how an artist found their sound, what a friend is making, and what might happen if we try something new. I still want to be surprised. Sometimes I will want the whole history. Sometimes I will just want you to press the button and hear what happens.", "My friendships carry whole chapters of my life. Shannon has known me since San Francisco in the 1990s. One of my oldest, deepest friends, still with me for Folsom, Pride, and my birthday. Joe and our Countdown tradition. Foster and Sam stepping behind the decks together. The next adventure means more because of everything we already share.", "And I love being welcomed, too. Being invited. Having someone make room for me. I remember how that feels.", "If I am sharing this with you, I want you to know how much it means to me that you are part of my life. I am excited about the music, the games, the places. I am excited that we get to be there together."];
function gordonLetter(){open('letter','A QUESTION FROM SHANNON MURRAY',`<h2 id="dialogTitle">What should people<br>know about me?</h2><div class="gordon-letter">${SELF_PORTRAIT.map(p=>`<p>${esc(p)}</p>`).join('')}<p class="letter-signature">LYMI,<br>Gordon</p></div><div class="dialog-actions"><button id="letterToShannon">The friend who asked ↗</button><button id="shareGordonLetter">Share this little note ↗</button></div>`);$('#letterToShannon').onclick=()=>{close();person=D.people.find(p=>p.id==='shannon');renderPerson();setHash('#people/shannon');$('#people').scrollIntoView({behavior:motion?'instant':'smooth'})};$('#shareGordonLetter').onclick=()=>shareUrl(urlWith('#about/gordon'))}
function shannonRelic(){open('relic','SHANNON + GORDON · A LITTLE TIME CAPSULE',`<h2 id="dialogTitle">2002. Still our story.</h2><p class="dialog-lead">I sent you this again in June, already looking ahead to our “25th posterversary” in 2027. Some of our history fits on a page. There is so much life around it.</p><figure class="shannon-relic"><img src="assets/shannon-pride-2002.webp" width="1200" height="1600" alt="A photograph of the 2002 Christopher Street West Pride Guide cover, Family, Amore and Paz."><figcaption>Our 2002 Pride time capsule · A photograph from my personal archive.</figcaption></figure><div class="dialog-actions"><button id="relicPride">Our next Pride + birthday ↗</button><button id="relicLetter">Back to my note to Shannon ↗</button></div>`);$('#relicPride').onclick=()=>{choose('pride');story()};$('#relicLetter').onclick=()=>{close();person=D.people.find(p=>p.id==='shannon');renderPerson();setHash('#people/shannon');$('#people').scrollIntoView({behavior:motion?'instant':'smooth'})}}
function friendDoor(id){return ['folsom','pride'].includes(id)?`<button class="friend-door" id="openShannonLetter"><span><small>SHANNON MURRAY · SINCE THE 1990s</small><strong>One of my oldest, deepest friends.</strong><em>A note from me to you ↗</em></span><i aria-hidden="true">♡</i></button>`:''}
function placeVisual(id){if(id==='ggp-games'||id==='ggp-mixer')return foundryPlace(id);if(id==='fang-live')return `<figure class="place-portrait"><a data-flickr-embed="true" href="https://www.flickr.com/photos/117199927@N03/48982795113/" title="Boonton, NJ. Maxfield Engine House by Jack Falat, on Flickr"><img src="https://live.staticflickr.com/65535/48982795113_c717e3ec11_b.jpg" width="614" height="1024" alt="The historic Maxfield Engine House facade in Boonton, New Jersey."></a><figcaption><p class="eyebrow">BOONTON, NEW JERSEY</p><h3>Imagine what these walls will hear.</h3><p>The real Maxfield Engine House. An archive view of the building Foster’s family is giving its next chapter.</p><a class="source-link" href="https://www.flickr.com/photos/117199927@N03/48982795113/" target="_blank" rel="noopener">Photograph by Jack Falat / Flickr ↗</a><p class="place-note">Archive photograph; the future performance space is still taking shape.</p></figcaption></figure>`;if(id==='olympics')return `<button class="film-door olympic-door" data-media="la28-world"><img src="https://i.ytimg.com/vi/ebcNlsI5SYA/hqdefault.jpg" alt="LA28’s official introduction to the Games’ venue zones"><span><small>OFFICIAL LA28 FILM</small><strong>Our city. A whole new stage.</strong><em>▶ Explore the venue zones</em></span></button>`;return ''}
function artistDoors(id){if(!['ggp-mixer','fang-live'].includes(id))return '';return `<div class="artist-doors">${(id==='fang-live'?['fang-speare']:['fang-speare','capnsmak']).map(k=>`<button class="artist-door" data-artist="${k}"><small>${esc(ARTISTS[k].realName)}</small><strong>${esc(ARTISTS[k].name)}</strong><span>Enter the artist’s world ↗</span></button>`).join('')}</div>`}
function artistOptions(){return {reducedMotion:motion,onPlay:(label,players)=>{stopOther(players);window.AfterHoursInstrument?.stop();transport(label)},onQuiet:()=>$('#transport').hidden=true,onProfile:artist,onBooth:booth,onEvent:id=>{choose(id);story()},onShare:hash=>shareUrl(urlWith(hash)),onComplete:()=>light('ggp-mixer')}}
function artist(id){const p=ARTISTS[id];if(!p)return;open('artist',p.realName+' / THE ARTIST',`<div id="artistRoot"></div>`);window.AfterHoursArtists.mountProfile($('#artistRoot'),p,artistOptions());}
function booth(){open('booth','FANG SPEARE B2B CAPNSMAK / A LITTLE LISTENING EXPERIMENT','<div id="boothRoot"></div>');window.AfterHoursArtists.mountBooth($('#boothRoot'),ARTISTS,artistOptions());}
function story(){const e=selected,d=DEPTH[e.id];open('story',`${e.stamp} / ${e.city}`,`<h2 id="dialogTitle">${esc(e.name)}</h2><p class="dialog-lead">${esc(e.note)}</p><p class="dialog-sub">${esc(e.crew)} · ${esc(e.venue)}${isPast(e)?' · Past date; the date alone does not confirm attendance.':''}</p>${friendDoor(e.id)}${placeVisual(e.id)}${artistDoors(e.id)}${filmDoor(e.id)}${photoStrip(e.id)}<div id="storyPlayer"></div>${mediaChoices(eventMedia[e.id]||[])}${d?.personalHistory?`<div class="story-personal"><p class="eyebrow">MY THREAD THROUGH THE MUSIC</p>${esc(d.personalHistory)}</div>`:''}<div class="story-grid">${(d?.chapters||[{label:'THE INVITATION',title:e.line,text:e.blurb,url:e.url,linkLabel:'Explore the official event'}]).map(c=>`<article class="story-chapter"><p class="eyebrow">${esc(c.label)}</p><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p>${c.url?`<a class="source-link" href="${esc(c.url)}" target="_blank" rel="noopener">${esc(c.linkLabel||'Go deeper at the source')} ↗</a>`:''}</article>`).join('')}</div>${e.id==='portola'?`<details class="story-chapter"><summary>Our Saturday, without overplanning it</summary><p>3:40–4:30 oskar med k · 7:10–8:10 Robyn · 9:00–10:15 Dog Blood. All on the Pier stage. Soulwax starts at 9:55; catching that opening means leaving Dog Blood early and allowing time to walk.</p><a class="source-link" target="_blank" rel="noopener" href="https://portolamusicfestival.com/set-times/">Check the official set times ↗</a><br><a class="source-link" target="_blank" rel="noopener" href="https://www.jambase.com/festival/portola-2026?utm_source=mcp&utm_medium=chatgpt&utm_campaign=tool-result&utm_content=searchEvents">Explore the full bill on JamBase ↗</a></details>`:''}<div class="dialog-actions"><a href="${esc(e.url)}" target="_blank" rel="noopener">${e.id==='fang-live'?'The story of the firehouse':'Official event & latest details'} ↗</a><button id="storyShare">Share this chapter ↗</button><button id="storyWonder">Find its little wonder ✳</button></div><p class="eyebrow">FOLLOW THE THREAD</p><div class="related">${(d?.related||[]).map(id=>D.events.find(x=>x.id===id)).filter(Boolean).map(x=>`<button data-related="${x.id}">${esc(x.name)} ↗</button>`).join('')}</div>`);bindMedia();bindPhotos(e.id);if($('#openShannonLetter'))$('#openShannonLetter').onclick=()=>{close();person=D.people.find(p=>p.id==='shannon');renderPerson();setHash('#people/shannon');$('#people').scrollIntoView({behavior:motion?'instant':'smooth'})};document.querySelectorAll('[data-artist]').forEach(b=>b.onclick=()=>artist(b.dataset.artist));$('#storyShare').onclick=()=>shareUrl(urlWith('#'+e.id));$('#storyWonder').onclick=wonder;document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>{choose(b.dataset.related);story()})}
function playMedia(id){let m=D.media.find(x=>x.id===id);if(!m)return;currentMedia=m;open('media',m.label,`<h2 id="dialogTitle">${esc(m.artist)}</h2><p class="dialog-lead">${esc(m.title)}</p><div class="provider-door"><a class="primary" href="${esc(m.url)}" target="_blank" rel="noopener">${m.type.startsWith('youtube')?'Watch on YouTube':m.type==='spotify'?'Listen on Spotify':'Listen on SoundCloud'} <span>↗</span></a><button id="loadEmbed">Play here ▶</button></div><div id="playerHost" class="player-poster" style="${m.poster?'background-image:url('+m.poster+')':m.type==='youtube'?'background-image:url(https://i.ytimg.com/vi/'+m.key+'/hqdefault.jpg)':''}"><span>THE SOUND & THE STORY</span></div><p class="player-note"><span>${esc(m.note)}</span><a href="${esc(m.url)}" target="_blank" rel="noopener">Open at the source ↗</a></p><div class="dialog-actions"><button id="backStory">← Back to ${esc(selected.name)}</button><button id="mediaStop">Stop playback</button></div>`);if(m.preview){$('#playerHost').classList.remove('player-poster');$('#playerHost').innerHTML=`<div class="album-preview"><img src="${esc(m.cover)}" alt="${esc(m.title)} album artwork"><div><p class="eyebrow">ALBUM PREVIEW · SPOTIFY</p><audio controls preload="none" src="${esc(m.preview)}" aria-label="${esc(m.title)} preview"></audio></div></div>`;const a=$('#playerHost audio');a.onplay=()=>{stopOther(a);window.AfterHoursInstrument?.stop();transport(m.title+' · preview')};a.onpause=()=>$('#transport').hidden=true;a.onended=a.onpause;}let iframe=document.createElement('iframe');iframe.className='media-frame'+(m.type==='spotify'?' spotify':'');iframe.title=m.artist+' — '+m.title;iframe.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.src=m.type==='youtube-playlist'?`https://www.youtube-nocookie.com/embed/videoseries?list=${m.key}&autoplay=1`:m.type==='spotify'?`https://open.spotify.com/embed/${m.entity||'playlist'}/${m.key}?utm_source=generator&theme=0`:m.type==='soundcloud'?`https://w.soundcloud.com/player/?url=${encodeURIComponent(m.key)}&auto_play=true&show_comments=false&visual=true`:`https://www.youtube-nocookie.com/embed/${m.key}?autoplay=1&playsinline=1&rel=0`;$('#loadEmbed').onclick=()=>{stopAll();$('#playerHost').replaceChildren(iframe);$('#playerHost').classList.remove('player-poster');$('#loadEmbed').textContent='Player opened below';transport('Player open · '+m.artist);};$('#backStory').onclick=story;$('#mediaStop').onclick=()=>{stopAll();$('#playerHost').innerHTML='<p>Playback stopped. Open the source link below to keep listening.</p>'}}
function memory(){open('memory','FROM MY EDC ARCHIVE',`<h2 id="dialogTitle">A little of being there.</h2><video id="memoryVideo" class="memory-film" controls playsinline preload="auto" poster="assets/edc-film-poster.webp"><source src="assets/edc-memory.mp4" type="video/mp4"><track kind="captions" src="assets/edc-captions.vtt" srclang="en" label="Sound descriptions"></video><p class="player-note"><span>My own 20-second EDC memory. Music, lights, a crowd in motion.</span><a href="assets/edc-memory.mp4" target="_blank">Open the film ↗</a></p><div class="dialog-actions"><button id="memorySet">Stay for Alison’s full EDC set ↗</button><button id="memoryPeople">The people behind the feeling ↘</button><button id="memoryPhotos">Open my photo box ↗</button></div>`);const v=$('#memoryVideo');v.volume=.55;v.play().then(()=>transport('My EDC memory')).catch(()=>notify('Tap play on the film to bring in the sound.'));v.onended=()=>{$('#transport').hidden=true};v.onplay=()=>transport('My EDC memory');v.onpause=()=>{$('#transport').hidden=true};$('#memoryPhotos').onclick=photoBox;$('#memorySet').onclick=()=>playMedia('alison');$('#memoryPeople').onclick=()=>{close();$('#people').scrollIntoView({behavior:motion?'instant':'smooth'})}}
function light(id){if(!seen.includes(id)){seen.push(id);try{localStorage.setItem('afterhours-lights',JSON.stringify(seen))}catch{}renderLights();renderThreads();}}
function renderLights(){$('#sparkCount').textContent=seen.length?`${seen.length} little ${seen.length===1?'wonder':'wonders'} found. Your constellation is growing.`:'Every little wonder you find leaves a light.';$('#constellation').innerHTML=seen.map((id,i)=>`<i style="left:${62+(i*17)%35}%;top:${(i*29)%90}%" title="${esc(id)}"></i>`).join('')}
function renderThreads(){const pairs=[{ids:['folsom','pride'],title:'Shannon · San Francisco to the desert',go:'pride'},{ids:['portola','niteharts'],title:'Brennan · across the crowd',go:'portola'},{ids:['zeds','olympics'],title:'Foster · a rain check, a birthday',go:'olympics'},{ids:['ggp-mixer','fang-live'],title:'Foster · the booth, the firehouse',go:'fang-live'},{ids:['ggp-games','ggp-mixer'],title:'GGP · the table, the dance floor',go:'ggp-mixer'},{ids:['sincity','olympics'],title:'Different courts · the same joy',go:'sincity'},{ids:['edc','pokemon'],title:'Alison · the thread keeps glowing',go:'pokemon'}];$('#threadsFound').innerHTML=pairs.filter(p=>p.ids.every(id=>seen.includes(id))).map(p=>`<button data-thread="${p.go}"><small>TWO LIGHTS. ONE THREAD.</small>${p.title} ↗</button>`).join('');$('#threadsFound').querySelectorAll('button').forEach(b=>b.onclick=()=>{choose(b.dataset.thread);story()})}
function wonder(){if(selected.id==='ggp-mixer'){booth();return}open('wonder',selected.name+' / A LITTLE WONDER',`<h2 id="dialogTitle">${esc(window.AfterHoursWonders.label(selected.id))}</h2><div id="wonderRoot"></div><div class="dialog-actions"><button id="wonderStory">Dig into the sound & story ↗</button><button id="wonderJam">Carry the feeling into your own loop ↗</button></div>`);window.AfterHoursWonders.mount($('#wonderRoot'),selected,{reducedMotion:motion,onComplete:()=>light(selected.id),onSound:()=>{window.AfterHoursInstrument?.stop();document.querySelectorAll('video').forEach(v=>v.pause());document.querySelectorAll('iframe.media-frame').forEach(f=>f.remove());transport('Original sound · '+selected.name)}});$('#wonderStory').onclick=story;$('#wonderJam').onclick=()=>{jamState=patternFromWonder(selected.id,window.AfterHoursWonders.snapshot());play()}}
function patternFromWonder(id,s={}){const group=['zeds','niteharts','pokemon','olympics'].includes(id)?'dnb174':['portola','folsom','foundry','pride','summit','countdown'].includes(id)?'house128':'warm112';const seed=D.events.findIndex(e=>e.id===id)+(s?.mode||0)+(s?.chosen?.length||0);return {version:1,preset:group,bpm:{warm112:112,house128:128,dnb174:174}[group],volume:.12,tracks:Array.from({length:4},(_,t)=>Array.from({length:16},(_,i)=>+(t===0?(group==='dnb174'?[0,6,8,14].includes(i):i%4===0):t===1?i%8===4:t===2?(i+seed)%3===0:(i+seed)%8===0)))};}
function play(){open('play','A LITTLE ORIGINAL SOUND / FROM US',`<h2 id="dialogTitle">Your turn to play.</h2><p class="dialog-sub">Tap a few lights. Change the feeling. Pass your loop to someone you love.</p><div id="jam"></div><div class="dialog-actions"><button id="shareLoop">Send this loop ↗</button><button id="resetLoop">Start with a fresh pattern</button></div><p class="dialog-sub">Original synthesized music. Your loop travels in its link; no account or live connection needed.</p>`);window.AfterHoursInstrument.mount($('#jam'),{reducedMotion:motion,onStart:()=>{stopOther();transport('Your original loop')},onChange:s=>{jamState=s;try{localStorage.setItem('afterhours-pattern',JSON.stringify(s))}catch{}}});if(jamState&&!window.AfterHoursInstrument.restore(jamState)){notify('That shared loop could not be read. A fresh pattern is ready.');jamState=null;}$('#jam').addEventListener('click',e=>{if(e.target.closest('.jam-play')?.getAttribute('aria-pressed')==='false')$('#transport').hidden=true});$('#shareLoop').onclick=()=>{const s=window.AfterHoursInstrument.serialize();shareUrl(urlWith('#play?loop='+encodeURIComponent(btoa(JSON.stringify(s))))) };$('#resetLoop').onclick=()=>{jamState=null;window.AfterHoursInstrument.restore({version:1,preset:'warm112',bpm:112,volume:.12,tracks:[[1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0],[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],[1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0],[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]]});notify('A fresh little beginning.')}}
function renderPerson(){const p=person,isLetter=p.portrait==='letter';$('#shannonQuestion').hidden=p.id!=='shannon';$('#shannonQuestion').onclick=()=>{setHash('#about/gordon');gordonLetter()};$('#openShannonRelic').onclick=()=>{setHash('#shannon/2002');shannonRelic()};$('.memory-photo').classList.toggle('is-letter',isLetter);$('#memoryLetter').hidden=!isLetter;$('.memory-photo img').hidden=isLetter;$('.memory-photo figcaption').hidden=isLetter;$('#fullPhoto').hidden=isLetter;$('#openPhotos').hidden=isLetter;$('.signature').textContent=p.id==='shannon'?'LYMI, Gordon':'With love, Gordon';$('#personTabs').innerHTML=D.people.map(p=>`<button data-person="${p.id}" aria-pressed="${p.id===person.id}">${esc(p.name)}</button>`).join('');$('#personKicker').textContent=p.kicker;$('#personTitle').textContent=p.title;$('#personBody').textContent=p.body;$('#personMemory').textContent=p.memory;$('.memory-photo img').src=p.photo||'assets/ultra-miami-1600.webp';$('.memory-photo img').alt=p.photoAlt||'A memory from my photo album';$('.memory-photo figcaption').textContent=p.photoCaption||'FROM MY PHOTO ALBUM';$('#fullPhoto').onclick=()=>photoBox(p.album||'all');$('#openPhotos').onclick=()=>photoBox(p.album||'all');document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{person=D.people.find(p=>p.id===b.dataset.person);renderPerson();setHash('#people/'+person.id)});$('#personNext').onclick=()=>{choose(p.next);$('#nights').scrollIntoView({behavior:motion?'instant':'smooth'})};$('#personMusic').onclick=()=>{choose(p.next);if(p.id==='foster')artist('fang-speare');else if(p.id==='sam')artist('capnsmak');else if(p.id==='shannon'){choose('pride');wonder()}else playMedia(p.media)};$('#personMusic').textContent=p.id==='foster'?'Enter Fang Speare’s world ↗':p.id==='sam'?'Enter Capnsmak’s world ↗':p.id==='shannon'?'Light our colors ↗':'A little of the feeling ▶'}
function urlWith(hash){return location.origin+location.pathname+hash}
async function shareUrl(url){open('share','PASS THE FEELING ON',`<h2 id="dialogTitle">A little invitation.</h2><p class="dialog-lead">Send a night, a memory, or a little music to someone you love.</p><label for="shareText">Your shareable link</label><input id="shareText" class="share-field" readonly value="${esc(url)}"><div class="dialog-actions"><button id="copyShare">Copy link ↗</button></div><p id="shareStatus" role="status" class="dialog-sub">This link opens the same chapter or musical pattern.</p>`);$('#shareText').onclick=()=>$('#shareText').select();$('#copyShare').onclick=async()=>{try{await navigator.clipboard.writeText(url);$('#shareStatus').textContent='Link copied. Ready to send with a little love.'}catch{$('#shareText').select();$('#shareStatus').textContent='Select and copy the link above.'}};}

function credits(){open('credits','MADE WITH LOVE',`<h2 id="dialogTitle">A life well danced.</h2><p class="dialog-lead">I made this for the people who turn music into memories with me. The night is a beginning. The friendship is the part I keep.</p><p>My real photographs from EDC, Ultra, HARD Summer, Second Sky, Red Rocks, Shambhala, Countdown, Gryphus, GGP and Sin City, and my EDC and GGP films, live here beside an imagined sunrise created with Higgsfield. The original little instruments and visual worlds are made for play. Artist recordings always come from their own players and sources.</p><p>Memories and upcoming plans are kept distinct. Dates and lineups can change; every chapter has a link to the official event. Your patterns and discovered lights stay in this browser unless you choose to copy a sharing link.</p><p class="dialog-sub">Creative direction: Gordon. Built in collaboration with Codex and Darby. Music discovery with Spotify; event cross-checks with JamBase.</p><a class="source-link" href="https://open.spotify.com/playlist/28hgvKjRRH5cDOHgz2Qn7G?utm_source=openai&utm_medium=chatgpt" target="_blank" rel="noopener">Explore EDM Joyful Adventures With Friends on Spotify ↗</a>`)}
function route(){let h;try{h=decodeURIComponent(location.hash.slice(1));}catch{return;}if(h==='shannon/2002'){shannonRelic();return}if(h==='about/gordon'){gordonLetter();return}if(h.startsWith('artist/')){artist(h.slice(7));return}if(h==='b2b'){booth();return}if(h==='film/ggp'){archiveFilm('ggp');return}if(h==='photos'){photoBox();return}if(h.startsWith('photos/')){photoBox(h.slice(7));return}if(h.startsWith('memory/')){photoView(h.slice(7));return}if(h.startsWith('play')){const q=new URLSearchParams(h.split('?')[1]||'');try{if(q.get('loop'))jamState=JSON.parse(atob(q.get('loop')))}catch{notify('That shared loop could not be read. Here is a fresh one.')}play();return}if(h.startsWith('people/')){person=D.people.find(p=>p.id===h.split('/')[1])||D.people[0];renderPerson();$('#people').scrollIntoView();return}if(D.events.some(e=>e.id===h)){choose(h,false);$('#nights').scrollIntoView()}}
$('#showFilter').onchange=()=>{const list=filtered();if(list.length&&!list.includes(selected))selected=list[0];renderNight()};$('#prevShow').onclick=()=>{const l=filtered();choose(l[(l.indexOf(selected)-1+l.length)%l.length].id)};$('#nextShow').onclick=()=>{const l=filtered();choose(l[(l.indexOf(selected)+1)%l.length].id)};$('#openStory').onclick=story;$('#openWonder').onclick=wonder;$('#shareNight').onclick=()=>shareUrl(urlWith('#'+selected.id));$('#shareHome').onclick=()=>shareUrl(urlWith('#home'));$('#playMemory').onclick=memory;$('#closeDialog').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});$('#dialogStop').onclick=()=>{stopAll();notify('A little quiet.')};$('#stopAll').onclick=()=>{stopAll();notify('A little quiet.')};document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='play'?play():b.dataset.open==='gordon'?(setHash('#about/gordon'),gordonLetter()):credits());$('#fullPhoto').onclick=()=>photoBox(person.album||'all');$('#openPhotos').onclick=()=>photoBox(person.album||'all');
function setMotion(){document.body.classList.toggle('motion-paused',motion);$('#motionToggle').setAttribute('aria-pressed',String(motion));$('#motionToggle').textContent=motion?'Motion paused':'Pause motion';if(motion)$('#dawnFilm').pause()}
$('#motionToggle').onclick=()=>{motion=!motion;setMotion();try{localStorage.setItem('afterhours-motion',motion?'paused':'on')}catch{}};$('#filmToggle').onclick=()=>{const v=$('#dawnFilm');if(v.paused){v.play().then(()=>$('#filmToggle').textContent='Pause the dawn film').catch(()=>notify('The film could not start. The sunrise is still here.'))}else{v.pause();$('#filmToggle').textContent='Play the dawn film'}};$('#dawnFilm').onpause=()=>$('#filmToggle').textContent='Play the dawn film';document.addEventListener('wonder-sound-ended',()=>{$('#transport').hidden=true});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCinema();cinemaPause?.();if(dialog.open&&dialogMode==='wonder')close();else stopAll()}});window.addEventListener('hashchange',()=>{if(dialog.open)close();route()});
const next=D.events.find(e=>!isPast(e)&&e.date);if(next){$('#nextNight').href='#'+next.id;$('#nextNight').innerHTML='NEXT UP / '+esc(next.name)+' <span>↘</span>';$('#nextNight').onclick=()=>{choose(next.id,false);$('#nights').scrollIntoView({behavior:motion?'instant':'smooth'})}}renderNight();renderPerson();renderLights();renderThreads();setMotion();route();
})();
