/* Four small rituals, grounded in the selected night. No messages are sent. */
(()=>{'use strict';
const q=s=>document.querySelector(s),host=q('#bside'),trigger=q('#surprise');
const people={shambhala:['Gordon','Drake','Mel','David Vermillion','Trent','Mason','Myke Bailey','Jacob Ferrufino'],sincity:['Gordon','Joe','Matt Kaplan','Andrew Ketchum','Casey Reed']};
const titles={stevie:'↔ A feeling worth returning to',zeds:'◒ Tune your curiosity',shambhala:'✦ Light up the Farmily',sincity:'● Pass a little joy'};
const storeKey='gordon-bside-notes-v1';let notes={};try{const v=JSON.parse(localStorage.getItem(storeKey)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))notes=v;}catch(e){}
let last='',open=false,phase='before',lights=new Set(),pass=0;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function button(text,fn,cls=''){const n=el('button',cls,text);n.type='button';n.onclick=fn;return n;}
function tone(kind){if(sound)play(kind);}
function endFrame(){host.classList.add('bside-open');trigger.setAttribute('aria-expanded','true');trigger.textContent='Close this B-side ×';open=true;}
function intro(kicker,title,copy){host.replaceChildren(el('p','ritual-kicker',kicker),el('h3','ritual-title',title),el('p','ritual-lede',copy));}
function saveNotes(){try{localStorage.setItem(storeKey,JSON.stringify(notes));return true;}catch(e){return false;}}
function journal(){const id=selected.id,box=el('div','ritual-note'),label=el('label','',phase==='before'?'One feeling I want to make room for':'One moment I want to keep');const input=el('textarea');input.id='bside-note';label.htmlFor=input.id;input.rows=3;input.maxLength=600;input.placeholder=phase==='before'?'A song, a feeling, a little room to breathe…':'What stayed with you?';input.value=notes[id]?.[phase]||'';const status=el('p','ritual-small','Only in this browser. Not sent, synced, or added to shared plans.');input.oninput=()=>{notes[id]||={};notes[id][phase]=input.value;status.textContent=saveNotes()?'Saved in this browser only. Not included when you copy your night.':'This browser could not save it. Copy your note before leaving.';};const actions=el('div','ritual-actions');actions.append(button('Copy this note',async()=>{try{await navigator.clipboard.writeText(input.value);status.textContent='Note copied. You choose whether to share it.';}catch(e){status.textContent='Copy unavailable here. Select the note and copy it manually.';}}),button('Clear this note',()=>{input.value='';if(notes[id])delete notes[id][phase];status.textContent=saveNotes()?'This note cleared from this browser.':'Cleared on screen; browser storage could not be updated.';}));box.append(label,input,actions,status);return box;}
function stevie(){intro('STEVIE / THE LONG THREAD','The feeling you already know.','In December 2021, this music stopped you in your tracks. Your next chapter is a solo journey.');
const face=el('div','memory-record');let then=true;
function flip(){face.replaceChildren(el('span','record-date',then?'18 DECEMBER 2021':'19 DECEMBER 2026'),el('strong','',then?'That rush of wonder.':'Room to feel it again.'),el('p','',then?'During the concert, Gordon described the performance as genius.':'No one else’s pace. No need to capture every moment. Just you, listening.'));face.dataset.side=then?'then':'now';}
flip();host.append(face,button('Turn the record ↔',()=>{then=!then;flip();tone('chord');},'ritual-primary'));
const choices=el('div','ritual-tabs');const before=button('Before the night',()=>{phase='before';stevie();host.querySelector('.ritual-tab[aria-pressed=true]').focus();},'ritual-tab'),after=button('After the night',()=>{phase='after';stevie();host.querySelector('.ritual-tab[aria-pressed=true]').focus();},'ritual-tab');before.setAttribute('aria-pressed',phase==='before');after.setAttribute('aria-pressed',phase==='after');choices.append(before,after);host.append(choices,journal(),el('p','ritual-small','2021 memory checked against Gordon’s concert-day messages. Artwork is an imagined record sleeve, not a photograph of that show.'));endFrame();}
function zeds(){intro('ZEDS DEAD / A SOLO LISTENING GAME','Follow one strange little sound.','Pick a way into the night. This is a listening experiment, not a prediction of the set.');
const visual=el('div','frequency-art');visual.setAttribute('aria-hidden','true');for(let i=0;i<19;i++){const bar=el('i');bar.style.setProperty('--height',(20+((i*37)%83))+'%');bar.style.setProperty('--i',i);visual.append(bar);}host.append(visual);
const result=el('p','ritual-result','Choose a doorway. You can change your mind.');result.setAttribute('role','status');const list=el('div','ritual-tabs');const options=[['Texture','Listen for a grain, a shimmer, or a sound you cannot quite name. How does it change?','bell'],['Space','Notice the quiet around a sound. What changes when the music leaves a little room?','chord'],['Movement','Follow one low sound with your attention. Notice when your body wants to move.','bass']];options.forEach(([label,prompt,sfx],i)=>{const b=button(label,()=>{for(const x of list.children)x.setAttribute('aria-pressed',x===b);result.textContent=prompt;visual.dataset.door=String(i);visual.classList.remove('frequency-play');void visual.offsetWidth;visual.classList.add('frequency-play');tone(sfx);},'ritual-tab');b.setAttribute('aria-pressed','false');list.append(b);});host.append(list,result,el('p','ritual-small','The graphic and optional tones are original illustrations of listening—not Zeds Dead audio. Sound follows the switch at the top.'));endFrame();}
function shambhala(){intro('SHAMBHALA / EIGHT OF US','Everyone brings a little light.','Tap each lantern to kindle the whole crew. This is a playful ritual, not an RSVP or task assignment.');const string=el('div','lantern-string'),status=el('p','ritual-result');status.setAttribute('role','status');const prompts=['Make a little room for wonder.','Follow a sound you did not plan for.','Offer someone a quiet pause.','Find each other after an adventure.','Bring back one unexpected discovery.','Celebrate the little acts of care.','Leave room for a wonderfully silly moment.','Let the forest surprise you.'];
people.shambhala.forEach((name,i)=>{const b=button(name,()=>{lights.has(i)?lights.delete(i):lights.add(i);b.setAttribute('aria-pressed',lights.has(i));status.textContent=lights.size===8?'Eight lights. Our whole Farmily. Pick a place to find each other, then leave room for discovery.':lights.size+' of 8 lights · '+prompts[i];string.classList.toggle('all-lit',lights.size===8);tone(lights.size===8?'chord':'bell');},'lantern');b.setAttribute('aria-pressed',lights.has(i));b.style.setProperty('--lantern-tone',['#ed8cac','#ffd17f','#a4dce3','#c4b1eb','#f28e71','#b9dd94','#ffd9b0','#97c8c1'][i]);string.append(b);});status.textContent=lights.size===8?'Eight lights. Our whole Farmily.':lights.size+' of 8 lights · Each one belongs here.';string.classList.toggle('all-lit',lights.size===8);host.append(string,status,button('Start the lights again',()=>{lights.clear();shambhala();host.querySelector('.ritual-reset').focus();},'ritual-reset'));endFrame();}
function sincity(){intro('SIN CITY / IN EACH OTHER’S CORNER','Good catch. Your turn.','A little warm-up for a weekend together. These are playful prompts; nobody is being assigned a team role.');const court=el('div','pass-court');court.setAttribute('aria-label','Pass the ball through the five-person crew');people.sincity.forEach((name,i)=>{const n=el('span','pass-person',name);n.classList.toggle('has-ball',i===pass%5);if(i===pass%5)n.setAttribute('aria-current','true');court.append(n);});const prompts=['Name one thing you are looking forward to.','Give someone a specific, well-earned cheer.','Remember one ridiculous shared moment.','Celebrate a great play—whoever made it.','Make a little time together between the games.'];const result=el('p','ritual-result',people.sincity[pass%5]+' has the imaginary ball. '+prompts[pass%5]);result.setAttribute('role','status');host.append(court,result,button('Pass the ball →',()=>{pass++;sincity();host.querySelector('.ritual-primary').focus();tone('kick');},'ritual-primary'),el('p','ritual-small','Gordon, Joe, Matt Kaplan, Andrew Ketchum and Casey Reed are going. Playing and cheering arrangements remain separate.'));endFrame();}
const builders={stevie,zeds,shambhala,sincity};const original=trigger.onclick;
trigger.onclick=()=>{if(!builders[selected.id]){original();return;}if(open){close();return;}builders[selected.id]();};
function close(){open=false;host.classList.remove('bside-open');host.replaceChildren(el('span','eyebrow',titles[selected.id]?'THERE’S SOMETHING PERSONAL IN THIS SLEEVE.':'THERE’S A LITTLE MORE IN EVERY SLEEVE.'));trigger.textContent=titles[selected.id]||'✳ Open the hidden B-side';trigger.setAttribute('aria-expanded','false');}
trigger.setAttribute('aria-controls','bside');const previous=connected;connected=function(){previous();if(last!==selected.id){last=selected.id;close();}};last=selected.id;close();
})();
