/* Original mini-instrument. Artist recordings are separate, opt-in official embeds. */
(()=>{'use strict';
const q=s=>document.querySelector(s), qa=s=>Array.from(document.querySelectorAll(s));
const oldMix=q('#night-instrument');
oldMix.innerHTML=`<div class="duet-intro"><p class="eyebrow">04 / PASS THE PHONE. MAKE A LITTLE MAGIC.</p><h2>My rhythm.<br>Your spark.<br><em>Our sound.</em></h2><p>One of us chooses the heartbeat. The other brings the surprise. Hear what happens together.</p></div><div class="duet-machine"><div class="duet-window playfield" aria-hidden="true"><div class="duet-disc disc-a"></div><div class="duet-disc disc-b"></div><div class="duet-trail"></div><span id="soundword">TWO CHOICES. ONE LITTLE UNIVERSE.</span></div><div class="duet-controls"><fieldset><legend>01 · Choose a heartbeat</legend><button data-heart="steady" aria-pressed="true">A steady hand</button><button data-heart="skip" aria-pressed="false">A little mischief</button></fieldset><fieldset><legend>02 · Pass it on. Add a spark.</legend><button data-spark="glow" aria-pressed="true">Make it glow</button><button data-spark="lift" aria-pressed="false">Lift us up</button><button data-spark="twist" aria-pressed="false">Plot twist</button></fieldset></div><div class="instrument-strips"><label>🥁 Rhythm <input id="rhythmLevel" type="range" min="0" max="1" value=".8" step=".05"></label><label>🌊 Bass <input id="bassLevel" type="range" min="0" max="1" value=".65" step=".05"></label><label>☀ Warmth <input id="warmthLevel" type="range" min="0" max="1" value=".55" step=".05"></label><label>✦ Sparkle <input id="sparkleLevel" type="range" min="0" max="1" value=".5" step=".05"></label></div><div class="live-keys" role="group" aria-label="Play the melody"><button data-live="0">C<span>A little hello</span></button><button data-live="1">D<span>A new direction</span></button><button data-live="2">E<span>Something warm</span></button><button data-live="3">G<span>Up we go</span></button><button data-live="4">A<span>Stay a while</span></button></div><label class="tempo-control">Pace <input id="jamTempo" type="range" min="85" max="140" value="116" step="1"><output id="tempoLabel">116 BPM</output></label><div class="duet-steps" aria-hidden="true">${Array.from({length:16},(_,i)=>`<i data-step="${i}"></i>`).join('')}</div><div class="duet-transport"><button id="duetPlay" aria-pressed="false">▶ Hear us together</button><button id="duetSurprise">✦ A little unexpected joy</button><label>Volume <input id="volume" type="range" min="0" max=".3" step=".01" value=".08"></label></div><p id="duetCaption" role="status">A steady hand + a warm glow. Ready when you are.</p><p class="small">Original synthesized drums, bass, warm chords and a bell melody. Tap the keys to play; the sliders change your mix. No samples from the artists. One phone, two people, no wrong notes.</p></div>`;
const listen=document.createElement('section');listen.id='listening-room';listen.className='listen-room';
listen.innerHTML=`<div class="listen-heading"><p class="eyebrow">BEFORE THE NIGHT / FOLLOW YOUR EARS</p><h2>Find the sound<br>that <em>finds you.</em></h2><p id="listenIntro"></p></div><div id="listenChoices" class="listen-choices"></div><div id="listenStage" class="listen-stage" hidden><div class="listen-stage-top"><b id="listenTitle"></b><button id="closeListening">■ Close player</button></div><div id="listenFrame"></div><p id="listenCue"></p><a id="listenSource" target="_blank" rel="noopener">Open the official source ↗</a><p class="small">Playback is provided by the artist’s platform and may depend on your browser or region. The source link remains available.</p></div>`;
q('#shared-memory').before(listen);
const tracks={
 dogblood:{name:'Dog Blood',title:'Turn Off the Lights',tag:'THE COLLABORATION',description:'Skrillex + Boys Noize. A duo to explore before your shared Portola chapter with Brennan.',cue:'Try this together: each choose one texture you hear, then swap. A listening invitation, not a claim about the upcoming set.',source:'https://soundcloud.com/dogblood/dog-blood-turn-off-the-lights',embed:'https://w.soundcloud.com/player/?url='+encodeURIComponent('https://soundcloud.com/dogblood/dog-blood-turn-off-the-lights')+'&auto_play=false&show_comments=false&show_reposts=false&visual=true',color:'#f85c43'},
 robyn:{name:'Robyn',title:'Dancing on My Own',tag:'THE COLLECTIVE FEELING',description:'An official SoundCloud preview to revisit before Portola. What changes when a song becomes something people share?',cue:'SoundCloud provides a preview here. A familiar song can hold different stories for each of you. Share yours if you want. This is a catalog doorway, not a promised setlist.',source:'https://soundcloud.com/robyn/dancing-on-my-own',embed:'https://w.soundcloud.com/player/?url='+encodeURIComponent('https://soundcloud.com/robyn/dancing-on-my-own')+'&auto_play=false&show_comments=false&show_reposts=false&visual=true',color:'#e4b8ee'},
 zeds:{name:'Zeds Dead',title:'Channel Flipping 2: Only You',tag:'THE STRANGE LITTLE DETOUR',description:'An audiovisual doorway selected from Zeds Dead’s own official links. See what catches your attention.',cue:'Before Grand Park, take a detour through their audiovisual world. Compare one image or sound that stayed with you. No future live sequence is promised.',source:'https://linktr.ee/zedsdead',embed:'https://www.youtube-nocookie.com/embed/gRmJyR3ff7k?playsinline=1&rel=0',color:'#a6d8d2'}
};
let nextBeat=0,visualTimers=[],instruments;
let heartbeat='steady',spark='glow',playing=false,timer=0,step=0,serial=0,previous='',surpriseBars=0;
const kick={steady:[0,4,8,12],skip:[0,3,8,10,14]}, melody={glow:[261.63,329.63,392,329.63],lift:[261.63,392,523.25,659.25],twist:[293.66,440,349.23,523.25]};
const heartNames={steady:'A steady hand',skip:'A little mischief'},sparkNames={glow:'a warm glow',lift:'a little lift',twist:'a plot twist'};
function caption(extra=''){q('#duetCaption').textContent=heartNames[heartbeat]+' + '+sparkNames[spark]+'. '+(extra||(playing?'You are making this together.':'Ready when you are.'));}
function engine(){if(!instruments||instruments.context!==ctx)instruments=createAfterHoursInstruments(ctx);instruments.volume(Number(q('#volume').value));return instruments;}
function tick(){if(!playing||document.hidden||!ctx||ctx.state!=='running')return;const music=engine();while(nextBeat<ctx.currentTime+.09){const i=step%16,t=nextBeat,root=[130.81,110,174.61,196][Math.floor(step/16)%4];const level=id=>Number(q(id).value);if(kick[heartbeat].includes(i))music.drum('kick',t,level('#rhythmLevel'));if(i===4||i===12)music.drum('snare',t,level('#rhythmLevel')*.7);if(i%2)music.drum('hat',t,level('#rhythmLevel')*.35);if(i%4===0||i===11)music.bass(root/2*(i===11?2:1),t,level('#bassLevel'));if(i===0||i===8)music.chord(root,t,level('#warmthLevel'));if(i%4===2)music.bell(melody[spark][Math.floor(i/4)],t,level('#sparkleLevel')*.5);if(surpriseBars&&i%2===0)music.bell(melody[spark][Math.floor(i/4)]*2,t,.35);const delay=Math.max(0,(t-ctx.currentTime)*1000);visualTimers.push(setTimeout(()=>{qa('.duet-steps i').forEach((n,j)=>n.classList.toggle('lit',i===j));q('.duet-window').classList.toggle('onbeat',i%4===0);q('.duet-machine').style.setProperty('--beat',String(i));if(i===0)q('#soundword').textContent=['FIND THE RHYTHM.','MAKE ROOM FOR EACH OTHER.','A LITTLE WARMTH GOES A LONG WAY.','THIS ONE IS OURS.'][Math.floor(step/16)%4];},delay));if(visualTimers.length>48)visualTimers.splice(0,24);step++;nextBeat+=60/Number(q('#jamTempo').value)/4;if(i===15&&surpriseBars){surpriseBars--;if(!surpriseBars){oldMix.classList.remove('duet-surprise');caption('The surprise has passed. The groove is still yours.');}}}timer=setTimeout(tick,25);}
function stop(suspend=false){serial++;playing=false;clearTimeout(timer);visualTimers.forEach(clearTimeout);visualTimers=[];if(instruments)instruments.stop();timer=0;q('#duetPlay').textContent='▶ Hear us together';q('#duetPlay').setAttribute('aria-pressed','false');oldMix.classList.remove('duet-playing','duet-surprise');qa('.duet-steps i').forEach(n=>n.classList.remove('lit'));q('.duet-window').classList.remove('onbeat');surpriseBars=0;if(suspend&&ctx)ctx.suspend();caption();}
function closePlayer(){const had=q('#listenFrame').childElementCount>0;q('#listenFrame').replaceChildren();if(had){sound=false;soundUI();}q('#listenStage').hidden=true;qa('[data-track]').forEach(b=>b.setAttribute('aria-expanded','false'));}
q('#duetPlay').onclick=async()=>{if(playing){stop(true);sound=false;soundUI();return;}closePlayer();q('#film').pause();const run=++serial;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();if(run!==serial||document.hidden)return;sound=true;soundUI();playing=true;step=0;nextBeat=ctx.currentTime+.035;oldMix.classList.add('duet-playing');q('#duetPlay').textContent='■ Pause our sound';q('#duetPlay').setAttribute('aria-pressed','true');caption();tick();}catch(e){stop();q('#duetCaption').textContent='Audio could not start here. You can still choose and explore silently.';}};
qa('[data-heart]').forEach(b=>b.onclick=()=>{heartbeat=b.dataset.heart;qa('[data-heart]').forEach(x=>x.setAttribute('aria-pressed',x===b));q('.duet-machine').dataset.heart=heartbeat;caption();});
qa('[data-spark]').forEach(b=>b.onclick=()=>{spark=b.dataset.spark;qa('[data-spark]').forEach(x=>x.setAttribute('aria-pressed',x===b));q('.duet-machine').dataset.spark=spark;caption();});
q('#duetSurprise').onclick=()=>{if(playing){surpriseBars=2;oldMix.classList.add('duet-surprise');caption('A higher melody joins for two loops.');}else{spark=({glow:'lift',lift:'twist',twist:'glow'})[spark];qa('[data-spark]').find(b=>b.dataset.spark===spark).click();caption('A new combination is ready. Press play when you want to hear it.');}};

q('#volume').addEventListener('input',()=>{if(instruments)instruments.volume(Number(q('#volume').value));});
q('#jamTempo').oninput=()=>{q('#tempoLabel').textContent=q('#jamTempo').value+' BPM';};
qa('.instrument-strips input').forEach(x=>x.oninput=()=>{q('.duet-machine').style.setProperty('--'+x.id,x.value);q('#duetCaption').textContent='Your mix: rhythm '+Math.round(Number(q('#rhythmLevel').value)*100)+'%, bass '+Math.round(Number(q('#bassLevel').value)*100)+'%, warmth '+Math.round(Number(q('#warmthLevel').value)*100)+'%, sparkle '+Math.round(Number(q('#sparkleLevel').value)*100)+'%.';});
qa('[data-live]').forEach(b=>b.onclick=async()=>{closePlayer();q('#film').pause();const run=serial;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();if(run!==serial||document.hidden)return;sound=true;soundUI();engine().bell([523.25,587.33,659.25,783.99,880][Number(b.dataset.live)],ctx.currentTime,.7);q('#soundword').textContent=b.textContent.toUpperCase();q('.duet-machine').dataset.lastNote=b.dataset.live;}catch(e){q('#duetCaption').textContent='Sound is unavailable. You can still explore the visual mix.';}});
q('#sound').addEventListener('click',()=>{if(!sound){stop(true);closePlayer();q('#film').pause();}});
q('#filmToggle').addEventListener('click',()=>{stop(true);closePlayer();sound=false;soundUI();});
q('#closeListening').onclick=closePlayer;
q('#film').addEventListener('play',()=>{stop(true);closePlayer();sound=true;soundUI();q('#sound').textContent='■ Stop all sound';});
q('#film').addEventListener('pause',()=>{if(!playing&&!q('#listenFrame').childElementCount){sound=false;soundUI();}});

document.addEventListener('visibilitychange',()=>{if(document.hidden){stop(true);closePlayer();}});
window.addEventListener('pagehide',()=>{stop(true);closePlayer();});
function openTrack(key,button){stop(true);q('#film').pause();sound=false;soundUI();closePlayer();const t=tracks[key],frame=document.createElement('iframe');frame.src=t.embed;frame.title=t.name+' · '+t.title;frame.allow='autoplay; encrypted-media; fullscreen; picture-in-picture';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;q('#listenFrame').append(frame);q('#listenTitle').textContent=t.name+' / '+t.title;q('#listenCue').textContent=t.cue;q('#listenSource').href=t.source;q('#listenStage').hidden=false;button.setAttribute('aria-expanded','true');q('#sound').textContent='■ Stop all sound';q('#sound').setAttribute('aria-pressed','true');sound=true;q('#listenStage').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}
function update(){if(previous===selected.id)return;previous=selected.id;stop(true);closePlayer();q('#film').pause();q('#film').hidden=true;q('#filmToggle').setAttribute('aria-expanded','false');q('#filmToggle').textContent='▶ Let the memory move';sound=false;soundUI();const list=selected.id==='portola'?['dogblood','robyn']:selected.id==='zeds'?['zeds']:[];listen.hidden=!list.length;q('#listenIntro').textContent=selected.id==='portola'?'Two different doors into your Saturday with Brennan. Choose one, listen, and compare what it brings out in each of you.':'A little exploration before October 3 at Grand Park. Start with the artists’ own audiovisual world.';q('#listenChoices').replaceChildren(...list.map((key,i)=>{const t=tracks[key],b=document.createElement('button');b.type='button';b.dataset.track=key;b.style.setProperty('--track-color',t.color);b.setAttribute('aria-expanded','false');b.setAttribute('aria-controls','listenStage');const num=document.createElement('span');num.className='listen-number';num.textContent='0'+(i+1);const tag=document.createElement('small');tag.textContent=t.tag;const h=document.createElement('strong');h.textContent=t.name;const title=document.createElement('span');title.textContent=t.title;const p=document.createElement('p');p.textContent=t.description;const play=document.createElement('span');play.className='listen-play';play.textContent=key==='robyn'?'▶ Open the official preview':'▶ Open the official player';b.append(num,tag,h,title,p,play);b.onclick=()=>openTrack(key,b);return b;}));}
const precedingDraw=draw;draw=function(){precedingDraw();update();};update();
})();
