/* Original Web Audio instruments; no third-party music, samples or trackers. */
function createAfterHoursInstruments(context){
 const master=context.createGain(),compressor=context.createDynamicsCompressor(),voices=new Set();
 master.gain.value=.08;compressor.threshold.value=-18;compressor.knee.value=18;compressor.ratio.value=5;compressor.attack.value=.005;compressor.release.value=.16;master.connect(compressor);compressor.connect(context.destination);
 const noise=context.createBuffer(1,context.sampleRate*.5,context.sampleRate);const data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;
 function track(source,nodes,end){voices.add(source);source.onended=()=>{voices.delete(source);source.disconnect();nodes.forEach(n=>n.disconnect());};source.stop(end);}
 function osc(f,t,dur,amp,type='sine',filterHz=0,slide=0){if(amp<=0)return;const o=context.createOscillator(),g=context.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(slide,t+.12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(amp,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);let nodes=[g];if(filterHz){const filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(filterHz,t);filter.frequency.exponentialRampToValueAtTime(Math.max(160,filterHz*.22),t+dur);filter.Q.value=.8;o.connect(filter);filter.connect(g);nodes.push(filter);}else o.connect(g);g.connect(master);o.start(t);track(o,nodes,t+dur+.03);}
 function hiss(t,dur,amp,hz){if(amp<=0)return;const n=context.createBufferSource(),filter=context.createBiquadFilter(),g=context.createGain();n.buffer=noise;filter.type='highpass';filter.frequency.value=hz;g.gain.setValueAtTime(amp,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);n.connect(filter);filter.connect(g);g.connect(master);n.start(t);track(n,[filter,g],t+dur+.01);}
 return {context,volume(v){master.gain.setTargetAtTime(Math.max(0,Math.min(.3,v)),context.currentTime,.015);},stop(){for(const v of voices){try{v.stop(context.currentTime);}catch(e){}}},drum(kind,t,v){if(kind==='kick'){osc(145,t,.3,v*1.6,'sine',0,44);hiss(t,.018,v*.12,2500);}if(kind==='snare'){hiss(t,.16,v*.6,1200);osc(185,t,.09,v*.25,'triangle');}if(kind==='hat')hiss(t,.055,v*.45,6500);},bass(f,t,v){osc(f,t,.36,v*.65,'triangle',1100);osc(f*2,t,.22,v*.14,'sawtooth',750);},chord(f,t,v){[1,1.25,1.5,1.875].forEach((ratio,i)=>{osc(f*ratio,t+i*.013,.95,v*.12,'triangle',1600);osc(f*ratio*1.003,t+i*.013,1.05,v*.06,'sine');});},bell(f,t,v){osc(f,t,.8,v*.38);osc(f*2.003,t,.19,v*.13);osc(f,t+.19,.65,v*.09);}};
}
