const DATA=JSON.parse(document.querySelector('#events').textContent),$=s=>document.querySelector(s);let selected=DATA.find(e=>e.id===location.hash.slice(1))||DATA.find(e=>e.id==='portola'),feeling='move',saved=[],sound=false,ctx,gain,pulseTimer;
try{saved=JSON.parse(localStorage.getItem('gordon-shows-shared-v2')||'[]');if(!Array.isArray(saved))saved=[]}catch(e){}let lastSurprise=-1;
const themes={portola:['A new-city kind of wonder.','A waterfront Saturday with an anchor set, a discovery, and time to talk after the sound fades.'],stevie:['Let the songs do what songs do.','Pick a song that has lived with you. If we get to hear it, tell me what it brings back.'],zeds:['A little electricity in the city.','Leave room for the unexpected texture, the change in pace, and the moment everyone around us catches it.'],countdown:['Carry something good into the year.','Before midnight, choose one thing to celebrate. After midnight, one possibility to welcome.'],niteharts:['Take turns being the guide.','One must-see each. One discovery neither of us came for. And permission to change the plan.'],latenite:['The encore is a choice.','If we still have energy, another chapter. If we need rest, the good night has already counted.'],comedy:['There is a kind of joy only a laugh can make.','Let’s leave a little room for something delightfully ridiculous.'],pride:['Come as you are. Bring your color.','A gathering can be a chance to receive the warmth we spend so much time giving.'],pokemon:['Let your playful self choose.','Which imaginary companion would come to a concert with you? Tell me why.']};
const feelCopy={move:'Choose one set or moment to be completely inside. No need to chase the whole bill.',connect:'Pick a meeting point before the music, and leave a little unhurried time afterwards.',discover:'Take turns choosing something unfamiliar. A ten-minute experiment can be enough.'};
function save(){try{localStorage.setItem('gordon-shows-shared-v2',JSON.stringify(saved))}catch(e){$('#status').textContent='Storage is unavailable. Copy your choices before leaving.'}}
function filtered(){const f=$('#filter').value;return DATA.filter(e=>f==='all'||((!e.date||e.date>='2026-09-15')&&(f==='upcoming'||(f==='Music'?e.kind==='Music':e.kind!=='Music'))))}
function draw(){const list=filtered();if(!list.includes(selected))selected=list[0];$('#sleeves').replaceChildren(...list.map(e=>{const b=document.createElement('button');b.className='sleeve';b.style.setProperty('--ink',e.color);b.setAttribute('aria-pressed',e===selected);const s=document.createElement('span'),n=document.createElement('b');s.textContent=e.stamp;n.textContent=e.name;b.append(s,n);b.onclick=()=>{selected=e;draw()};return b}));if(!selected)return;for(const [id,k]of Object.entries({stamp:'stamp',name:'name',blurb:'blurb'}))$('#'+id).textContent=selected[k];$('#place').textContent=selected.city;$('#edition').textContent=selected.venue;$('#poster').style.setProperty('--accent',selected.color);const t=themes[selected.id]||['A night worth making room for.','Come for the experience. Keep a little time for the people.'];$('#feeling').textContent=t[0];$('#invitation').textContent=t[1];$('#official').href=selected.url;$('#feelresult').textContent=feelCopy[feeling];$('#pick').setAttribute('aria-pressed',saved.includes(selected.id));$('#pick').textContent=saved.includes(selected.id)?'♥ In my nights':'♡ I’d love this night';$('#bside').textContent='There’s a little more in every sleeve.';history.replaceState(null,'','#'+selected.id);chosen()}
function chosen(){$('#chosen').replaceChildren(...saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean).map(e=>{const b=document.createElement('button');b.textContent=e.stamp+' · '+e.name+' ×';b.setAttribute('aria-label','Remove '+e.name+' from my nights');b.onclick=()=>{saved=saved.filter(x=>x!==e.id);save();draw()};return b}));if(!saved.length)$('#chosen').textContent='No nights chosen yet. Tap a heart on a sleeve.'}
$('#filter').onchange=draw;$('#pick').onclick=()=>{saved=saved.includes(selected.id)?saved.filter(x=>x!==selected.id):[...saved,selected.id];save();draw();if(sound)play('bell')};document.querySelectorAll('[data-feel]').forEach(b=>b.onclick=()=>{feeling=b.dataset.feel;document.querySelectorAll('[data-feel]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#feelresult').textContent=feelCopy[feeling]});
const surprises={portola:['SWEET DETOUR','Humphry Slocombe is on Portola’s food list. Pick a flavor together. The menu is part of the discovery.'],countdown:['A MIDNIGHT POSTCARD','Before the countdown, tell someone one specific good thing they brought into your year.'],stevie:['THE SONG WITH A BACKSTORY','Pick the song you most hope to hear. Before the show, tell me whose face comes to mind when it plays.'],pokemon:['YOUR CONCERT COMPANION','Choose an imaginary creature to be your concert buddy. Which one has the best dance moves?'],pride:['A LITTLE MORE COLOR','Wear one thing that makes you feel unmistakably yourself. Let that be enough.']};
const extras=[['THE TEN-MINUTE TRADE','You choose the next discovery. Then your friend chooses. Neither has to defend their taste.'],['AN ENCORE WITHOUT A STAGE','After the show, finish this sentence together: “The moment I’m taking home is…”'],['A POSTCARD FROM THE FLOOR','Take one photo together if everyone wants one. Then let the next song be just for being there.'],['THE JOY YOU ALREADY MADE','There’s a real moving memory waiting below. Open it when you want a little reminder of why we do this.']];
$('#surprise').onclick=()=>{const options=[surprises[selected.id]||extras[0],...extras];let i;do{i=Math.floor(Math.random()*options.length)}while(i===lastSurprise);lastSurprise=i;const [h,p]=options[i],b=document.createElement('b'),t=document.createElement('p');b.textContent=h;t.textContent=p;$('#bside').replaceChildren(b,t);if(sound)play('chord')};
const routes={anchor:{rows:[['3:40–4:30','oskar med k','Pier Stage'],['7:10–8:10','Robyn','Pier Stage'],['9:00–10:15','Dog Blood','Pier Stage']],text:'Stay for Dog Blood’s ending. Soulwax starts at 9:55, so you miss at least its first 20 minutes plus the walk. Choose afterwards whether a partial set is worth the move.'},soulwax:{rows:[['7:10–8:10','Robyn','Pier Stage'],['9:00–before 9:55','Dog Blood, partial','Leave time to move'],['9:55–10:55','Soulwax','Crane Stage']],text:'To hear Soulwax’s opening, leave Dog Blood before 9:55. That costs more than its last 20 minutes once walking time is included. Agree together before the loudest moment.'},despacio:{rows:[['2:45–9:45','Despacio','Choose a daytime visit'],['3:40–4:30','oskar med k','Pier Stage'],['9:00–10:15','Dog Blood','Pier Stage']],text:'Visit Despacio earlier if you want all of Dog Blood. Its sound-system roots are about vinyl and listening together. Choose a window around your other sets; allow for queues.'}};
function route(k){$('#route').replaceChildren(...routes[k].rows.map(([time,title,stage])=>{const a=document.createElement('article'),t=document.createElement('time'),b=document.createElement('b'),s=document.createElement('small');t.textContent=time;b.textContent=title;s.textContent=stage;a.append(t,b,s);return a}));$('#routeMeaning').textContent=routes[k].text;document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.route===k))}document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));route('anchor');
$('#filmToggle').onclick=()=>{const open=$('#film').hidden;$('#film').hidden=!open;$('#filmToggle').setAttribute('aria-expanded',open);$('#filmToggle').textContent=open?'Close the moving memory':'▶ Let the memory move';if(!open)$('#film').pause();if(ctx)ctx.suspend()};
function soundUI(){$('#sound').setAttribute('aria-pressed',sound);$('#sound').textContent=sound?'♫ Sound on':'♫ Sound off'}
function play(kind){try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();ctx.resume();sound=true;soundUI();const notes=kind==='kick'?[120]:kind==='bass'?[65.41]:kind==='bell'?[523.25,783.99]:[261.63,329.63,392];notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.04;o.type=kind==='bass'?'triangle':'sine';o.frequency.setValueAtTime(f,t);if(kind==='kick')o.frequency.exponentialRampToValueAtTime(38,t+.18);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(Number($('#volume').value)/notes.length,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.65);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.7)});$('.playfield').classList.add('pulse');$('#soundword').textContent={kick:'FEEL THE GROUND',bell:'A LITTLE SPARK',bass:'THE ROOM HAS A HEARTBEAT',chord:'MORE BEAUTIFUL TOGETHER'}[kind];clearTimeout(pulseTimer);pulseTimer=setTimeout(()=>$('.playfield').classList.remove('pulse'),600)}catch(e){$('#status').textContent='Audio unavailable here. Every part also works silently.'}}
$('#sound').onclick=()=>{sound=!sound;soundUI();if(sound)play('bell');else if(ctx)ctx.suspend()};document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>play(b.dataset.note));document.addEventListener('visibilitychange',()=>{if(document.hidden){if(ctx)ctx.suspend();sound=false;soundUI();$('#film').pause()}});
async function copy(text){try{await navigator.clipboard.writeText(text);$('#status').textContent='Copied. Send it when you’re ready.';$('#copyFallback').hidden=true}catch(e){$('#copyFallback').hidden=false;$('#copyFallback').value=text;$('#copyFallback').focus();$('#copyFallback').select();$('#status').textContent='Select and copy this text. Nothing has been sent.'}}
const base=()=>location.href.split('#')[0];$('#copy').onclick=()=>copy('Gordon, I’d love to explore these with you:\n'+saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean).map(e=>e.stamp+' · '+e.name).join('\n')+'\n'+base());$('#copyNight').onclick=()=>copy('Let’s explore '+selected.name+' · '+selected.stamp+'\n'+base()+'#'+selected.id);$('#print').onclick=()=>window.print();window.addEventListener('hashchange',()=>{const e=DATA.find(x=>x.id===location.hash.slice(1));if(e){selected=e;if(e.date&&e.date<'2026-09-15')$('#filter').value='all';draw()}});if(selected.date&&selected.date<'2026-09-15')$('#filter').value='all';draw();
const nightNotes={
comedy:{crew:'Gordon + Joe · September 18',booking:'Two tickets purchased. Joe is joining Gordon, confirmed September 15. This is not an offer of an extra ticket.',title:'A little ridiculous. A lot of us.',steps:['Before: save your tickets. The Elysian is at 1944 Riverside Drive.','The show: 9:30–10:45 p.m. Katie, Erika and Laser’s Back to School party.','After: compare the moment that made each of you laugh hardest.'],context:'The organizers invite old high-school photos with a two-sentence memory, and 90s teen outfits. Participation is optional. Joe is your companion for this night.',evidence:'Timing and dress-up suggestions: organizer email September 11. Purchase and companion checked September 15.',move:'Trade the dancefloor for a laugh. If dressing up sounds fun, make one small 90s outfit choice together.',connect:'Make this a Joe-and-Gordon evening: choose an unhurried hello before the show and a favorite moment afterwards.',discover:'Each bring an old school photo if you want. Swap the stories before deciding whether to share them with the show.',surprise:['CLASS PHOTO, OPTIONAL','The organizers invited an old high-school photo plus a two-sentence memory. You and Joe could each choose one. No homework, no pressure.']},
olympics:{crew:'Gordon + Foster · three booked sessions',booking:'Two seats or guests per session are booked. Digital access instructions will follow nearer the Games. No spare ticket is being offered here.',title:'The friendship has a future date.',steps:['July 15, 2028 · squash · 7:30 p.m. · two Category A seats at Universal City.','July 17 · table tennis · two guests, Category B + Leisure Lounge, LA Convention Center.','July 18 · squash · 7:30 p.m. · two Category A seats. Foster’s birthday.'],context:'The April 5 purchase emails confirm both squash sessions and the table-tennis hospitality booking. The table-tennis receipt lists a broad 8 a.m.–11:15 p.m. window; recheck actual session and entry instructions nearer the Games.',evidence:'Purchase emails reviewed September 15; Foster confirmed as companion by Gordon. Billing and booking identifiers stay in Gordon’s private plan.',move:'Follow a rally together. Pick one detail to watch: footwork, anticipation, or the change of pace.',connect:'Make July 18 a birthday chapter for Foster. Leave space around the squash session to celebrate together.',discover:'Learn one rule of squash or table tennis together before the Games, then see it come alive.',surprise:['JULY 18 IS ALREADY SPECIAL','Your second squash evening lands on Foster’s birthday. A celebration is already waiting in the calendar.']},
sincity:{crew:'Gordon + Joe + Matt Kaplan + Andrew Ketchum + Casey Reed',title:'Good company. Great dodgeball.',booking:'The crew is confirmed by Gordon. January 14–18 is the festival window; 2027 dodgeball match times and individual registrations are not yet verified.',steps:['Before: coordinate travel and confirm who is playing, cheering, or both.','During: find our court, share the cheers, and leave time together between matches.','After: keep one brilliant play and one ridiculous moment.'],context:'Sin City Classic lists January 14–18, 2027. Its dodgeball page includes registration opening October 1, 2026, alongside an older day-by-day schedule. Do not use that old timetable for 2027 matches.',evidence:'Crew: Gordon, September 15. Festival dates: sincityclassic.org, checked September 15.'},
gryphus:{crew:'Gordon · companions still open',title:'This chapter already has a place in your calendar.',booking:'Your calendar block runs April 28–May 3, 2027, ending May 4. This is your trip window, not an independently verified festival timetable.',steps:['Before: use your April 28–May 3 calendar block to plan the trip.','Next: confirm venue, festival timetable, and companions.','Then: give the music and the journey room to breathe.'],context:'Calendar entry: GRYPHUS 2027 Definitely. Starts April 28 and ends May 4 (exclusive). The album now preserves this existing commitment.',evidence:'Gordon’s Google Calendar read September 15.'},
shambhala:{crew:'Gordon + Drake + Mel + David Vermillion + Trent + Mason + Myke Bailey + Jacob Ferrufino',title:'All eight. All in.',booking:'The whole named crew is going, confirmed by Gordon. Travel and camping arrangements are separate decisions.',steps:['Before: plan our travel and camping together.','During: trade discoveries, and choose a place to find each other.','After: leave room for rest and the stories we bring home.'],context:'The upcoming Shambhala crew is confirmed by Gordon. This records attendance plans, not individual payment or ticket details.',evidence:'Gordon confirmed the complete eight-person crew in this conversation, September 15.'},
stevie:{crew:'Gordon · a solo journey',title:'The songs, and you.',booking:'An intentional solo outing, confirmed by Gordon.',steps:['Before: choose a song with a personal story.','During: follow your own pace. Let the music have your full attention.','After: keep one moment, a lyric, or a feeling from the night.'],context:'This is Gordon’s solo journey. No companion is needed or being assigned.',evidence:'Solo attendance confirmed directly by Gordon, September 15.'},
portola:{crew:'Gordon + Brennan · Saturday at Pier 80',title:'Choose the evening together.',steps:['Before: pick a meeting point and one shared must-see.','During: use the timetable below to choose the whole Dog Blood set, Soulwax’s opening, or an earlier Despacio visit.','After: make room for the story behind your favorite moment.'],context:'Brennan is joining Gordon for Portola. The route choices below make the Dog Blood / Soulwax overlap visible. Portola Week parties are separate events.',evidence:'Companion: Gordon’s confirmation relayed by Darby September 15. Timetable: official September 15 review.',move:'Choose the whole Dog Blood set below and let the ending count. Soulwax overlaps; the route shows the cost.',connect:'Agree on the evening with Brennan before splitting for a discovery. A shared ending is a choice, not an obligation.',discover:'Try an earlier Despacio visit, then return to your anchor. Choose that route below to see the tradeoff.'},
zeds:{crew:'Gordon · a solo journey',title:'Your rhythm. Your night.',booking:'An intentional solo outing, confirmed by Gordon.',steps:['Before: save your ticket and choose your own arrival pace.','During: find your favorite listening spot and let one stretch be phone-free.','After: keep one sound or transition that stayed with you.'],context:'This is the Los Angeles Zeds Dead show at Grand Park. It is a different event from the New York Zeds Dead memories with Foster; Gordon confirmed this LA show is a solo journey.',evidence:'Event details inherited from the September 13 edition. Check the official event link for current entry information.',move:'Choose a comfortable spot and let the bass do the organizing. Recheck arrival and entry with the organizer.',connect:'Connection can be with the music, the room, and yourself. Enjoy this solo journey at your own pace.',discover:'Listen for a texture you have not noticed before. Afterwards, keep the sound that surprised you most.'},
};
const eventPrompts={stevie:['Before: choose the song with a personal story.','During: listen for the way a familiar song changes in the room.','After: tell each other why that song mattered.'],niteharts:['Before: agree on one must-see each and a reunion point.','During: trade one unfamiliar set choice each.','After: choose rest or the separately ticketed LateNite on its own merits.'],latenite:['Before: confirm energy and your separate ticket.','During: pick a simple reunion point.','After: choose a safe, unhurried way home.'],pokemon:['Before: choose your imaginary concert companion.','During: enjoy the collision of a familiar world and live music.','After: share the most playful moment.'],foundry:['Before: check the party timing against your return flight.','During: only choose this if the travel buffer still works.','After: leave enough time to collect bags and reach the airport.'],pride:['Before: agree on the part of the weekend you want to share.','During: find a moment to give and receive a welcome.','After: keep one new connection alive.'],summit:['Before: check the official entry and transport details.','During: set a reunion point before exploring.','After: trade the moment the whole room seemed to move together.'],countdown:['Before: choose one thing from this year to celebrate.','During: make the midnight meet-up simple.','After: welcome one possibility together.'],gryphus:['Before: plan around your April 28–May 3 calendar block.','Then: confirm the festival timetable and venue.','Next: choose companions and travel arrangements.'],edc:['Before: decide who is going and plan rest as carefully as the music.','During: leave room for a shared sunrise.','After: let one photo become the memory, not the whole night.'],shambhala:['Before: confirm dates, travel and camping with the organizer.','During: trade one discovery each.','After: leave room to recover before the journey home.'],blizzcon:['Remember: a day in worlds made for play.','Reconnect: follow through on the conversations that mattered.','Keep: the moment you most want to return to.']};
let preferences={};let selectedRoute='anchor';try{preferences=JSON.parse(localStorage.getItem('show-intentions-v1')||'{}');if(!preferences||typeof preferences!=='object'||Array.isArray(preferences))preferences={};selectedRoute=localStorage.getItem('show-portola-route')||'anchor';if(!routes[selectedRoute])selectedRoute='anchor'}catch(e){}function persistChoices(){try{localStorage.setItem('show-intentions-v1',JSON.stringify(preferences));localStorage.setItem('show-portola-route',selectedRoute)}catch(e){}}
function connected(){
 const n=nightNotes[selected.id]||{},musical=selected.kind==='Music';document.body.style.setProperty('--night-accent',selected.color);
 $('#planTitle').textContent=n.title||themes[selected.id]?.[0]||'Make room for this chapter.';
 $('#planEyebrow').textContent='02 / '+selected.name+' · YOUR PLAN';$('#crew').textContent=n.crew||'Choose your companions together. No group attendance is implied.';
 $('#booking').textContent=n.booking||'This collection is an invitation to explore. Confirm tickets and companions with Gordon; saving a night does not reserve admission.';
 const steps=n.steps||eventPrompts[selected.id]||['Check the official details.','Choose one moment to share.','Keep some room for the unexpected.'];
 $('#planSteps').replaceChildren(...steps.map((t,i)=>{const d=document.createElement('article'),s=document.createElement('span'),p=document.createElement('p');s.textContent=String(i+1).padStart(2,'0');p.textContent=t;d.append(s,p);return d}));
 const meaning=n[feeling]||(feeling==='move'?'Choose the part of '+selected.name+' you most want to feel fully. Keep room to rest.':feeling==='connect'?'For '+selected.name+', agree on who you are meeting, where to reconnect, and a little time to talk.':'For '+selected.name+', each choose one unfamiliar detail to explore. You can change your minds.');
 $('#feelresult').textContent=meaning;$('#intentionLabel').textContent={move:'YOUR CHOICE · FEEL THE MOMENT',connect:'YOUR CHOICE · TIME TOGETHER',discover:'YOUR CHOICE · DISCOVERY'}[feeling];$('#planMeaning').textContent=meaning;
 $('#nightContext').textContent=n.context||selected.blurb+' The sequence above is a suggestion for enjoying this event, not an organizer’s schedule.';
 $('#nightEvidence').textContent=n.evidence||'Event listing from the September 13 edition. Recheck the official event link before travel or purchase.';
 $('#portola-room').hidden=selected.id!=='portola';$('#night-instrument').hidden=!musical;$('#shared-memory').hidden=!musical;
 document.querySelectorAll('[data-feel]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.feel===feeling);if(b.dataset.feel==='move')b.textContent=musical?'MOVE ME':'FEEL THE MOMENT'});
 $('#copyNight').textContent='Copy '+selected.name+' + my choice';const shelf=$('#sleeves'),active=shelf.querySelector('[aria-pressed=true]');if(active){const left=active.offsetLeft-shelf.offsetLeft;if(left<shelf.scrollLeft||left+active.offsetWidth>shelf.scrollLeft+shelf.clientWidth)shelf.scrollLeft=Math.max(0,left-16)}
}
const oldDraw=draw;draw=function(){const prior=selected.id;oldDraw();feeling=preferences[selected.id]||'move';connected()};
document.querySelectorAll('[data-feel]').forEach(b=>b.onclick=()=>{feeling=b.dataset.feel;preferences[selected.id]=feeling;persistChoices();connected()});
const oldRoute=route;route=function(k){selectedRoute=k;oldRoute(k);persistChoices()};
$('#surprise').onclick=()=>{const n=nightNotes[selected.id],special=n?.surprise||surprises[selected.id]||['A SMALL DISCOVERY FOR '+selected.name,preferences[selected.id]==='connect'?'Ask your companion which moment they most want to share. Make a little space for it.':'Choose one unexpected detail to notice at '+selected.name+'. Compare your discoveries afterwards.'];const b=document.createElement('b'),p=document.createElement('p');b.textContent=special[0];p.textContent=special[1];$('#bside').replaceChildren(b,p);if(sound)play('chord')};
function nightText(e){const f=preferences[e.id]||'move';return e.stamp+' · '+e.name+'\n'+e.venue+'\nOur intention: '+{move:'feel the moment',connect:'time together',discover:'discovery'}[f]+(e.id==='portola'?'\nPortola route: '+({anchor:'the whole Dog Blood set',soulwax:'Soulwax from the opening',despacio:'a Despacio detour'}[selectedRoute]):'')+'\n'+base()+'#'+e.id;}
$('#copyNight').onclick=()=>copy('Gordon, here is the night I’m thinking about:\n'+nightText(selected));$('#copy').onclick=()=>copy('Gordon, these are my nights. Let’s confirm plans together:\n\n'+saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean).map(nightText).join('\n\n'));
const printPlan=document.createElement('section');printPlan.id='print-plan';printPlan.className='print-only';document.querySelector('main').append(printPlan);window.addEventListener('beforeprint',()=>{printPlan.replaceChildren();const h=document.createElement('h1');h.textContent='Our nights, together';printPlan.append(h);const es=saved.length?saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean):[selected];for(const e of es){const a=document.createElement('article'),t=document.createElement('h2'),p=document.createElement('p');t.textContent=e.name;p.textContent=nightText(e);p.style.whiteSpace='pre-line';a.append(t,p);printPlan.append(a)}});draw();

route(selectedRoute);
