const DATA=JSON.parse(document.querySelector('#events').textContent),$=s=>document.querySelector(s);let selected=DATA.find(e=>e.id===location.hash.slice(1))||DATA.find(e=>e.id==='portola'),feeling='move',saved=[],sound=false,ctx,gain,pulseTimer;
try{saved=JSON.parse(localStorage.getItem('gordon-shows-shared-v2')||'[]');if(!Array.isArray(saved))saved=[]}catch(e){}let lastSurprise=-1;
const themes={portola:['A new-city kind of wonder.','A waterfront Saturday with an anchor set, a discovery, and time to talk after the sound fades.'],stevie:['Let the songs do what songs do.','Pick a song that has lived with you. If we get to hear it, tell me what it brings back.'],zeds:['A little electricity in the city.','Leave room for the unexpected texture, the change in pace, and the moment everyone around us catches it.'],countdown:['Carry something good into the year.','Before midnight, choose one thing to celebrate. After midnight, one possibility to welcome.'],niteharts:['Take turns being the guide.','One must-see each. One discovery neither of us came for. And permission to change the plan.'],latenite:['The encore is a choice.','If we still have energy, another chapter. If we need rest, the good night has already counted.'],comedy:['There is a kind of joy only a laugh can make.','Let’s leave a little room for something delightfully ridiculous.'],pride:['Come as you are. Bring your color.','A gathering can be a chance to receive the warmth we spend so much time giving.'],pokemon:['Let your playful self choose.','Which imaginary companion would come to a concert with you? Tell me why.']};
const feelCopy={move:'Choose one set or moment to be completely inside. No need to chase the whole bill.',connect:'Pick a meeting point before the music, and leave a little unhurried time afterwards.',discover:'Take turns choosing something unfamiliar. A ten-minute experiment can be enough.'};
function save(){try{localStorage.setItem('gordon-shows-shared-v2',JSON.stringify(saved))}catch(e){$('#status').textContent='Storage is unavailable. Copy your choices before leaving.'}}
function filtered(){const f=$('#filter').value;return DATA.filter(e=>f==='all'||((!e.date||e.date>='2026-09-15')&&(f==='upcoming'||(f==='Music'?e.kind==='Music':e.kind!=='Music'))))}
function draw(){const list=filtered();if(!list.includes(selected))selected=list[0];$('#sleeves').replaceChildren(...list.map(e=>{const b=document.createElement('button');b.className='sleeve';b.style.setProperty('--ink',e.color);b.setAttribute('aria-pressed',e===selected);const s=document.createElement('span'),n=document.createElement('b');s.textContent=e.stamp;n.textContent=e.name;b.append(s,n);b.onclick=()=>{selected=e;draw()};return b}));if(!selected)return;for(const [id,k]of Object.entries({stamp:'stamp',name:'name',blurb:'blurb'}))$('#'+id).textContent=selected[k];$('#place').textContent=selected.city;$('#edition').textContent=selected.venue;$('#poster').style.setProperty('--accent',selected.color);const t=themes[selected.id]||['A night worth making room for.','Come for the experience. Keep a little time for the people.'];$('#feeling').textContent=t[0];$('#invitation').textContent=t[1];$('#official').href=selected.url;$('#feelresult').textContent=feelCopy[feeling];$('#pick').setAttribute('aria-pressed',saved.includes(selected.id));$('#pick').textContent=saved.includes(selected.id)?'♥ In my nights':'♡ I’d love this night';$('#bside').textContent='There’s a little more in every sleeve.';history.replaceState(null,'','#'+selected.id);chosen()}
function chosen(){$('#chosen').replaceChildren(...saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean).map(e=>{const b=document.createElement('button');b.textContent=e.stamp+' · '+e.name+' ×';b.setAttribute('aria-label','Remove '+e.name+' from my nights');b.onclick=()=>{saved=saved.filter(x=>x!==e.id);save();draw()};return b}));if(!saved.length)$('#chosen').textContent='No nights chosen yet. Tap a heart on a sleeve.'}
$('#filter').onchange=draw;$('#pick').onclick=()=>{saved=saved.includes(selected.id)?saved.filter(x=>x!==selected.id):[...saved,selected.id];save();draw();if(sound)play('bell')};document.querySelectorAll('[data-feel]').forEach(b=>b.onclick=()=>{feeling=b.dataset.feel;document.querySelectorAll('[data-feel]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#feelresult').textContent=feelCopy[feeling]});
const surprises={portola:['SWEET DETOUR','Humphry Slocombe is on Portola’s food list. Pick a flavor together. The menu is part of the discovery.'],countdown:['A MIDNIGHT POSTCARD','Before the countdown, tell someone one specific good thing they brought into your year.'],stevie:['THE SONG WITH A BACKSTORY','Pick the song you most hope to hear. Before the show, tell me whose face comes to mind when it plays.'],pokemon:['YOUR CONCERT COMPANION','Choose an imaginary creature to be your concert buddy. Which one has the best dance moves?'],pride:['A LITTLE MORE COLOR','Wear one thing that makes you feel unmistakably yourself. Let that be enough.']};
const extras=[['THE TEN-MINUTE TRADE','You choose the next discovery. Then your friend chooses. Neither has to defend their taste.'],['AN ENCORE WITHOUT A STAGE','After the show, finish this sentence together: “The moment I’m taking home is…”'],['A POSTCARD FROM THE FLOOR','Take one photo together if everyone wants one. Then let the next song be just for being there.'],['THE JOY YOU ALREADY MADE','There’s a real moving memory waiting below. Open it when you want a little reminder of why we do this.']];
$('#surprise').onclick=()=>{const options=[surprises[selected.id]||extras[0],...extras];let i;do{i=Math.floor(Math.random()*options.length)}while(i===lastSurprise);lastSurprise=i;const [h,p]=options[i],b=document.createElement('b'),t=document.createElement('p');b.textContent=h;t.textContent=p;$('#bside').replaceChildren(b,t);if(sound)play('chord')};
const routes={anchor:{rows:[['3:40–4:30','oskar med k','Pier Stage'],['7:10–8:10','Robyn','Pier Stage'],['9:00–10:15','Dog Blood','Pier Stage']],text:'Stay for Dog Blood’s ending. Soulwax starts at 9:55, so you miss at least its first 20 minutes plus the walk. Choose afterwards whether a partial set is worth the move.'},soulwax:{rows:[['7:10–8:10','Robyn','Pier Stage'],['9:00–before 9:55','Dog Blood, partial','Leave time to move'],['9:55–10:55','Soulwax','Crane Stage']],text:'To hear Soulwax’s opening, leave Dog Blood before 9:55. That costs more than its last 20 minutes once walking time is included. Agree together before the loudest moment.'},despacio:{rows:[['2:45–9:45','Despacio','Choose a daytime visit'],['3:40–4:30','oskar med k','Pier Stage'],['9:00–10:15','Dog Blood','Pier Stage']],text:'Visit Despacio earlier if you want all of Dog Blood. Its sound-system roots are about vinyl and listening together. Choose a window around your other sets; allow for queues.'}};
function route(k){$('#route').replaceChildren(...routes[k].rows.map(([time,title,stage])=>{const a=document.createElement('article'),t=document.createElement('time'),b=document.createElement('b'),s=document.createElement('small');t.textContent=time;b.textContent=title;s.textContent=stage;a.append(t,b,s);return a}));$('#routeMeaning').textContent=routes[k].text;document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.route===k))}document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));route('anchor');
$('#filmToggle').onclick=()=>{const open=$('#film').hidden;$('#film').hidden=!open;$('#filmToggle').setAttribute('aria-expanded',open);$('#filmToggle').textContent=open?'Close the moving memory':'▶ Let the memory move';if(!open)$('#film').pause();if(ctx)ctx.suspend()};
function soundUI(){$('#sound').setAttribute('aria-pressed',sound);$('#sound').textContent=sound?'♫ Sound on':'♫ Sound off'}
function play(kind){try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();ctx.resume();sound=true;soundUI();const notes=kind==='kick'?[120]:kind==='bass'?[65.41]:kind==='bell'?[523.25,783.99]:[261.63,329.63,392];notes.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.04;o.type=kind==='bass'?'triangle':'sine';o.frequency.setValueAtTime(f,t);if(kind==='kick')o.frequency.exponentialRampToValueAtTime(38,t+.18);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(Number($('#volume').value)/notes.length,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.65);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.7)});$('.playfield').classList.add('pulse');$('#soundword').textContent={kick:'FEEL THE GROUND',bell:'A LITTLE SPARK',bass:'THE ROOM HAS A HEARTBEAT',chord:'MORE BEAUTIFUL TOGETHER'}[kind];clearTimeout(pulseTimer);pulseTimer=setTimeout(()=>$('.playfield').classList.remove('pulse'),600)}catch(e){$('#status').textContent='Audio unavailable here. Every part also works silently.'}}
$('#sound').onclick=()=>{sound=!sound;soundUI();if(sound)play('bell');else if(ctx)ctx.suspend()};document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>play(b.dataset.note));document.addEventListener('visibilitychange',()=>{if(document.hidden){if(ctx)ctx.suspend();sound=false;soundUI();$('#film').pause()}});
async function copy(text){try{await navigator.clipboard.writeText(text);$('#status').textContent='Copied. Send it when you’re ready.';$('#copyFallback').hidden=true}catch(e){$('#copyFallback').hidden=false;$('#copyFallback').value=text;$('#copyFallback').focus();$('#copyFallback').select();$('#status').textContent='Select and copy this text. Nothing has been sent.'}}
const base=()=>location.href.split('#')[0];$('#copy').onclick=()=>copy('Gordon, I’d love to explore these with you:\n'+saved.map(id=>DATA.find(e=>e.id===id)).filter(Boolean).map(e=>e.stamp+' · '+e.name).join('\n')+'\n'+base());$('#copyNight').onclick=()=>copy('Let’s explore '+selected.name+' · '+selected.stamp+'\n'+base()+'#'+selected.id);$('#print').onclick=()=>window.print();window.addEventListener('hashchange',()=>{const e=DATA.find(x=>x.id===location.hash.slice(1));if(e){selected=e;if(e.date&&e.date<'2026-09-15')$('#filter').value='all';draw()}});if(selected.date&&selected.date<'2026-09-15')$('#filter').value='all';draw();
