/* A night stays one experience as it moves from invitation to memory to music. */
(()=>{'use strict';const q=s=>document.querySelector(s);let states={};try{const saved=JSON.parse(localStorage.getItem('shows-thread-v1')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))states=saved;}catch(e){}let loaded='';function persistThread(){try{localStorage.setItem('shows-thread-v1',JSON.stringify(states));}catch(e){}}
const memoryBridge=document.createElement('div');memoryBridge.className='thread-bridge';memoryBridge.innerHTML='<p class="eyebrow">BRING THE FEELING FORWARD</p><p id="memoryToNight"></p><button id="carryConnection">Make time together our intention</button><a href="#night-instrument">Then make our little soundtrack ↓</a>';q('.memorycopy').append(memoryBridge);
const musicBridge=document.createElement('div');musicBridge.className='thread-bridge music-thread';musicBridge.innerHTML='<p class="eyebrow" id="mixForNight"></p><p id="mixSuggestion"></p><button id="applyNightMix">Set up this little groove</button><p class="small">An original creative prompt, not the artist’s sound or the event’s tempo. Sets the controls; sound starts only when you press play.</p>';q('.duet-intro').append(musicBridge);
const keepsake=document.createElement('p');keepsake.id='nightKeepsake';keepsake.className='night-keepsake';keepsake.setAttribute('aria-live','polite');q('#chosen').before(keepsake);
function state(){return states[selected.id]||(states[selected.id]={});}
function solo(){return ['zeds','stevie'].includes(selected.id);}
function connectionLabel(){return solo()?'TIME FOR ME':'TIME TOGETHER';}
function preset(){const slow=['zeds','latenite','stevie','shambhala'].includes(selected.id);return feeling==='connect'?{pace:104,bass:.45,warmth:.8,spark:.5,heart:'steady',color:'glow',words:solo()?'A warm, unhurried groove. Space to hear yourself.':'A warm, unhurried groove. Space to hear each other.'}:feeling==='discover'?{pace:slow?98:123,bass:.55,warmth:.45,spark:.8,heart:'skip',color:'twist',words:'A skipping rhythm and a bright little plot twist.'}:{pace:slow?96:126,bass:.8,warmth:.45,spark:.6,heart:'steady',color:'lift',words:'A firm heartbeat, a little lift, and room to move.'};}
function snapshot(){return {pace:q('#jamTempo').value,rhythm:q('#rhythmLevel').value,bass:q('#bassLevel').value,warmth:q('#warmthLevel').value,sparkle:q('#sparkleLevel').value,heart:q('[data-heart][aria-pressed=true]').textContent.trim(),spark:q('[data-spark][aria-pressed=true]').textContent.trim()};}
function update(){persistThread();const p=preset();q('#memoryToNight').textContent='For '+selected.name+(solo()?': carry the feeling of that memory into a night that is yours. The people in the photograph are part of the memory, not this solo outing.':': take the habit of finding each other into the next chapter. The photograph is a memory, not this event’s guest list.');q('[data-feel=connect]').textContent=connectionLabel();q('#carryConnection').textContent=solo()?'Make time for myself the intention':'Make time together our intention';if(feeling==='connect')q('#intentionLabel').textContent='YOUR CHOICE · '+connectionLabel();q('#mixForNight').textContent=selected.name+' / '+({move:'FEEL THE MOMENT',connect:connectionLabel(),discover:'DISCOVERY'}[feeling]);q('#mixSuggestion').textContent=p.words;q('#applyNightMix').textContent='Try '+p.pace+' BPM · '+(feeling==='connect'?'warmth':feeling==='discover'?'mischief':'lift');const s=state();q('#nightKeepsake').textContent=selected.name+' · '+({move:'feel the moment',connect:solo()?'time for myself':'time together',discover:'discovery'}[feeling])+(s.memory?' · '+s.memory+' memory':'')+(s.mix?' · your '+s.mix.pace+' BPM groove':'')+'. Your copied plan carries these choices with it.';}
q('#carryConnection').onclick=()=>{preferences[selected.id]='connect';feeling='connect';state().memory=q('#shared-memory').dataset.memory==='ultra'?'Ultra':'EDC';persistChoices();connected();q('#carryConnection').textContent=solo()?'♥ Time for myself carried into my plan':'♥ Time together carried into our plan';};
q('#applyNightMix').onclick=()=>{const p=preset();q('[data-heart="'+p.heart+'"]').click();q('[data-spark="'+p.color+'"]').click();for(const [id,value]of Object.entries({jamTempo:p.pace,bassLevel:p.bass,warmthLevel:p.warmth,sparkleLevel:p.spark})){q('#'+id).value=value;q('#'+id).dispatchEvent(new Event('input',{bubbles:true}));}state().mix=snapshot();q('#duetCaption').textContent='Your '+selected.name+' groove is ready. Press play when you want to hear it.';update();};
q('.duet-machine').addEventListener('input',()=>{state().mix=snapshot();update()});q('.duet-machine').addEventListener('click',e=>{if(e.target.closest('[data-heart],[data-spark]')){state().mix=snapshot();update();}});
function restoreMix(){const stored=state().mix;if(!stored)return;const m={...stored};for(const [id,key]of Object.entries({jamTempo:'pace',rhythmLevel:'rhythm',bassLevel:'bass',warmthLevel:'warmth',sparkleLevel:'sparkle'})){const el=q('#'+id),v=Number(m[key]);if(m[key]!==undefined&&Number.isFinite(v))el.value=Math.max(Number(el.min),Math.min(Number(el.max),v));}q('#tempoLabel').textContent=q('#jamTempo').value+' BPM';for(const [selector,key]of [['[data-heart]','heart'],['[data-spark]','spark']]){const b=[...document.querySelectorAll(selector)].find(x=>x.textContent.trim()===m[key]);if(b)b.click();}state().mix=snapshot();}
const oldConnected=connected;connected=function(){oldConnected();if(loaded!==selected.id){q('#carryConnection').textContent='Make time together our intention';loaded=selected.id;restoreMix();}update();};
const originalNightText=nightText;nightText=function(e){const s=states[e.id];return originalNightText(e)+(s?.memory?'\nA memory to carry forward: '+s.memory:'')+(s?.mix?'\nOur original groove: '+s.mix.pace+' BPM · '+s.mix.heart+' + '+s.mix.spark:'');};loaded=selected.id;restoreMix();update();
})();
