(()=>{'use strict';let root=null,ctx=null,nodes=new Set(),timers=[],raf=0,resize=null,active=false,suppress=false,snapshot=()=>null;const data=()=>window.ARTIST_DEPTH||{};const titles={'olympics':'Foster’s drop'};
function stopSound(){suppress=true;for(const n of nodes){try{n.stop()}catch{}}nodes.clear();if(ctx&&ctx.state==='running')ctx.suspend().catch(()=>{});}
function destroy(){active=false;cancelAnimationFrame(raf);timers.forEach(clearTimeout);timers=[];resize?.disconnect();resize=null;stopSound();root=null}
function mount(el,event,opt={}){destroy();root=el;active=true;root.addEventListener('click',()=>suppress=false,true);root.addEventListener('input',()=>suppress=false,true);const id=event.id,def=data()[id]?.wonder||{name:'A little wonder',instruction:'Tap a light.',kind:'constellation'},reduced=opt.reducedMotion;let n=0,p=.1,done=false,chosen=new Set(),mode=0,pose=0;snapshot=()=>({id,mode,chosen:[...chosen],n,p});const colors=['#ffba87','#d8ec82','#95d7ef','#d6b0fa','#f99eca','#faf0c7'];
root.innerHTML=`<p class="dialog-lead" id="wonderInstruction"></p><div class="wonder-stage"><canvas aria-hidden="true"></canvas><div class="wonder-controls"></div></div><div class="wonder-input"></div><div class="wonder-meter" aria-hidden="true"><i></i></div><p class="wonder-result" role="status"></p><p class="dialog-sub" style="text-align:center">Original sights & sounds, made for this little world.</p>`;const $=s=>root?.querySelector(s),canvas=$('canvas'),c=canvas.getContext('2d'),controls=$('.wonder-controls'),input=$('.wonder-input'),result=$('.wonder-result');$('#wonderInstruction').textContent=def.instruction;
function say(s){result.textContent=s}function progress(v){p=Math.max(0,Math.min(1,v));$('.wonder-meter i').style.width=p*100+'%';draw()}
function finish(text){done=true;progress(1);say(text);opt.onComplete?.();pulse()}
async function sound(kind='bell',pitch=220){if(suppress)return;try{opt.onSound?.();if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();await ctx.resume();if(!active||suppress){ctx.suspend();return}const t=ctx.currentTime,master=ctx.createGain(),comp=ctx.createDynamicsCompressor();master.gain.value=.065;comp.threshold.value=-20;comp.ratio.value=12;master.connect(comp);comp.connect(ctx.destination);const tone=(f,delay,dur,type='sine',amp=1,end)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t+delay);if(end)o.frequency.exponentialRampToValueAtTime(end,t+delay+.25);g.gain.setValueAtTime(.0001,t+delay);g.gain.exponentialRampToValueAtTime(amp,t+delay+.012);g.gain.exponentialRampToValueAtTime(.0001,t+delay+dur);o.connect(g);g.connect(master);o.start(t+delay);o.stop(t+delay+dur+.02);nodes.add(o);o.onended=()=>{nodes.delete(o);o.disconnect();g.disconnect()}};
if(kind==='drop'){for(let i=0;i<16;i++){tone(145,i*.22,.28,'sine',1.4,44);if(i%2===0)tone([55,65.4,73.4,49][Math.floor(i/4)],i*.22+.08,.3,'triangle',.7);if(i%4===2)tone(320,i*.22,.08,'triangle',.35)}}else if(kind==='chord'){[1,1.25,1.5,2].forEach((x,i)=>tone(pitch*x,i*.08,1.7,'triangle',.24))}else if(kind==='pulse'){for(let i=0;i<4;i++)tone(pitch,i*.22,.16,'triangle',.45,pitch*.6)}else tone(pitch,0,.7,'sine',.7);
const timer=setTimeout(()=>{master.disconnect();comp.disconnect();if(!nodes.size){ctx.suspend().catch(()=>{});document.dispatchEvent(new CustomEvent('wonder-sound-ended'))}},kind==='drop'?4500:2500);timers.push(timer);
}catch{say('The lights work without sound. Your browser could not start the audio.')}}
function dot(x,y,r,color){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=color;c.fill()}
function stroke(points,color,width=1){c.strokeStyle=color;c.lineWidth=width;c.beginPath();points.forEach((v,i)=>i?c.lineTo(v[0],v[1]):c.moveTo(v[0],v[1]));c.stroke()}
function draw(t=0){if(!root)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const drift=reduced?0:Math.sin(t*.002)*5;
if(id==='portola'){for(let i=0;i<80;i++)dot((i*67)%w,35+(i*53)%(h-70),2,'#82977755');const x=w*(.16+p*.34),x2=w*(.84-p*.34);stroke([[w*.16,h*.5],[x,h*.5],[x2,h*.5],[w*.84,h*.5]],'#d9f99d55',2);for(const [a,col]of[[x,'#edec91'],[x2,'#efabc8']]){dot(a,h*.5,26+drift,col+'22');dot(a,h*.5,8,col)}c.fillStyle='#f3eed7';c.font='11px Switzer';c.textAlign='center';c.fillText('GORDON',x,h*.5+50);c.fillText('BRENNAN',x2,h*.5-45)}
else if(id==='folsom'){for(let j=0;j<5;j++){stroke([[w*(.12+j*.19),h*.1],[w*(.05+j*.22),h*.87]],'#b486b344',2)}for(let j=0;j<4;j++){c.beginPath();c.moveTo(0,h*(.1+j*.18));c.quadraticCurveTo(w*.5,h*(.32+j*.14),w,h*(.1+j*.18));c.strokeStyle='#dda0d750';c.lineWidth=1.4;c.stroke()}for(let j=0;j<3;j++){const x=w*(.23+j*.27),y=h*(j===1?.32:.42);dot(x,y,chosen.has(j)?28:16,colors[j+2]+(chosen.has(j)?'44':'18'));dot(x,y,chosen.has(j)?9:4,colors[j+2]);c.fillStyle='#f1d8ec';c.font='10px Switzer';c.textAlign='center';c.fillText(['THE STREET','THE MUSIC','OUR PEOPLE'][j],x,y+45)}}
else if(id==='foundry'||id==='zeds'){for(let i=0;i<40;i++){let y=id==='foundry'?h*.5+Math.sin(i*.4+(1-p)*i)*((1-p)*60+10):h*.5+Math.sin(i*.25+mode+t*.002)*45;stroke([[w*.1+i*w*.02,y-20-mode*7],[w*.1+i*w*.02,y+20+mode*7]],colors[mode],3)}}
else if(id==='niteharts'){for(let k=0;k<2;k++){let x=w*(k?.67:.33);c.save();c.translate(x,h*.5);c.scale(1+drift*.005,1+drift*.005);c.beginPath();c.moveTo(0,30);c.bezierCurveTo(-65,-20,-28,-70,0,-25);c.bezierCurveTo(28,-70,65,-20,0,30);c.fillStyle=chosen.has(k)?'#facf98':'#bd738966';c.fill();c.restore()}if(done)stroke([[w*.33,h*.5],[w*.67,h*.5]],'#ffdd9a',3)}
else if(id==='latenite'){const gr=c.createLinearGradient(0,0,0,h);gr.addColorStop(0,`hsl(${255+p*50},35%,${8+p*12}%)`);gr.addColorStop(1,`hsl(${300-p*55},45%,${20+p*20}%)`);c.fillStyle=gr;c.fillRect(0,0,w,h);dot(w*.5,h*.45,70,'#f8e6c6');dot(w*.5-30+p*55,h*.45-25,66,`hsl(${255+p*50},35%,${8+p*12}%)`);for(let i=0;i<35;i++)dot((i*73)%w,(i*37)%h,1+p,'#efdbcf88')}
else if(id==='pokemon'){c.save();c.translate(w*.5,h*.48+drift);c.fillStyle=colors[mode];c.beginPath();c.ellipse(0,0,55,60,0,0,Math.PI*2);c.fill();dot(-18,-7,5,'#132118');dot(18,-7,5,'#132118');stroke([[-15,22],[0,28],[15,22]],'#132118',3);stroke([[-35,-40],[-55,-90],[-10,-52]],colors[mode],12);stroke([[35,-40],[55,-90],[10,-52]],colors[mode],12);stroke([[-25,48],[-38,72+drift],[25,48],[38,72-drift]],colors[mode],9);c.restore()}
else if(id==='pride'){[...chosen].forEach((k,i)=>{c.beginPath();c.moveTo(0,65+i*29);c.bezierCurveTo(w*.3,20+i*30+drift,w*.7,140+i*15,w,70+i*29);c.strokeStyle=colors[k];c.lineWidth=20;c.stroke()})}
else if(id==='summit'){for(let i=0;i<4;i++){const top=h*.8-(i+1)*h*.14;stroke([[w*.15+i*w*.08,h*.86],[w*.15+i*w*.08,top],[w*.9,top]],chosen.has(i)?colors[i]:'#81947133',chosen.has(i)?6:2)}if(done)dot(w*.75,h*.23,36+drift,'#e7ff7677')}
else if(id==='stevie'){dot(w*.5,h*.48,108,'#080b08');for(let i=0;i<12;i++){c.strokeStyle='#b9b29740';c.beginPath();c.arc(w*.5,h*.48,35+i*6,0,7);c.stroke()}dot(w*.5,h*.48,36,mode?'#e7c685':'#bd8168');dot(w*.5,h*.48,5,'#101610');c.fillStyle='#eee5cf';c.font='12px Switzer';c.textAlign='center';c.fillText(mode?'DECEMBER 2026':'DECEMBER 2021',w*.5,h*.93)}
else if(id==='gryphus'){for(let i=0;i<55;i++)dot(12+(i*73)%(w-24),14+(i*41)%(h-35),i%8===0?1.7:.8,'#d9eac633');const pts=[[w*.19,h*.37],[w*.50,h*.23],[w*.81,h*.37]];c.beginPath();c.moveTo(w*.04,h*.66);c.bezierCurveTo(w*.26,h*.03,w*.58,h*.09,w*.96,h*.66);c.strokeStyle='#9db78a55';c.lineWidth=1.5;c.stroke();const names=['WALT','CALE','TOGETHER'],dates=['SINCE 1986','SINCE SXSW','THE NEXT SKY'];pts.forEach(([x,y],i)=>{const lit=chosen.has(i);dot(x,y,lit?24:15,lit?colors[i]+'18':'#b5cea210');dot(x,y,lit?11:4,lit?colors[i]:'#8a9f77');if(lit){c.beginPath();c.arc(x,y,19,0,Math.PI*2);c.strokeStyle=colors[i]+'77';c.lineWidth=1;c.stroke()}c.textAlign='center';c.font='10px Switzer';c.fillStyle=lit?'#f4efdc':'#9ba98d';c.fillText(names[i],x,y+43);c.font='8px Switzer';c.fillStyle='#97a688';c.fillText(dates[i],x,y+59)});}
else if(id==='countdown'){const count=done?55:7;for(let i=0;i<count;i++){let x=20+(i*79)%(w-40),y=35+(i*61)%(h-70);dot(x,y,i===mode?5:2,colors[i%6]);}if(n>0&&!done){c.font='80px Clash';c.textAlign='center';c.fillStyle='#eee9d2';c.fillText(String(11-n),w*.5,h*.65)}}
else if(id==='edc'){const gr=c.createLinearGradient(0,0,0,h);gr.addColorStop(0,`hsl(${250-p*15},${25+p*30}%,${10+p*30}%)`);gr.addColorStop(1,`hsl(${280-p*255},75%,${15+p*52}%)`);c.fillStyle=gr;c.fillRect(0,0,w,h);dot(w*.5,h*(1.15-p*.7),55,'#ffdeb0');for(let i=0;i<30;i++){dot(i*w/29,h*.88+(i%3)*8,5,'#0e1716');stroke([[i*w/29,h*.9],[i*w/29,h]],'#0e1716',9)}}
else if(id==='shambhala'){for(let i=0;i<8;i++){let x=w*(.1+(i%4)*.26),y=h*(i<4?.3:.65);c.strokeStyle='#9aa88766';c.strokeRect(x-10,y-15,20,30);dot(x,y,chosen.has(i)?18:3,chosen.has(i)?colors[i%6]+'bb':'#728361');if(chosen.has(i))dot(x,y,35,'#cdef6111')}if(done)stroke([[w*.1,h*.3],[w*.88,h*.3],[w*.88,h*.65],[w*.1,h*.65]],'#d5ec9280',2)}
else if(id==='ggp-games'){c.fillStyle='#664c32';c.beginPath();c.ellipse(w*.5,h*.45,w*.37,h*.31,0,0,7);c.fill();for(let i=0;i<3;i++){c.fillStyle=chosen.has(i)?colors[i]:'#b6996f';c.fillRect(w*(.25+i*.2)-26,h*.27,52,76);c.fillStyle='#283321';c.font='24px Switzer';c.textAlign='center';c.fillText(chosen.has(i)?['✦','♡','∞'][i]:'?',w*(.25+i*.2),h*.27+48)}}
else if(id==='fang-live'){for(let i=0;i<3;i++){c.fillStyle=chosen.has(i)?'#f2bb73':'#543d37';c.beginPath();c.roundRect(w*(.22+i*.22)-22,h*.18,44,h*.47,[22,22,0,0]);c.fill();stroke([[w*(.22+i*.22),h*.18],[w*(.22+i*.22),h*.65]],'#36281f',3);stroke([[w*(.22+i*.22)-22,h*.39],[w*(.22+i*.22)+22,h*.39]],'#36281f',3);}stroke([[w*.1,h*.69],[w*.9,h*.69]],'#bd8065',4);}
else if(id==='sincity'){for(let i=0;i<4;i++)stroke([[w*(.15+i*.233),h*.1],[w*(.15+i*.233),h*.73]],'#f1b78f55',2);stroke([[w*.15,h*.1],[w*.85,h*.1]],'#f1b78f55',2);const lane=(n*2+1)%3;dot(w*(.266+lane*.233),h*.24+drift*2,24,'#fa806a');dot(w*(.266+mode*.233),h*.65,18,done?'#e7ff76':'#a5dce8');if(done)for(let i=0;i<28;i++)dot((i*71)%w,15+(i*31)%(h*.65),3,colors[i%6]);}
else if(id==='olympics'){stroke([[w*.14,h*.13],[w*.86,h*.13],[w*.86,h*.87],[w*.14,h*.87],[w*.14,h*.13]],'#c3ef9388',2);stroke([[w*.14,h*.4],[w*.86,h*.4]],'#c3ef9388',2);dot(w*(.25+(n%3)*.25),h*.53+drift*(done?7:2),12,'#ebff82');if(done){for(let i=0;i<5;i++){c.beginPath();c.arc(w*.5,h*.5,35+i*24+drift,0,7);c.strokeStyle='#b9e97233';c.stroke()}}}
else if(id==='blizzcon'){for(let i=0;i<9;i++){c.save();c.translate(w*.5,h*.5);c.rotate(i*.22+(reduced?0:t*.00005));c.strokeStyle=colors[(i+mode)%6]+'77';c.lineWidth=2;c.strokeRect(-50-i*7*p,-65-i*7*p,100+i*14*p,130+i*14*p);c.restore()}}
else if(id==='comedy'){c.save();c.translate(w*.5,h*.47);c.rotate((pose-1)*.18);c.fillStyle='#eed7ae';c.fillRect(-68,-85,136,175);dot(0,-12,43,colors[pose]);dot(-15,-19,4,'#152419');dot(15,-19,4,'#152419');stroke([[-15,10],[0,pose===1?17:3],[15,10]],'#152419',3);c.fillStyle='#243223';c.fillRect(-43,34,86,45);c.fillStyle='#eee';c.font='10px Switzer';c.textAlign='center';c.fillText(['MOST LIKELY TO DROP','CLASS CLOWN ENERGY','PERFECT ATTENDANCE?'][pose],0,65);c.restore()}}
function pulse(){if(reduced){draw();return}cancelAnimationFrame(raf);const start=performance.now();function step(t){if(!active)return;draw(t);if(t-start<2400)raf=requestAnimationFrame(step)}raf=requestAnimationFrame(step)}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;controls.append(b);return b}
function range(label,value,fn){input.innerHTML='<label style="display:grid;gap:12px;font-size:12px">'+label+'<input style="width:100%;height:44px;accent-color:#e7ff76" type="range" min="0" max="100" value="'+value+'"></label>';input.querySelector('input').oninput=e=>fn(Number(e.target.value))}
if(id==='portola'){button('Find Gordon',()=>{chosen.add(0);progress(chosen.size/2);sound('bell',330);if(chosen.size===2)finish('There you are. HARD Summer, August 6, 2023: Brennan helped me through the crowd for Skrillex + Four Tet.');else say('One light found. Now find Brennan.');pulse()});button('Find Brennan',()=>{chosen.add(1);progress(chosen.size/2);sound('bell',440);if(chosen.size===2)finish('There you are. HARD Summer, August 6, 2023: Brennan helped me through the crowd for Skrillex + Four Tet.');else say('One light found. Now find Gordon.');pulse()});controls.style.alignSelf='end';controls.style.paddingBottom='16px'}
else if(id==='folsom'){['The street','The music','Our people'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);b.setAttribute('aria-pressed','true');progress(chosen.size/3);sound('chord',[164.81,196,220][i]);say(['Folsom Sunday. San Francisco, with room to be yourself.','A street full of possibility. The Foundry is one of my stops.','Shannon, a dear friend from my San Francisco years. Still making days like this together.'][i]);if(chosen.size===3)finish('Folsom with Shannon. Palm Springs with Shannon. The places change; the friendship keeps coming with us.');pulse()});b.style.width='90px';b.style.height='52px';b.style.borderRadius='5px'});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='foundry'){range('Tune the hidden frequency',12,v=>{progress(1-Math.abs(v-73)/73);sound('bell',120+v*4);if(Math.abs(v-73)<4)finish('Locked in. MCMLXXXV leads back to Herrensauna: queer freedom, collective energy, a whole club culture to discover.');else say(v<73?'A little higher…':'A little lower…')})}
else if(id==='zeds'){['Texture','Space','Movement'].forEach((l,i)=>button(l,()=>{mode=i;chosen.add(i);sound(i===0?'pulse':i===1?'chord':'drop',i===1?164:90);progress(chosen.size/3);say(['A little grit. Zeds Dead’s story begins in hip-hop production.','A little room to float. Follow their ambient side.','A little force. The same curiosity, another channel.'][i]);if(chosen.size===3){opt.onComplete?.();done=true}pulse()}));controls.style.alignSelf='end';controls.style.paddingBottom='18px'}
else if(id==='niteharts'){['My heart','Your heart'].forEach((l,i)=>button(l,()=>{chosen.add(i);sound('bell',i?330:262);progress(chosen.size/2);if(chosen.size===2)finish('One signal. We found each other at NiteHarts on October 11, 2025. LateNite is October 11, 2026. A year later, the calendar keeps our thread.');else say('One heart is glowing. Give the other a beat.');pulse()}));controls.style.alignSelf='end';controls.style.paddingBottom='16px'}
else if(id==='latenite'){range('One more dance ← → A soft landing',30,v=>{progress(v/100);if(v>75){finish('A soft landing counts as a beautiful ending, too.');sound('chord',130)}else if(v<25){say('One more dance. Alison’s world is waiting in the sound & story.');sound('pulse',180)}pulse()})}
else if(id==='pokemon'){['Spark','Mischief','Glow'].forEach((l,i)=>button(l,()=>{mode=i;progress(1);sound(i===1?'pulse':'chord',180+i*50);finish(['A spark with a little courage. Your original concert creature is awake.','A mischievous little friend. Absolutely no responsible dancing.','A soft glow for the walk home. Keep a little magic with you.'][i]);pulse()}));controls.style.alignSelf='end';controls.style.paddingBottom='10px'}
else if(id==='pride'){const names=['Shannon','Joe','Mason','Alex','Gordon','A wish'];const words=['Shannon: a friendship from San Francisco in the 1990s, and our host in Palm Springs.','Joe: another beautiful weekend in our shared life.','Mason: another adventure in good company.','Alex Rogers: another color in our Palm Springs chapter.','Pride, November 6–8. Room to be ourselves, together.','My birthday is Monday, November 9. A little wish for another year of nights like these.'];colors.forEach((col,i)=>{const b=button(names[i],()=>{chosen.add(i);b.setAttribute('aria-pressed','true');sound(i===5?'chord':'bell',220*Math.pow(1.12246,i));progress(chosen.size/6);say(words[i]);if(chosen.size===6)finish('Our colors, together. Pride November 6–8. My birthday November 9. Another year is sweeter with you in it.');pulse()});b.style.width='70px';b.style.height='50px';b.style.borderRadius='7px'});controls.style.alignSelf='end';controls.style.paddingBottom='10px';controls.style.maxWidth='310px';controls.style.flexWrap='wrap'}
else if(id==='summit'){['Pulse','Bass','Air','Lift'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);b.setAttribute('aria-pressed','true');progress(chosen.size/4);sound(i===0?'pulse':i===1?'drop':'chord',130+i*30);if(chosen.size===4)finish('The room opens. In Comfort In Chaos, the big sound makes room for the vulnerable feeling.');pulse()});b.style.width='66px';b.style.height='66px'});controls.style.alignSelf='end';controls.style.paddingBottom='12px'}
else if(id==='stevie'){button('Turn it over',()=>{mode=1-mode;progress(1);sound('chord',mode?164:130);finish(mode?'December 2026: I am returning on my own, with room to hear what the songs bring up now.':'December 18, 2021: Stevie in the room. I was describing the performance as genius while it was happening.');pulse()});controls.style.alignSelf='end';controls.style.paddingBottom='45px'}
else if(id==='countdown'){['Joy','Courage','Us'].forEach((l,i)=>button(l,()=>{mode=i;say('Carry '+l.toLowerCase()+' into the next year.');sound('bell',330+i*55);draw()}));const go=button('Count us in',()=>{if(n&&!done)return;n=1;done=false;controls.hidden=true;function tick(){if(!active)return;progress(n/11);sound('bell',330+n*10);if(n===11){finish('Here’s to the next year of us. Joe, our lovely old tradition keeps making room for something new.');controls.hidden=false;return}n++;timers.push(setTimeout(tick,600))}tick()});go.style.background='#e7ff76';go.style.color='#172010';controls.style.alignSelf='end';controls.style.paddingBottom='10px'}
else if(id==='gryphus'){const memories=[{tag:'WALT · SINCE 1986',image:'gryphus-2026-bill',text:'The ride from Logan Airport to St. Paul’s. Forty years later: the same friendship, another gathering. Still making each other laugh.'},{tag:'CALE · A PLACE UNDER THE STARS',image:'gryphus-cale-2026',text:'From our WAVE XR / SXSW chapter to this Hill Country sky. Cale picked me a campsite with a view of the stars. I remember that welcome.'},{tag:'TOGETHER · THE NEXT CHAPTER',image:'gryphus-2026-arrival',text:'I connected Cale and Walt in 2023. In 2026, I got to share the festival they made. April 30–May 2, 2027: we go back.'}];const reveal=document.createElement('div');reveal.className='gryphus-reveal';reveal.hidden=true;root.insertBefore(reveal,$('.wonder-meter'));$('.wonder-stage').style.height='260px';['Walt','Cale','Together'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);mode=i;progress(chosen.size/3);sound('chord',[164.81,196,220][i]);b.setAttribute('aria-pressed','true');const m=memories[i];reveal.hidden=false;reveal.innerHTML=`<img src="assets/memories/${m.image}.webp" alt="A photograph from my Gryphus album"><p><small>${m.tag}</small>${m.text}</p>`;if(chosen.size===3)finish('The road back is made of people. Our next Hill Country chapter is already waiting.');pulse()});b.style.minWidth='76px'});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='edc'){range('Midnight ← → Morning',10,v=>{progress(v/100);if(v>88&&!done){finish('Stay for the light. Keep the people. This is what the tickets are for.');sound('chord',164);const im=document.createElement('img');im.src='assets/edc-crew-1600.webp';im.alt='Gordon and friends in a real EDC photograph';im.style.cssText='width:100%;border-radius:4px;margin-top:20px';root.append(im)}else draw()})}
else if(id==='shambhala'){['Gordon','Drake','Mel','David','Trent','Mason','Myke','Jacob'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);b.setAttribute('aria-pressed','true');progress(chosen.size/8);sound('bell',220*Math.pow(1.12246,i));if(chosen.size===8)finish('Eight lights. One Farmily. Drake and Dane opened this door for me. Now the circle keeps growing.');else say(chosen.size+' of our eight lanterns lit.');pulse()});b.style.width='62px';b.style.height='48px';b.style.borderRadius='4px'});controls.style.alignSelf='end';controls.style.padding='0 16px 10px';controls.style.maxWidth='340px'}
else if(id==='ggp-games'){['A chair','A game','One more round'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);b.setAttribute('aria-pressed','true');progress(chosen.size/3);sound('bell',220+i*110);say(['There is a place for you here.','No perfect introduction needed. Just deal someone in.','One more round. That’s how an evening becomes a memory.'][i]);if(chosen.size===3)finish('The table is set. Eric, BrenBren, Alex, Foster: pull up a chair. Tomorrow, we turn it up.');pulse()});b.style.width='95px';b.style.height='50px';b.style.borderRadius='6px'});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='fang-live'){['1893','A new life','Foster, live'].forEach((l,i)=>{const b=button(l,()=>{chosen.add(i);b.setAttribute('aria-pressed','true');progress(chosen.size/3);sound('chord',110+i*27.5);say(['A firehouse, with room above for the town to gather.','Art, music, community. The old room keeps welcoming new people.','Fang Speare LIVE. Foster’s birthday weekend, 2027.'][i]);if(chosen.size===3)finish('The windows are warm. A room for Foster’s sound. Open the story to hear the real Poe Beat and explore the firehouse.');pulse()});b.style.width='95px';b.style.height='50px';b.style.borderRadius='5px'});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='sincity'){const lanes=['left','middle','right'];say('The ball is coming down the middle. Find an open lane.');lanes.forEach((l,i)=>{const b=button(l==='middle'?'Center':l[0].toUpperCase()+l.slice(1),()=>{if(done){done=false;n=0;chosen.clear()}const incoming=(n*2+1)%3;mode=i;n++;if(i!==incoming){chosen.add(chosen.size);sound('pulse',165+chosen.size*33);progress(chosen.size/5);if(chosen.size===5)finish('Five good dodges. One loud sideline. Sin City, save a little room for our crew.');else say(chosen.size+' / 5 · Nice dodge! Next ball: '+lanes[(n*2+1)%3]+'.')}else{chosen.clear();progress(0);sound('bell',140);say('Got us! A fresh rally. Next ball: '+lanes[(n*2+1)%3]+'.')}pulse()});b.style.borderRadius='5px';b.style.height='50px'});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='olympics'){const b=button('Bounce',()=>{n++;if(n<4){sound('bell',220+n*55);progress(n/4);b.textContent=n===3?'DROP':'Bounce';say(n===3?'Three good bounces. Foster, this one’s for you.':n+' / 3 · Keep the rally going.')}else{sound('drop');finish('Foster’s drop. The Zeds Dead birthday plan was postponed. The rain check is still owed. Olympic squash lands on your birthday in 2028. Still finding new firsts.');b.textContent='Again';n=0}pulse()});controls.style.alignSelf='end';controls.style.paddingBottom='15px'}
else if(id==='blizzcon'){['Sky','Fire','Forest'].forEach((l,i)=>button(l,()=>{mode=i;sound('bell',220+i*80);progress(.4);draw()}));button('Open it',()=>{finish('Portal open. A world starts with a little play. Follow it into Pokémon’s meeting of games and music.');sound('chord',220);pulse()});controls.style.alignSelf='end';controls.style.paddingBottom='10px'}
else if(id==='comedy'){button('Another pose',()=>{pose=(pose+1)%3;draw();sound('bell',220+pose*70)});button('Strike it',()=>{finish(['Most likely to drop the bass at graduation.','Class clown energy. Joe, a little laughter belongs in the album too.','Perfect attendance… at the afterparty.'][pose]);sound('chord',170);pulse()});controls.style.alignSelf='end';controls.style.paddingBottom='10px'}
resize=new ResizeObserver(()=>draw());resize.observe(canvas);draw();return{destroy,stopSound};}
window.AfterHoursWonders={label:id=>titles[id]||data()[id]?.wonder?.name||'A little wonder',mount,destroy,stopSound,snapshot:()=>snapshot()};
})();
