'use strict';
const experiences=[["music", "01", "Music", "Big sound. Wide-open sky.", "A festival-scale show with the production to match the landscape.", "2027 artists and set times are coming.", "Hear the music", 0, 0], ["race", "02", "MTB race", "Find your next gear.", "A little grit. A little friendly competition.", "Race categories, entry, routes and timing await the 2027 program.", "Chase the climb", 1, 0], ["ride", "03", "Trail riding", "Take the long way.", "Limestone singletrack and room to find your rhythm.", "Ranch trails are established; festival access and guided rides are still to be announced.", "Ride together", 2, 0], ["demos", "04", "Bike demos", "Meet your next ride.", "Get closer to the bikes, the builders, and the details.", "Demo brands, booking and availability are proposed, not yet confirmed.", "Try something new", 3, 0], ["run", "05", "Trail running", "Follow your feet.", "A different way to feel the Hill Country.", "Festival running routes, distances and sessions will follow.", "Run the hills", 0, 1], ["camp", "06", "Camping", "Stay for the stars.", "The kind of night you want to keep a little longer.", "Festival camping, facilities and booking terms are coming.", "Make yourself at home", 1, 1], ["taste", "07", "Food + drink", "Good food. Better company.", "Something delicious, shared outside.", "2027 vendors and food options will be announced.", "Pull up a chair", 2, 1], ["family", "08", "Family adventure", "Make a new favorite memory.", "Space for discovery, small adventures, and time together.", "Activities, age guidance and family facilities are being developed.", "Explore together", 3, 1], ["skills", "09", "Skills clinics", "Try. Learn. Go again.", "Build confidence with a little encouragement.", "Clinics, instructors, skill levels and registration are to be confirmed.", "Find your confidence", 0, 2], ["expo", "10", "Outdoor expo", "Find your kind of outdoors.", "Meet the people making the gear that gets you out there.", "Exhibitors and the demo village are part of the proposed 2027 experience.", "Meet the makers", 1, 2], ["recover", "11", "Recovery + wellness", "A slower kind of good.", "A little room to stretch, reset, and take it all in.", "Sessions and facilities will be published with the program.", "Take a breath", 2, 2]];
const $=s=>document.querySelector(s);const all=s=>[...document.querySelectorAll(s)];
let saved=[];try{const list=JSON.parse(localStorage.getItem('gryphus-weekend')||'[]');saved=Array.isArray(list)?list.filter(id=>experiences.some(x=>x[0]===id)):[]}catch{}
let active=experiences[0],toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function save(){try{localStorage.setItem('gryphus-weekend',JSON.stringify(saved))}catch{document.querySelector('.saved-panel .small').textContent='This browser cannot save between visits. Copy your weekend to keep it.'}renderSaved()}
function renderSaved(){$('#saved-count').textContent=saved.length+' MOMENT'+(saved.length===1?'':'S');$('#saved-list').replaceChildren();if(!saved.length){let p=document.createElement('p');p.className='empty-plan';p.textContent='What’s your first stop? Open an experience above and save it here.';$('#saved-list').append(p)}else saved.forEach(id=>{const x=experiences.find(e=>e[0]===id),row=document.createElement('div'),txt=document.createElement('span'),b=document.createElement('button');row.className='saved-item';txt.textContent=x[2];b.textContent='×';b.setAttribute('aria-label','Remove '+x[2]);b.onclick=()=>{saved=saved.filter(i=>i!==id);save();syncSaveButton()};row.append(txt,b);$('#saved-list').append(row)})}
function syncSaveButton(){const has=saved.includes(active[0]);$('#save-experience').innerHTML=has?'Saved to my weekend <span>✓</span>':'Add to my weekend <span>+</span>';$('#save-experience').setAttribute('aria-pressed',has)}
function populate(x){active=x;$('#modal-scene').style.setProperty('--x',x[7]*100/3+'%');$('#modal-scene').style.setProperty('--y',x[8]*50+'%');$('#modal-scene').setAttribute('role','img');$('#modal-scene').setAttribute('aria-label',x[2]+' campaign concept');$('#modal-category').textContent=x[1]+' / '+x[2].toUpperCase();$('#modal-title').textContent=x[3];$('#modal-desc').textContent=x[4];$('#modal-status').textContent=x[5];syncSaveButton()}
all('.experience').forEach(b=>b.addEventListener('click',()=>{populate(experiences.find(x=>x[0]===b.dataset.id));$('#experience-dialog').showModal();document.body.style.overflow='hidden'}));
$('#save-experience').onclick=()=>{if(saved.includes(active[0])){saved=saved.filter(id=>id!==active[0]);toast('Removed from your weekend')}else{saved.push(active[0]);toast(active[2]+' added to your weekend')}save();syncSaveButton()};
$('#next-experience').onclick=()=>{populate(experiences[(experiences.indexOf(active)+1)%experiences.length]);$('#experience-dialog').scrollTop=0};
all('dialog').forEach(d=>{d.querySelector('.dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>document.body.style.overflow='');d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$('#credits-open').onclick=()=>{$('#credits-dialog').showModal();document.body.style.overflow='hidden'};
const groups={all:experiences.map(x=>x[0]),move:['race','ride','demos','run','skills'],gather:['music','taste','family','expo'],slow:['camp','recover']};
all('.filter').forEach(b=>b.onclick=()=>{all('.filter').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});$('.experience-grid').classList.toggle('filtered',b.dataset.filter!=='all');all('.experience').forEach(card=>{card.hidden=!groups[b.dataset.filter].includes(card.dataset.id)});});
$('#copy-plan').onclick=async()=>{const t='My Gryphus weekend · April 30–May 2, 2027\nFlat Rock Ranch, Comfort, Texas\n\n'+(saved.length?saved.map(id=>'• '+experiences.find(x=>x[0]===id)[2]).join('\n'):'Come explore the weekend with me.')+'\n\nA wish list while the 2027 program takes shape.\n'+((location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname))?'https://gordonusc.github.io/the-cabinet/gryphus/':location.origin+location.pathname)+'?direction='+encodeURIComponent(document.documentElement.dataset.direction);try{await navigator.clipboard.writeText(t);$('#copy-status').textContent='Copied. Paste it into a message to your people.'}catch{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/plain'}));a.download='my-gryphus-weekend.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#copy-status').textContent='Your weekend has been downloaded as a text file.'}};
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});all('.section-intro,.experience,.people-copy,.weekend>div,.plan-title,.plan-details').forEach(el=>{el.classList.add('reveal');io.observe(el)})}
renderSaved();
const tileResize=new ResizeObserver(entries=>entries.forEach(({target,contentRect:r})=>{target.style.setProperty('--tile-size',Math.ceil(Math.max(r.width,r.height))+'px')}));all('.scene').forEach(el=>tileResize.observe(el));
if(document.documentElement.dataset.direction==='basecamp')$('.art-caption').textContent='GORDON + CALE / A REAL GRYPHUS MEMORY, 2026';
