(()=>{'use strict';const host=document.querySelector('[data-gryphus-midnight]');if(!host)return;
host.classList.add('night-invitation');host.innerHTML='<div><p class="night-kicker">WHEN THE TRAILS GIVE WAY TO THE STAGE</p><h2>THE NIGHTS<br>ARE MUSIC.</h2><p>Live music until 10 p.m.<br>A whole day outside. A night together.</p></div><button class="midnight-secret" type="button" aria-label="Reveal a secret after-hours surprise"><span class="secret-moon" aria-hidden="true">☾</span><span>Psst… one more?</span><i aria-hidden="true">↗</i></button>';
const dialog=document.createElement('dialog');dialog.className='midnight-dialog';dialog.setAttribute('aria-labelledby','midnight-title');dialog.innerHTML='<button type="button" class="midnight-close" aria-label="Close the midnight surprise">×</button><div class="midnight-inner"><div class="midnight-record" aria-hidden="true"><div class="record-sun">G<br><small>AFTER DARK</small></div></div><p class="night-kicker">YOU FOUND THE AFTER-HOURS / 10 P.M. — MIDNIGHT</p><h2 id="midnight-title">THE BOOTS<br>STAY ON.</h2><p class="midnight-artist">DISKO COWBOY</p><p class="midnight-copy">Cale, here’s a little Texas after dark.<br>Country memories. Disco energy. One more dance.</p><div class="midnight-audio"><button type="button" class="midnight-play">Play Disko Cowboy’s preview ▶</button><button type="button" class="midnight-stop">Stop sound ■</button><label>Volume <input type="range" min="0" max="1" step="0.05" value="0.6" aria-label="Disko Cowboy preview volume"></label><p class="midnight-status" role="status"></p></div><div class="midnight-links"><a href="https://open.spotify.com/artist/74oX0NocVrrkOf0Mtir1wB?utm_source=openai&amp;utm_medium=chatgpt" target="_blank" rel="noopener">More on Spotify ↗</a><a href="https://www.diskocowboy.com/" target="_blank" rel="noopener">Meet Disko Cowboy ↗</a><a href="https://vinylranch.bandcamp.com/music" target="_blank" rel="noopener">The country remix rabbit hole ↗</a></div><p class="midnight-fine">After-hours DJ concept until midnight. Disko Cowboy is Gordon’s listening inspiration for Cale; an artist booking has not been announced. Preview courtesy of Spotify.</p></div>';
document.body.append(dialog);const q=s=>dialog.querySelector(s);const audio=new Audio();audio.hidden=true;dialog.append(audio);audio.preload='none';audio.volume=.6;audio.src='https://p.scdn.co/mp3-preview/c100b97f429b7c1a8bdeda03ed02e0ed7552c027.mp3';
let generation=0;
function stop(message='Sound stopped.'){generation++;audio.pause();try{audio.currentTime=0}catch{}dialog.classList.remove('is-playing');q('.midnight-status').textContent=message}
async function play(){document.querySelectorAll('[data-gryphus-sound]').forEach(el=>window.GryphusMood?.mount(el)?.stop());document.querySelectorAll('[data-gryphus-lineup]').forEach(el=>window.GryphusLineup?.mount(el)?.stop());const run=++generation;q('.midnight-status').textContent='Loading the preview…';try{await audio.play();if(run!==generation||!dialog.open||document.hidden){audio.pause();return}dialog.classList.add('is-playing');q('.midnight-status').textContent='Playing Disko Cowboy’s Spotify preview.'}catch{if(run===generation)q('.midnight-status').textContent='The preview could not play here. Try Play again, or open Spotify above.'}}
const triggers=[host.querySelector('button'),document.getElementById('gSun')].filter(Boolean);triggers.forEach(button=>button.addEventListener('click',event=>{event.preventDefault();dialog.showModal();triggers.forEach(b=>b.setAttribute('aria-expanded','true'));play()}));dialog.addEventListener('close',()=>triggers.forEach(b=>b.setAttribute('aria-expanded','false')));q('.midnight-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>stop());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
q('.midnight-play').onclick=play;q('.midnight-stop').onclick=()=>stop();q('input').oninput=e=>audio.volume=Number(e.target.value);audio.onended=()=>stop('Preview complete. Follow the remix rabbit hole for more.');audio.onerror=()=>{q('.midnight-status').textContent='Preview unavailable here. Open Spotify or the artist’s remix page.';dialog.classList.remove('is-playing')};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('Paused while you were away. Tap Play to continue.')});window.addEventListener('pagehide',()=>stop());document.addEventListener('click',e=>{if(e.target.closest('.gm-play,.gl-load'))stop()},true);
})();
