(()=>{'use strict';const room=document.querySelector('.midnight-dialog');if(!room)return;const inner=room.querySelector('.midnight-inner');
const toggle=document.createElement('button');toggle.className='midnight-effects-toggle';toggle.type='button';toggle.setAttribute('aria-pressed','false');const toolbar=document.createElement('div');toolbar.className='midnight-toolbar';toolbar.append(toggle,room.querySelector('.midnight-close'));room.prepend(toolbar);
const canvas=document.createElement('canvas');canvas.className='midnight-liquid';canvas.setAttribute('aria-hidden','true');inner.prepend(canvas);const ctx=canvas.getContext('2d');
const waves=document.createElement('div');waves.className='midnight-wave-photo';waves.setAttribute('aria-hidden','true');waves.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" aria-hidden="true"><filter id="midnight-ripple" x="-20%" y="-20%" width="140%" height="140%"><feTurbulence type="fractalNoise" baseFrequency="0.005 0.009" numOctaves="1" seed="8" result="noise"><animate attributeName="baseFrequency" dur="18s" values="0.005 0.009;0.009 0.006;0.005 0.009" repeatCount="indefinite"/></feTurbulence><feDisplacementMap in="SourceGraphic" in2="noise" scale="25" xChannelSelector="R" yChannelSelector="G"/></filter></svg><div class="midnight-light-field"></div>';inner.prepend(waves);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let enabled=!reduced.matches,raf=0,time=0,last=0;try{const saved=localStorage.getItem('gryphus-midnight-effects');if(saved!==null)enabled=saved==='on'&&!reduced.matches}catch{}
function resize(){const width=inner.clientWidth,height=inner.clientHeight;canvas.width=Math.round(width);canvas.height=Math.round(height)}
function frame(stamp){if(!room.open||!enabled||document.hidden){raf=0;return}if(!last||stamp-last>31){time+=.009;last=stamp;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);for(let n=0;n<7;n++){ctx.beginPath();for(let x=-30;x<=w+30;x+=14){const y=h*(.1+n*.145)+Math.sin(x/w*4.8+time+n*.7)*h*.07+Math.sin(x/w*8-time*.65)*h*.026;x===-30?ctx.moveTo(x,y):ctx.lineTo(x,y)}for(let x=w+30;x>=-30;x-=14){const y=h*(.14+n*.145)+Math.sin(x/w*4.8+time+n*.7)*h*.07+Math.sin(x/w*8-time*.65)*h*.026;ctx.lineTo(x,y)}ctx.closePath();ctx.fillStyle=n%2?'rgba(218,175,85,.035)':'rgba(152,182,133,.045)';ctx.fill()}}raf=requestAnimationFrame(frame)}
function sync(){cancelAnimationFrame(raf);raf=0;const on=enabled&&room.open&&!document.hidden;room.classList.toggle('effects-on',on);toggle.textContent=enabled?'Effects off':'Effects on';toggle.setAttribute('aria-pressed',String(enabled));toggle.setAttribute('aria-label',enabled?'Turn off the after-hours visual effects':'Turn on the after-hours visual effects');const svg=waves.querySelector('svg');if(on){resize();svg.unpauseAnimations?.();last=0;raf=requestAnimationFrame(frame)}else{ctx.clearRect(0,0,canvas.width,canvas.height);svg.pauseAnimations?.()}}
toggle.onclick=()=>{enabled=!enabled;try{localStorage.setItem('gryphus-midnight-effects',enabled?'on':'off')}catch{}sync()};
room.addEventListener('close',sync);document.querySelector('.midnight-secret')?.addEventListener('click',sync);document.addEventListener('visibilitychange',sync);window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);raf=0;room.classList.remove('effects-on')});reduced.addEventListener('change',()=>{if(reduced.matches)enabled=false;sync()});new ResizeObserver(()=>{if(room.open)resize()}).observe(inner);sync();
})();
