const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const root=path.join(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'projects.json'),'utf8'));
async function run(){
 cp.execFileSync(process.execPath,[path.join(root,'scripts/build-cabinet.cjs'),'--check']);
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const dom=new JSDOM(html,{url:'https://gordonusc.github.io/the-cabinet/?for=cale&q=dodgeball&room=stadium#projects',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,d=w.document;w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=function(){};
 let copied='';Object.defineProperty(w.navigator,'clipboard',{configurable:true,value:{writeText:async s=>{copied=s}}});
 w.eval(fs.readFileSync(path.join(root,'cabinet-20261003.js'),'utf8'));
 const q=d.querySelector('#search'),room=d.querySelector('#room'),sort=d.querySelector('#sort');
 const cards=()=>[...d.querySelectorAll('.project')],visible=()=>cards().filter(p=>!p.hidden),ids=()=>cards().map(p=>p.dataset.id),fire=(el,type)=>el.dispatchEvent(new w.Event(type));
 assert.equal(data.projects.length,44);assert.equal(new Set(data.projects.map(p=>p.id)).size,44);assert.equal(cards().length,39);assert.equal(d.querySelectorAll('[data-related-id]').length,5);assert.equal(d.querySelector('#project-total').textContent,'39');assert.equal(d.querySelector('#footer-total').textContent,'39');
 const originalOrder=data.projects.filter(p=>p.role==='experience').map(p=>p.id);assert.deepEqual(ids(),originalOrder);
 for(const p of data.projects){const el=d.querySelector('#project-'+p.id);assert.equal(p.role==='related'?el.querySelector('.related-name').firstChild.textContent.trim():el.querySelector('.project-name').textContent,p.title);const url=new URL(el.querySelector('a').href);if(p.id==='island-hop')url.searchParams.delete('pilot');if(p.id==='shows-with-friends')url.searchParams.delete('for');assert.equal(String(url),p.url);}
 assert.equal(d.querySelectorAll('.project-number,.feature-index,.door-number').length,0);assert.equal(visible().length,1);assert.equal(visible()[0].dataset.id,'final-boss');assert.match(room.selectedOptions[0].textContent,/Saved category/);
 d.querySelector('#clear-filters').click();assert.equal(visible().length,39);assert.equal(d.activeElement,q);assert.equal(w.location.search,'?for=cale');
 for(const term of ['music','dodgeball','Minecraft','mood board','CÁLE','AI','Final Boss','The Skill Tree','What I Learned About Myself','CHRIS LAKE, TONIGHT']){q.value=term;fire(q,'input');assert.ok(visible().length,term+' finds entries');}
 q.value='music';room.value='music';fire(room,'change');assert.ok(visible().length);assert.ok(visible().every(p=>p.dataset.collection==='music'));
 sort.value='az';fire(sort,'change');assert.deepEqual(ids(),data.projects.filter(p=>p.role==='experience').sort((a,b)=>a.title.localeCompare(b.title,'en',{sensitivity:'base'})).map(p=>p.id));assert.equal(d.querySelector('#alphabetical-index').hidden,false);assert.ok([...d.querySelectorAll('.collection')].every(s=>s.hidden));
 d.querySelector('#clear-filters').click();assert.equal(sort.value,'az');assert.equal(visible().length,39);sort.value='curated';fire(sort,'change');assert.deepEqual(ids(),originalOrder);assert.equal(d.querySelector('#alphabetical-index').children.length,0);assert.equal([...d.querySelectorAll('.collection')].filter(s=>!s.hidden).length,7);
 q.value='no-such-xyz';fire(q,'input');assert.equal(visible().length,0);assert.equal(d.querySelector('#empty').hidden,false);d.querySelector('#clear-filters').click();
 for(const oldRoom of Object.keys(data.legacyRooms)){w.history.replaceState(null,'','?room='+oldRoom);w.dispatchEvent(new w.PopStateEvent('popstate'));assert.deepEqual(visible().map(p=>p.dataset.id),data.projects.filter(p=>p.role==='experience'&&p.legacyRooms.includes(oldRoom)).map(p=>p.id));}
 w.history.replaceState(null,'','?for=cale&sort=az&q=kit+dodgeball&room=stadium#projects');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(visible().length,1);assert.equal(sort.value,'az');assert.equal(d.querySelector('#recipient-note').hidden,false);
 for(const route of data.routes){d.querySelector('[data-route='+route.key+']').click();assert.equal(d.querySelector('#adventure').hidden,false);assert.equal(d.activeElement.id,'adventure');assert.equal(d.querySelector('#adventure-title').textContent,route.title);assert.deepEqual([...d.querySelectorAll('#adventure-stops a')].map(a=>a.firstChild.textContent),route.stops.map(s=>data.projects.find(p=>p.id===s.id).title));assert.equal(new w.URL(w.location.href).searchParams.get('adventure'),route.key);}
 d.querySelector('[data-route=lift]').click();assert.ok([...d.querySelectorAll('#adventure-stops a')].some(a=>a.href.includes('?pilot=cale')));d.querySelector('#copy-adventure').click();await new Promise(r=>setTimeout(r,0));assert.equal(copied,w.location.href);assert.equal(new w.URL(copied).searchParams.get('for'),'cale');assert.match(d.querySelector('#adventure-status').textContent,/copied/);
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async()=>{throw Error('unavailable')}}});d.querySelector('#copy-adventure').click();await new Promise(r=>setTimeout(r,0));const fallback=d.querySelector('#adventure-link');assert.equal(fallback.hidden,false);assert.equal(d.activeElement,fallback);assert.equal(fallback.selectionEnd,fallback.value.length);
 w.history.replaceState(null,'',copied);w.dispatchEvent(new w.Event('pageshow'));assert.equal(fallback.hidden,true);assert.equal(sort.value,'az');assert.equal(d.querySelector('#adventure-title').textContent,'Play and make sound');
 w.history.replaceState(null,'','?adventure=invalid&room=invalid&sort=invalid');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(d.querySelector('#adventure').hidden,true);assert.equal(room.value,'all');assert.equal(sort.value,'curated');assert.deepEqual(ids(),originalOrder);assert.equal(d.querySelector('#recipient-note').hidden,true);assert.equal(d.querySelector('[data-project-link=island-hop]').href,'https://gordonusc.github.io/island-hop/');
 assert.match(d.querySelector('#project-ctin-s9-students').textContent,/Alternate lesson URL/);assert.equal(d.querySelector('#project-ctin-s9-students').closest('.project').dataset.id,'ctin-sept21');
 for(const [query,child,parent] of [['The Research File','gordon-media-research','media-log'],['USA / 26','usa-26','usmnt-2026-public'],['Cale, Come On In','for-cale','cale-yarborough'],['September 21 student resources','ctin-s9-students','ctin-sept21']]){q.value=query;fire(q,'input');assert.ok(visible().some(p=>p.dataset.id===parent));assert.equal(d.querySelector('[data-related-id='+child+']').hidden,false);}
 q.value='Good Company';fire(q,'input');assert.equal(visible().length,0);assert.equal(d.querySelector('[data-related-id=good-company]').hidden,false);assert.equal(d.querySelector('#empty').hidden,true);assert.equal(d.querySelector('#results').textContent,'1 related link');
 d.querySelector('#clear-filters').click();assert.equal(d.querySelector('#results').textContent,'39 experiences · 5 related links');
 dom.window.close();console.log('PASS: canonical 39-experience / 5-related-link rendering; titles and destinations; no catalogue ordinals; seven collections and legacy category URLs; old/new search aliases; A–Z and grouped restoration; no-results/clear; explicit route contents, copied URL/fallback; Cale links; pageshow/popstate; nested alternate lesson, invitation, earlier edition, research companion, and earlier-tour search.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
