/* Presentation preference only. Staff content requires real authentication before deployment. */
(()=>{'use strict';const key='ggp-audience-v1',root=document.documentElement;
const staffRoute=()=>/\/(eric-review|analytics|review-brief)\.html$/.test(location.pathname)||/^#(production|review)(\/|$)/.test(location.hash);
let view='donor';try{view=localStorage.getItem(key)==='staff'?'staff':'donor'}catch{}if(staffRoute())view='staff';root.dataset.ggpView=view;
function paint(){root.dataset.ggpView=view;root.dataset.ggpStaffPage=String(staffRoute());document.querySelectorAll('[data-audience-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.audienceChoice===view)));document.querySelectorAll('a[href]').forEach(a=>{const u=new URL(a.getAttribute('href'),location.href);if(u.origin===location.origin&&(/\/(eric-review|analytics|review-brief)\.html$/.test(u.pathname)||/^#(production|review)(\/|$)/.test(u.hash)))a.setAttribute('data-staff-only','')});const context=document.getElementById('audience-context');const text=view==='staff'?'Staff workspace · production, editorial review and measurement. View toggle only; not access control.':'Donor view · discover programs, compare support and explore giving.';if(context&&context.textContent!==text)context.textContent=text;}
function set(value,navigate){view=value;try{localStorage.setItem(key,view)}catch{}paint();if(navigate){const hash=view==='staff'?'#production':'#donors';if(/\/(eric-review|analytics|review-brief)\.html$/.test(location.pathname))location.href='./'+hash;else location.hash=hash;}window.ggpSound?.('select')}
window.ggpEnsureAudience=()=>{if(staffRoute()&&view!=='staff')set('staff',false);paint()};
document.addEventListener('DOMContentLoaded',()=>{const header=document.querySelector('header')||document.querySelector('main')||document.body;const control=document.createElement('section');control.className='audience-control';control.setAttribute('aria-label','Choose your view');control.innerHTML='<div class="audience-toggle" role="group" aria-label="Experience view"><button type="button" data-audience-choice="donor" title="Show program discovery, comparisons and giving portfolios.">Donor view</button><button type="button" data-audience-choice="staff" title="Show production, editorial review and measurement tools. This is not a sign-in.">Staff view</button></div><p id="audience-context" role="status"></p>';header.before(control);control.querySelectorAll('button').forEach(b=>b.onclick=()=>set(b.dataset.audienceChoice,true));paint();new MutationObserver(()=>paint()).observe(document.body,{subtree:true,childList:true});});
window.addEventListener('storage',e=>{if(e.key===key){view=e.newValue==='staff'?'staff':'donor';if(view==='donor'&&staffRoute()){if(/\.html$/.test(location.pathname)&&!location.pathname.endsWith('/index.html'))location.href='./#donors';else location.hash='#donors';}paint()}});
})();
