window.GGPPublicGrants=[
  {
    "id": "mac-dyn-2025",
    "funder": "MacArthur Foundation",
    "recipient": "Northwestern University \u00b7 Digital Youth Network",
    "year": 2025,
    "amount": 100000,
    "theme": "Learning + access",
    "geography": "Illinois, US",
    "duration": "7 months",
    "purpose": "Flexible support for opportunity mapping and youth learning.",
    "source": "https://www.macfound.org/grantee/northwestern-university-177/",
    "basis": "Awarded",
    "currency": "USD",
    "checked": "2026-09-07"
  },
  {
    "id": "mac-fuse-2014",
    "funder": "MacArthur Foundation",
    "recipient": "Northwestern University \u00b7 FUSE",
    "year": 2014,
    "amount": 385000,
    "theme": "Learning + access",
    "geography": "Illinois, US",
    "duration": "2 years 5 months",
    "purpose": "STEM challenges and evaluation of skills development.",
    "source": "https://www.macfound.org/grantee/northwestern-university-177/",
    "basis": "Awarded",
    "currency": "USD",
    "checked": "2026-09-07"
  },
  {
    "id": "mac-fuse-2013",
    "funder": "MacArthur Foundation",
    "recipient": "Northwestern University \u00b7 FUSE",
    "year": 2013,
    "amount": 350000,
    "theme": "Learning + access",
    "geography": "Illinois, US",
    "duration": "1 year",
    "purpose": "Expansion of hands-on STEM learning challenges.",
    "source": "https://www.macfound.org/grantee/northwestern-university-177/",
    "basis": "Awarded",
    "currency": "USD",
    "checked": "2026-09-07"
  },
  {
    "id": "mellon-kinfolk-2021",
    "funder": "Mellon Foundation",
    "recipient": "Kinfolk Tech Foundation",
    "year": 2021,
    "amount": 1800000,
    "theme": "Creative technology",
    "geography": "New York, US",
    "duration": "Not specified in source story",
    "purpose": "Monuments Project support for augmented-reality history and public storytelling.",
    "source": "https://www.mellon.org/grant-story/new-technology-opens-doors-to-meet-people-and-places-of-our-past",
    "basis": "Awarded",
    "currency": "USD",
    "checked": "2026-09-07"
  },
  {
    "id": "mellon-kinfolk-2024",
    "funder": "Mellon Foundation",
    "recipient": "Kinfolk Tech Foundation",
    "year": 2024,
    "amount": 3500000,
    "theme": "Creative technology",
    "geography": "New York, US",
    "duration": "Not specified in source story",
    "purpose": "Further Monuments Project support; separate award from 2021.",
    "source": "https://www.mellon.org/grant-story/new-technology-opens-doors-to-meet-people-and-places-of-our-past",
    "basis": "Awarded",
    "currency": "USD",
    "checked": "2026-09-07"
  }
];