/* One authored level; render-independent simulation, deterministic fixed-step friendly. */
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const NAMES=['Gordon','Eric'];
export const COLORS=['#ffe29a','#79e7fa'];
export const STAGES=[
 ['01 · TWO SHORES, ONE WORLD','Make room for two.','Walk onto either glowing welcome stone. Your partner takes the other.'],
 ['02 · THE WISCAGO CROSSING','A way across. For everyone.','At each broken span: Eric sketches it blue. Gordon kindles it gold. Use your power nearby.'],
 ['03 · AN ECHO OF ROSEMONT','Bring the lost lights home.','Find three storm knots. Eric steadies each with blue light; Gordon releases its gold. Dash through the pulses.'],
 ['04 · ALL ROADS LEAD HOME','Leave no one behind.','Stand on the two stones by the portal. There’s a place here for both of you.']
];
const HERO=(id,x,y)=>({id,x,y,hp:5,cool:0,dash:0,dashCool:0,inv:0,cast:0,emote:0,walk:0,face:1,lastX:0,lastY:-1,revive:0});
export class Adventure{
 constructor({mode='solo',gentle=false,emit=()=>{}}={}){this.mode=mode;this.gentle=gentle;this.emit=emit;this.heroes=[HERO(0,11,33),HERO(1,13,33)];this.active=0;this.stage=0;this.time=0;this.finished=false;this.paused=false;this.plateTime=0;this.finishTime=0;this.rescues=0;this.combos=0;this.cheers=0;this.cheerCool=0;this.aiClock=0;this.beams=[];this.pulses=[];this.wisps=[];this.bridge=[{x:12,y:24,done:false,blue:0},{x:12,y:22,done:false,blue:0},{x:12,y:20,done:false,blue:0}];this.knots=[{x:8,y:15,done:false,blue:0},{x:16,y:15,done:false,blue:0},{x:12,y:10,done:false,blue:0}];this.plates=[{x:9,y:28},{x:15,y:28}];this.portalPlates=[{x:10,y:8},{x:14,y:8}];this.events=0;}
 event(type,data={}){this.emit({type,...data});}
 tile(x,y){x=Math.round(x);y=Math.round(y);if(y>=26&&y<=36&&Math.pow((x-12)/9,2)+Math.pow((y-31)/7,2)<1.25)return 'grass';if(y===25&&x>=10&&x<=14)return this.stage>0?'path':'gate';if(y>=20&&y<=24&&x>=11&&x<=13){const i=y>=23?0:y>=21?1:2;return this.bridge[i].done?'bridge':'gap';}if(y>=6&&y<=19&&Math.pow((x-12)/9,2)+Math.pow((y-13)/8.8,2)<1.12)return 'crown';return null;}
 walkable(x,y){const t=this.tile(x,y);return !!t&&t!=='gap'&&t!=='gate';}
 move(h,dx,dy,dt){if(h.hp<=0)return;const len=Math.hypot(dx,dy);h.walk=0;if(len<.08)return;dx/=Math.max(1,len);dy/=Math.max(1,len);h.lastX=dx;h.lastY=dy;h.face=dx-dy>=0?1:-1;const speed=(h.dash>0?10:3.35)*dt;const nx=h.x+dx*speed,ny=h.y+dy*speed;if(this.walkable(nx,h.y)){h.x=nx;h.walk=1;}if(this.walkable(h.x,ny)){h.y=ny;h.walk=1;}}
 dash(id){const h=this.heroes[id];if(this.paused||this.finished||h.hp<=0||h.dashCool>0)return;h.dash=.24;h.inv=.35;h.dashCool=1.15;this.event('dash',{hero:id});}
 swap(){if(this.mode!=='solo'||this.paused)return;this.active=1-this.active;this.event('swap',{hero:this.active});}
 power(id){const h=this.heroes[id];if(this.paused||this.finished||h.hp<=0||h.cool>0)return false;h.cool=.85;h.cast=.42;const friend=this.heroes[1-id];const linked=distance(h,friend)<4;const range=linked?3.4:2.5;this.event('power',{hero:id,x:h.x,y:h.y,range});
 const choices=this.stage===1?this.bridge:this.stage===2?this.knots:[];let targets=choices.filter(n=>!n.done&&distance(n,h)<range).sort((a,b)=>distance(a,h)-distance(b,h));if(this.stage===1)targets=targets.filter(n=>choices.slice(0,choices.indexOf(n)).every(p=>p.done));
 const n=targets[0];if(n){if(id===1){n.blue=9;this.beams.push({a:{x:h.x,y:h.y},b:{x:n.x,y:n.y},color:COLORS[1],life:.4});this.event('sketch',{x:n.x,y:n.y});}else if(n.blue>0){n.done=true;n.blue=0;this.combos++;this.beams.push({a:{...friend},b:{...n},color:COLORS[1],life:.8},{a:{...h},b:{...n},color:COLORS[0],life:.8});this.event('restore',{x:n.x,y:n.y,kind:this.stage===1?'bridge':'light'});this.heroes.forEach(p=>{p.hp=Math.min(5,p.hp+1);p.emote=.7;});if(this.stage===1&&this.bridge.every(n=>n.done)){this.stage=2;this.checkpoint();this.event('chapter',{stage:2});this.wisps=[{x:8,y:15,anchor:0,timer:2},{x:16,y:15,anchor:1,timer:3.3},{x:12,y:10,anchor:2,timer:1.4}];}else if(this.stage===2&&this.knots.every(n=>n.done)){this.stage=3;this.pulses=[];this.wisps=[];this.event('chapter',{stage:3});}}else this.event('needsEric');}
 // Both powers clear threatening motes, but neither alone can restore a knot.
 for(const p of this.pulses){if(distance(h,p)<range&&p.life>0){p.life=0;this.event('spark',{x:p.x,y:p.y,color:COLORS[id]});}}
 return true;}
 cheer(){if(this.paused||this.finished||this.cheerCool>0)return;const[a,b]=this.heroes;if(distance(a,b)>3){this.event('toast',{text:'Come a little closer for a high-five.'});return;}this.cheerCool=7;this.cheers++;for(const h of this.heroes){h.emote=1.4;h.hp=Math.min(5,h.hp+1);}this.event('cheer',{x:(a.x+b.x)/2,y:(a.y+b.y)/2});}
 checkpoint(){for(const h of this.heroes){h.hp=5;h.inv=2;}this.event('checkpoint');}
 nextStep(from,to){const start=[Math.round(from.x),Math.round(from.y)],end=[Math.round(to.x),Math.round(to.y)],key=(x,y)=>x+','+y;let q=[start],seen=new Set([key(...start)]),parent=new Map(),found=null;for(let i=0;i<q.length&&i<800;i++){const p=q[i];if(Math.hypot(p[0]-end[0],p[1]-end[1])<1){found=p;break;}for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const n=[p[0]+dx,p[1]+dy],k=key(...n);if(!seen.has(k)&&this.walkable(...n)){seen.add(k);parent.set(k,p);q.push(n);}}}if(!found)return to;while(parent.has(key(...found))&&key(...parent.get(key(...found)))!==key(...start))found=parent.get(key(...found));return{x:found[0],y:found[1]};}
 companion(dt){const h=this.heroes[1-this.active],leader=this.heroes[this.active];if(h.hp<=0)return;let dest=null;if(leader.hp<=0)dest=leader;else if(this.stage===0||this.stage===3){const plates=this.stage===0?this.plates:this.portalPlates;const li=distance(leader,plates[0])<distance(leader,plates[1])?0:1;if(distance(leader,plates[li])<2)dest=plates[1-li];}const helpNodes=this.stage===1?this.bridge:this.stage===2?this.knots:[];const helpNode=helpNodes.find((n,i)=>!n.done&&distance(leader,n)<3.5&&(this.stage!==1||helpNodes.slice(0,i).every(p=>p.done)));if(!dest&&helpNode&&distance(h,helpNode)>2.6)dest={x:helpNode.x,y:helpNode.y+2};if(!dest&&distance(h,leader)>1.5)dest={x:leader.x+(leader.x>12?-1:1),y:leader.y+.3};if(dest&&distance(h,dest)>.18){const step=this.nextStep(h,dest);this.move(h,step.x-h.x,step.y-h.y,dt);}else h.walk=0;
 const choices=this.stage===1?this.bridge:this.stage===2?this.knots:[];const target=choices.find((n,i)=>!n.done&&distance(h,n)<3.3&&distance(leader,n)<3.4&&(this.stage!==1||choices.slice(0,i).every(p=>p.done)));if(target&&(h.id===1||target.blue>0))this.power(h.id);
 if(this.pulses.some(p=>distance(p,h)<1.4&&p.life>0)&&h.dashCool<=0)this.dash(h.id);}
 update(dt,input=[{},{}]){if(this.paused||this.finished)return;dt=clamp(dt,0,.05);this.time+=dt;this.cheerCool=Math.max(0,this.cheerCool-dt);for(const h of this.heroes){for(const k of ['cool','dash','dashCool','inv','cast','emote'])h[k]=Math.max(0,h[k]-dt);h.walk=0;const i=input[h.id]||{};if(this.mode==='coop'||h.id===this.active){let dx=i.x||0,dy=i.y||0;if(h.dash>0&&Math.hypot(dx,dy)<.08){dx=h.lastX;dy=h.lastY;}this.move(h,dx,dy,dt);}}
 for(const n of [...this.bridge,...this.knots])n.blue=Math.max(0,n.blue-dt);if(this.mode==='solo')this.companion(dt);
 const plates=this.stage===0?this.plates:this.stage===3?this.portalPlates:null;if(plates){const pair=(distance(this.heroes[0],plates[0])<.85&&distance(this.heroes[1],plates[1])<.85)||(distance(this.heroes[1],plates[0])<.85&&distance(this.heroes[0],plates[1])<.85);this.plateTime=pair?this.plateTime+dt:Math.max(0,this.plateTime-dt*2);if(this.plateTime>1.5){this.plateTime=0;if(this.stage===0){this.stage=1;this.event('chapter',{stage:1});this.checkpoint();}else{this.finished=true;for(const h of this.heroes)h.emote=5;this.event('finish',{time:this.time,combos:this.combos,rescues:this.rescues,cheers:this.cheers});}}}
 for(const w of this.wisps){const n=this.knots[w.anchor];if(n.done)continue;w.timer-=dt;w.x=n.x+Math.cos(this.time*.6+w.anchor*2)*1.5;w.y=n.y+Math.sin(this.time*.6+w.anchor*2)*1.2;if(w.timer<0){w.timer=this.gentle?5:3.3;const h=this.heroes[w.anchor%2];const angle=Math.atan2(h.y-w.y,h.x-w.x);this.event('warning',{x:w.x,y:w.y});for(let i=-1;i<=1;i++){const a=angle+i*.35;this.pulses.push({x:w.x,y:w.y,vx:Math.cos(a)*2,vy:Math.sin(a)*2,life:4,warn:.75});}}}
 for(const p of this.pulses){p.life-=dt;p.warn-=dt;if(p.warn>0)continue;p.x+=p.vx*dt;p.y+=p.vy*dt;for(const h of this.heroes)if(p.life>0&&h.hp>0&&h.inv<=0&&distance(p,h)<.48){p.life=0;if(!this.gentle)h.hp--;h.inv=1.3;this.event('hit',{hero:h.id,x:h.x,y:h.y});}}
 this.pulses=this.pulses.filter(p=>p.life>0);this.beams=this.beams.filter(b=>(b.life-=dt)>0);
 for(const h of this.heroes){if(h.hp<=0){const other=this.heroes[1-h.id];h.revive=other.hp>0&&distance(h,other)<1.7?h.revive+dt:0;if(h.revive>1.2){h.hp=3;h.inv=3;h.revive=0;this.rescues++;this.event('rescue',{hero:h.id});}}}
 if(this.heroes.every(h=>h.hp<=0)){const y=this.spawnY??(this.stage>=2?18:27);this.heroes=[HERO(0,11,y),HERO(1,13,y)];this.pulses=[];this.event('toast',{text:'A breath. A fresh start. Everything you restored stays restored.'});}
 }
}
