(()=>{'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sources={
 t2:'https://ir.take2games.com/static-files/b5863f86-fadd-4232-9712-8b813817e444',
 t23:'https://assets.ctfassets.net/wn7ipiv9ue5v/5TyspVTlLFdPvHctrie8n7/ad5a4299bee672b007e94b962b356f4c/Take-Two_Interactive_2023_Impact_Report_Final.pdf',
 dream:'https://www.dreamhaven.com/news/applications-open-for-dreamhaven-ggp-scholarship-program-2025',
 fun:'https://funplus.com/partnership/funplus-announces-a-year-long-partnership-with-gay-gaming-professionals/',
 esa:'https://www.theesa.com/the-esa-foundation-announces-its-2021-22-scholars/',
 joint:'https://www.theesa.com/esa-hosts-gay-gaming-professionals-and-lgbt-congressional-staff-association/',
 ua:'https://urbanarts.org/wp-content/uploads/2025/12/THE-URBAN-ARTS-YEARBOOK-2025_FINAL_.pdf',
 caw:'https://funplus.com/funplus-and-creative-art-works-kick-off-their-first-on-site-character-design-apprenticeship/',
 grants:'https://www.theesa.com/foundation/grants/'
};
const rows=[];
function add(supporter,recipient,type,period,evidence,source){rows.push({supporter,recipient,type,period,evidence,source,checked:'2026-09-07'});}
add('Take-Two Interactive','GGP','Scholarship support','2024 report','GGP is named among scholarship partners; no GGP-specific amount disclosed.',sources.t2);
add('Dreamhaven','GGP','Scholarship support','2025 announcement','Scholarships of $5,000 described, alongside mentorship. This is not a current application window.',sources.dream);
add('FunPlus','GGP','Partnership','Historical announcement; renewal unverified','Year-long partnership announced; amount and current renewal not established.',sources.fun);
add('ESA Foundation','GGP','Partnership','Partnership since 2019, reported 2022','Joint LGBTQ+ Service Scholarship. Partnership is not itself proof of a grant payment.',sources.joint);
for(const n of ['AMD','Dreamhaven','Facebook Gaming','Jam City','Niantic','Take-Two Interactive'])add(n,'ESA Foundation','Support acknowledgment','2021–22 scholars','Named supporting company. Financial, in-kind and work-experience support described collectively; company-specific amount and form not stated.',sources.esa);
for(const [tier,names] of [['$250K+',['Google','Unity Technologies']],['$100K+',['Endless Network','Google Play','NBCUniversal','Siegel Family Endowment','Hearst Foundations']],['$50K+',['Hasbro','Take-Two Interactive Software']]])for(const n of names)add(n==='Take-Two Interactive Software'?'Take-Two Interactive':n,'Urban Arts','Giving tier','July 2024–June 2025',tier+' acknowledgment tier, not an exact grant. Do not add tiers together as total giving.',sources.ua);
for(const n of ['New York Videogame Critics Circle','New York University','University of Southern California'])add('Take-Two Interactive',n,'Scholarship support','2023 report','Named scholarship partner; amount and current renewal not established.',sources.t23);
for(const n of ['The Animation Project','Harlem Academy','Harlem Lacrosse','School of Interactive Arts'])add('Take-Two Interactive',n==='School of Interactive Arts'?'Urban Arts':n,'Educational support','2023 report',n==='School of Interactive Arts'?'School of Interactive Arts program named in report; shown under Urban Arts. No separate grant inferred.':'Named educational program support; no amount stated.',sources.t23);
add('FunPlus','Creative Art Works','Partnership','2022 announcement','Character-design apprenticeship collaboration. A program lead for creative career access.',sources.caw);
for(const n of ['Global Game Jam','iCivics','Girlstart','The Animation Project','Boys & Girls Clubs of America','Girl Scouts of Greater Los Angeles','Hispanic Heritage Foundation','Association on American Indian Affairs','After-School All-Stars','HopeLab'])add('ESA Foundation',n,'Historical grant','Past-grantee page; award year not stated','Listed as a past grantee. Current organization and program availability require separate review.',sources.grants);
// September 7 evening expansion: primary sources; no inferred amounts.
for(const n of ['Endless Network','Unity Technologies','Motorola Solutions Foundation','General Motors','Verizon','Take-Two Interactive'])add(n,'Games for Change / G4C Learn','Partnership','Live page checked September 7, 2026; support period unstated','Listed among G4C Learn partners. Branding standardized for browsing; legal grantmaker, amount and payment dates are not established.','https://learn.gamesforchange.org/impact');
add('Siegel Family Endowment','ECEP Alliance','Educational support','May 14, 2026 announcement','ECEP reports a new grant supporting state-level CS and AI education pathways. Amount is not stated.','https://ecepalliance.org/news/2026/05/14/ecep-siegel-family-partner/');
const siegel24='https://www.siegelendowment.org/insights/siegel-family-endowment-awards-over-16-3-million-to-strengthen-workforce-innovation-infrastructure-and-philanthropy/';
for(const [recipient,why] of [
['MIT Work of the Future Initiative','Generative AI and workplace research.'],
['Upwardly Global','Responsible-AI pilot for job seekers.'],
['Data & Society Research Institute','Research informing AI workforce policy.'],
['AFL-CIO Technology Institute','Worker input into AI workplace tools.'],
['Code the Dream','Public-interest technology career pathways.'],
['BlackTechFutures Research Institute','Public-interest technology pathways.']])add('Siegel Family Endowment',recipient,'Historical grant','December 17, 2024 announcement',why+' Named grant recipient; individual amount undisclosed.',siegel24);
window.GGPSupportNetwork=rows;
const entities=[['GGP','GG Professionals Inc.','83-2884652','https://projects.propublica.org/nonprofits/organizations/832884652'],['ESA Foundation','ESAS Foundation','06-1582325','https://projects.propublica.org/nonprofits/organizations/61582325'],['Games for Change','Games for Change Inc.','26-2623362','https://projects.propublica.org/nonprofits/organizations/262623362'],['Urban Arts','Urban Arts Partnership','13-3554734','https://urbanarts.org/financials/']];
const options=(key)=>[...new Set(rows.map(x=>x[key]))].sort().map(x=>`<option>${esc(x)}</option>`).join('');
const old=window.publicPortfolios,oldBind=window.bindPublic;
window.publicPortfolios=()=>`<section class="panel" id="support-network"><p class="eyebrow">NEW / THE SUPPORT BEHIND THE OPPORTUNITY</p><h1>Follow the support.</h1><p class="lead">Start with an organization. Find its documented supporters. Then explore what else those supporters help make possible.</p><div class="strip"><b>${rows.length} sourced relationships · checked September 7, 2026</b><p>A partial research collection across several years. A relationship is not a new funding offer. Historical support, partnerships and giving tiers stay distinct from exact awards.</p></div><div class="toolbar"><label>Organization<select id="network-recipient"><option value="all">All organizations</option>${options('recipient')}</select></label><label>Supporter<select id="network-supporter"><option value="all">All supporters</option>${options('supporter')}</select></label><label>Evidence type<select id="network-type" aria-label="Evidence type"><option value="all">All evidence types</option>${options('type')}</select></label><button id="network-reset">Reset filters</button><button id="network-export">Export relationships</button></div><p id="network-count" role="status"></p><div id="network-results" class="cards"></div><details><summary>How to read this map</summary><p>Use “Explore this supporter” to see other documented recipients. Shared supporters do not prove joint grants or coordinated funding. Giving ranges are not exact amounts. Historical program names do not guarantee an active opportunity today. Donor-advised intermediaries do not identify the original donor. Google and Google Play follow the source’s names; separate legal grantmakers are not inferred.</p><p>Alan Lewis is described as chairman of Take-Two’s Charitable Giving Committee in <a href="https://www.ccny.cuny.edu/s-jay-levy-demo/industry-mentorship-profiles" target="_blank" rel="noopener">his CCNY profile</a>. A separate Take-Two Foundation legal entity has not been verified here.</p></details></section><section class="panel"><p class="eyebrow">PUBLIC RECORDS / START WITH THE RIGHT ENTITY</p><h2>Open the financial evidence.</h2><div class="cards">${entities.map(([n,legal,ein,url])=>`<article class="card"><h3>${n}</h3><p>${legal}<br>EIN ${ein}</p><a href="${url}" target="_blank" rel="noopener">Open filings and reports ↗</a></article>`).join('')}</div><p class="small">Filing indexes and reports are linked, not fully imported. Public charity returns generally omit contributor identities; grantmaker filings and public acknowledgments fill different parts of the picture. <a href="https://www.irs.gov/charities-non-profits/public-disclosure-and-availability-of-exempt-organizations-returns-and-applications-documents-subject-to-public-disclosure" target="_blank" rel="noopener">IRS disclosure guidance ↗</a></p></section>${old()}`;
window.bindPublic=()=>{oldBind();let selected=[];const el=id=>document.getElementById(id);function draw(){selected=rows.filter(r=>['recipient','supporter','type'].every(k=>el('network-'+k).value==='all'||el('network-'+k).value===r[k]));el('network-count').textContent=`${selected.length} of ${rows.length} relationships · ${new Set(selected.map(x=>x.recipient)).size} organizations shown`;el('network-results').innerHTML=selected.map(r=>`<article class="card"><span class="tag">${esc(r.type)}</span><h3>${esc(r.supporter)} <span aria-label="supports">→</span> ${esc(r.recipient)}</h3><p>${esc(r.evidence)}</p><p class="small">${esc(r.period)} · checked ${r.checked}</p><a href="${r.source}" target="_blank" rel="noopener">Read the evidence ↗</a><p><button data-network-supporter="${esc(r.supporter)}" title="Clear other filters and show all recorded organizations this supporter backs">Explore this supporter →</button></p></article>`).join('')||'<p class="empty">No recorded relationships match. Reset the filters to explore the collection.</p>';el('network-results').querySelectorAll('[data-network-supporter]').forEach(b=>b.onclick=()=>{el('network-recipient').value=el('network-type').value='all';el('network-supporter').value=b.dataset.networkSupporter;draw();el('network-supporter').focus();});}for(const k of ['recipient','supporter','type'])el('network-'+k).onchange=draw;el('network-reset').onclick=()=>{for(const k of ['recipient','supporter','type'])el('network-'+k).value='all';draw();};el('network-export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({checked:'2026-09-07',coverage:'Partial, historical and current acknowledgments; not a complete donor portfolio. Giving tiers are not exact grants.',records:selected},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='ggp-support-relationships.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};draw();};
window.ggpResearchQueue=()=>`<section class="panel"><p class="eyebrow">STAFF / SUPPORTER RESEARCH</p><h2>Verify before adding grant amounts.</h2><p>New public evidence is available in <a href="#public">Public giving</a>. The following leads are not counted as verified awards:</p><ul><li>Fidelity Charitable → GGP: indexed FY22/FY23 primary rows and a secondary $245,450 amount differ. Retrieve complete schedules and reconcile periods; do not infer the underlying donor.</li><li>Summit Health Cares → GGP ($11,400) and American Online Giving Foundation → GGP ($7,708): secondary index leads; verify original Schedule I rows and fiscal years.</li><li>ESA Foundation → GGP: secondary FY2022/FY2023 grant leads require original schedule verification.</li><li>Games for Change 2025 impact report: update the 2024 supporter roster after reviewing the newer document.</li><li>ESA historical grantees: verify current program status before promotion into the active opportunity pipeline.</li></ul><p>Research ownership: unassigned. Full supporter portfolios remain incomplete. <a href="https://www.causeiq.com/organizations/gg-professionals%2C832884652/" target="_blank" rel="noopener">GGP secondary grant leads ↗</a> · <a href="https://www.gamesforchange.org/2025-impact-report/" target="_blank" rel="noopener">G4C 2025 report ↗</a></p></section>`;
})();
