(()=>{'use strict';
const $=s=>document.querySelector(s);
const scales=[['Extreme wide','translate(144 100) scale(.55)', 'The setting takes most of the frame. The person is small within it.'],['Wide','translate(-38 -45) scale(1.18)','The full person and some setting stay visible.'],['Medium','translate(-140 -190) scale(2)','The view crops near the waist. Less setting remains.'],['Close-up','translate(-690 -763) scale(4.4)','The face fills more of the frame. Much of the place is outside it.'],['Detail','translate(-1980 -1990) scale(10)','A small facial detail fills the frame. Context is withheld.']];
document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>{const [name,transform,description]=scales[+b.dataset.scale];$('#s2 #world').setAttribute('transform',transform);$('#scale-note').textContent=name+': '+description;$('#s2 svg').setAttribute('aria-label',name+' view. '+description);document.querySelectorAll('[data-scale]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
document.querySelector('[data-scale="0"]').click();
let palette='day';const palettes={day:['#bce6ef','#879ccc','#b14c4e'],night:['#303258','#7967a9','#5b3b71'],warm:['#ffd08a','#d58270','#a04853']};function color(){const el=$('#s3 svg'),colors=palettes[palette];el.querySelector('.sky').setAttribute('fill',colors[0]);el.querySelector('.hill').setAttribute('fill',colors[1]);el.querySelector('#color-house rect').setAttribute('fill',colors[2]);const sat=$('#saturation').value;el.style.filter=`saturate(${sat}%)`;$('#sat-value').textContent=sat+'%';$('#color-note').textContent={day:'Daylight',night:'Night garden',warm:'Golden hour'}[palette]+' palette · '+sat+'% saturation. The objects have not moved. '+(sat==='0'?'Color is removed; light–dark differences remain.':'Compare the light–dark differences as well as the hues.');el.setAttribute('aria-label',$('#color-note').textContent);}
document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{palette=b.dataset.palette;document.querySelectorAll('[data-palette]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));color()});$('#saturation').oninput=color;
let move='pan';const notes={pan:'Pan: turns left or right from a fixed position. This diagram is a top view.',tilt:'Tilt: points up or down from a fixed position. This diagram is a side view.',dolly:'Dolly: the camera position travels toward the subject. Its direction stays fixed in this example.',boom:'Boom: the camera position rises. Its direction stays fixed in this example.'};function movement(){const t=+$('#move-step').value/100;let transform=move==='pan'||move==='tilt'?`rotate(${-30*t} 139 180)`:move==='dolly'?`translate(${190*t} 0)`:`translate(0 ${-65*t})`;$('#camera').setAttribute('transform',transform);$('#move-value').textContent=t===0?'Start':t===1?'End':Math.round(t*100)+'%';$('#move-note').textContent=notes[move]+(t>0?' Compare position with direction.':' Slide to compare start and end.');$('#move-title').textContent=notes[move];}
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{move=b.dataset.move;$('#move-step').value=0;document.querySelectorAll('[data-move]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));movement()});$('#move-step').oninput=movement;
document.querySelectorAll('.save-note').forEach(b=>b.onclick=()=>{let id=b.dataset.note,text=$('#note-'+id).value.trim(),out=b.nextElementSibling;if(!text){out.textContent='Nothing to save yet. A few words are plenty, if you want to write.';return}const name=$('#title-'+id).textContent;const blob=new Blob(['CTIN 290 · '+name+'\n\n'+text+'\n\nOptional reflection. Not submitted.'],{type:'text/plain;charset=utf-8'});let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='CTIN-290-'+id+'-reflection.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);out.textContent='Download requested. Check your browser’s downloads. Nothing was submitted.';});
})();
