(()=>{'use strict';let handles=new Map();const key='gordtopia-welcome-v1';let welcomed=false,offer=false;
try{welcomed=localStorage.getItem(key)==='seen'||JSON.parse(localStorage.getItem('gordtopia-portal-v1')||'{}').entered===true}catch{}
const remember=()=>{welcomed=true;try{localStorage.setItem(key,'seen')}catch{}};
function clean(){for(const [host,h] of handles)if(!host.isConnected){h.destroy();handles.delete(host)}}
function put(host,id,options={}){clean();if(!host)return null;if(handles.has(host))return handles.get(host);const h=window.GordtopiaVignettes.mount(host,id,options);handles.set(host,h);return h;}
function selected(p,animate=false){const host=document.getElementById('selection');if(!host)return;let slot=host.querySelector('.atlas-vignette');if(!slot){slot=document.createElement('div');slot.className='atlas-vignette';host.prepend(slot)}const h=put(slot,'atlas',{compact:true,caption:`Our next direction: ${p.code} · ${p.label}. The Atlas keeps the real coordinates.`});if(animate)h?.play();return h;}
function mounted(route){clean();if(route==='arrival')welcome();if(route==='hold'){const host=document.querySelector('.workspace');if(host&&!host.querySelector('.fishing-break')){const d=document.createElement('details');d.className='fishing-break panel';const s=document.createElement('summary');s.textContent='A fishing pause, just because';d.append(s);const slot=document.createElement('div');d.append(slot);host.append(d);d.addEventListener('toggle',()=>{if(d.open)put(slot,'hold')})}}
if(route==='fieldbook'){const c=document.getElementById('care-surprises');if(c&&!c.querySelector('.chest-vignette')){const slot=document.createElement('div');slot.className='chest-vignette';c.insertBefore(slot,c.querySelector('.surprise-grid'));put(slot,'fieldbook',{compact:true})}const b=document.getElementById('together-bookmark');if(b&&!b.querySelector('.home-vignette')){const slot=document.createElement('div');slot.className='home-vignette';b.append(slot);put(slot,'homecoming',{compact:true})}}
if(route==='atlas'&&offer){offer=false;const host=document.querySelector('.workspace');const n=document.createElement('aside');n.className='welcome-next panel';n.innerHTML='<p class="eyebrow">A little hello, then your own pace</p><h2>You’re here, friend.</h2><p>This Atlas holds our real places. If you fancy one small surprise, there’s a place saved for you.</p><button id="welcome-wonder">One little discovery</button><button id="welcome-done">Let me wander</button>';host.querySelector('.realm-banner').after(n);n.querySelector('#welcome-wonder').onclick=()=>{window.GordtopiaWonders?.open('eighty-eight');n.remove()};n.querySelector('#welcome-done').onclick=()=>n.remove();}}
function welcome(force=new URLSearchParams(location.search).get('welcome')==='1'){const stage=document.querySelector('.together-landing');if(!stage||welcomed&&!force)return;stage.classList.add('first-welcome');document.querySelector('.arrival')?.classList.add('welcome-memories');stage.parentElement.prepend(stage);const copy=stage.firstElementChild;copy.querySelector('.eyebrow').textContent='Eric, I made this for you.';copy.querySelector('h2').innerHTML='A little world.<br>With love.';const p=copy.querySelector('.before-portal + p');p.textContent='Thank you for almost twenty years of friendship, for the laughter, the worlds we’ve made, and all the life still ahead. Come in for a moment. There’s nothing here you have to finish. Love, Gordon.';const wander=copy.querySelector('a[href="#atlas"]');wander.textContent='Let me wander';wander.addEventListener('click',remember,{once:true});document.getElementById('enter-together').addEventListener('click',()=>{offer=true;remember()},{once:true});const memories=document.querySelector('.arrival');if(memories){document.querySelectorAll('.welcome-memories-door').forEach(d=>{if(!d.contains(memories))d.remove()});const d=document.createElement('details');d.className='welcome-memories-door';const s=document.createElement('summary');s.textContent='The real memories behind this doorway';d.append(s,memories);stage.after(d)}}
function react(id,text){mounted(document.body.dataset.realm);const match=[...handles.values()].find(h=>h.root.dataset.scene===id&&h.root.isConnected);if(match){if(text)match.celebrate(text);else match.play()}}
window.GordtopiaLiving={mounted,selected,react,needsWelcome:()=>!welcomed,replayWelcome(){remember();location.hash='arrival';setTimeout(()=>{welcome(true);document.querySelector('.together-landing')?.scrollIntoView({block:'start'})},80)}};
})();
