/* Optional Gordtopia extension. The Site owner integrates this file. */
(()=>{'use strict';
const KEY='gordtopia-wonders-v1';
const ITEMS=[
{id:'eighty-eight',route:'arrival',label:'88',title:'Your place is still here.',type:'pair',a:'Gordon’s place',b:'Eric’s place',intro:'A little nod to Mug 88. Set down two places at the table.',done:'The good part is who pulls up the other chair.',future:'What belongs on the table next time?'},
{id:'waterfall',route:'atlas',label:'The scenic route',title:'There were stairs.',type:'branch',intro:'A waterfall, an ambitious climb, and the later discovery of a much simpler way. Choose your approach.',options:['Ride the waterfall','Look for the stairs'],answers:['Excellent story. Questionable route planning. The stairs are over here.','A remarkably sensible choice. Shall we take the scenic way back?'],future:'What detour should become a story next?'},
{id:'totems',route:'atlas',label:'Find each other',title:'Different paths. A familiar face.',type:'meet',intro:'Move the two markers toward one another. An imagined little reunion, wherever the next adventure takes you.',done:'There you are.',future:'Where would you like your paths to meet next?'},
{id:'teammates',route:'arrival',label:'Same side',title:'Still teammates.',type:'rhythm',intro:'Blue, then yellow. Take turns at your own pace.',done:'A small rhythm, held between two people. Still on the same side.',future:'What should you try as a team next?'},
{id:'gravel',route:'hold',label:'Check the gravel',title:'A very ordinary box.',type:'peel',intro:'Some of the best surprises arrive in the least glamorous places.',layers:['A bit of gravel.','A little more gravel.','Something small. For no occasion. Because it’s you.'],future:'What small surprise could you leave next time?'},
{id:'handmade',route:'hold',label:'By hand',title:'Every block has a before.',type:'order',intro:'Put a small build in the order it becomes real.',options:['Leave it for someone','Imagine it','Make it'],order:['Imagine it','Make it','Leave it for someone'],done:'The world remembers the work of your hands. And who you had in mind.',future:'What would you like to make for each other?'},
{id:'two-rods',route:'fieldbook',label:'Two fishing rods',title:'The conversation can wander.',type:'pair',a:'Settle in',b:'Make room beside you',intro:'Eric wanted to go fishing with Gordon. Here, a moment can be enough.',done:'Nothing to catch up on. Nothing to catch, either, if you’d rather just talk.',future:'What would make an ordinary evening lovely?'},
{id:'rescue',route:'arrival',label:'3,425',title:'The number kept one part.',type:'reveal',intro:'Rosemont, June 27, 2026. The scoreboard counted 3,425 villagers saved.',button:'And the photograph?',done:'It kept two friends having a very good Saturday.',image:'assets/rosemont.jpg',alt:'Eric and Gordon at the Minecraft Experience in Rosemont',future:'What photograph would you love to take together next?'},
{id:'firsts',route:'arrival',label:'Another first',title:'Firsts have no closing date.',type:'reveal',intro:'Chicago, June 28, 2026. Eric’s first Pride is one of the doorway’s real memories.',button:'Leave room for another first',done:'A place neither of you has been. Something neither of you has tried. A new version of an ordinary day.',image:'assets/pride.jpg',alt:'Gordon and Eric at Eric’s first Pride in Chicago',future:'What first would you like to share?'},
{id:'homeward',route:'atlas',label:'A light home',title:'Leave a light in the window.',type:'light',intro:'Drag slowly from night toward morning. This is an imagined view, not a map of the server.',done:'Whatever the route, keep a little room for coming home.',future:'What makes a place feel like yours together?'},
{id:'ordinary-tuesday',route:'fieldbook',label:'An ordinary Tuesday',title:'It doesn’t have to be an occasion.',type:'mix',intro:'Choose two ingredients for a small future evening.',options:['Fishing','A good story','A wander','Music','Comfortable quiet'],done:'No booking made. No calendar filled. Just something you could enjoy.',future:'Add one thing that would make it yours.'},
{id:'unmapped',route:'atlas',label:'Beyond the map',title:'A place neither of you knows yet.',type:'horizon',intro:'Choose a direction for your imagination. These are possibilities, not recorded destinations.',options:['Somewhere with water','Somewhere wonderfully strange','Somewhere close to home'],done:'Leave the coordinates blank for now.',future:'Where does your curiosity go?'},
{id:'next-chapter',route:'fieldbook',label:'One more chapter',title:'Almost twenty years. Still room.',type:'words',intro:'Choose three words you would like the next chapter to hold.',options:['Laughter','Rest','Discovery','Courage','Play','Home','Surprise','Time'],done:'A wish for the years ahead, not a prediction.',future:'What else belongs in that chapter?'},
{id:'postcard',route:'fieldbook',label:'A postcard unwritten',title:'Wish we were here.',type:'postcard',intro:'Imagine a postcard from a day you haven’t shared yet. Give it a place and one small detail.',placeholder:'Somewhere by the water. We found the stairs this time.',future:'An imagined future postcard'},
{id:'small-tradition',route:'hold',label:'Begin something small',title:'A tradition can start once.',type:'mix',intro:'Choose two ingredients for a ritual you might want to repeat.',options:['A hello','A tiny gift','A photo','One good question','A shared sunset'],done:'It becomes a tradition if you both want to come back to it.',future:'What would you call it?'},
{id:'unfinished',route:'hold',label:'Room to grow',title:'Leave one corner unfinished.',type:'reveal',intro:'Not every good world needs a final state.',button:'Make room for an idea',done:'A spare corner. A new color. Something Eric imagines that Gordon never would. Something Gordon can’t wait to show Eric.',future:'What would you leave open for the other person?'},
{id:'slow-down',route:'fieldbook',label:'Stay a little',title:'No achievement required.',type:'still',intro:'A quiet window. You can let it be just that.',done:'You don’t need a better reason to spend time together.',future:'What would you like less of, so there is more room for this?'},
{id:'question',route:'fieldbook',label:'A question for the walk',title:'Something worth asking.',type:'question',intro:'Turn over a question for a future conversation. There is no need to answer here.',options:['What have you been curious about lately?','What would you love us to try together?','What small thing made you laugh today?','What would make this week feel lighter?','What do you want more time for?'],future:'Keep a question of your own.'},
{id:'later-letter',route:'hold',label:'For another chapter',title:'A note you can return to.',type:'letter',intro:'Write in your own words. Fold it closed and open it when you want. It stays on this device; the fold is a playful reveal, not a lock.',placeholder:'Something I want to remember about the life ahead…',future:'Your note for another chapter'},
{id:'open-door',route:'arrival',label:'The door stays open',title:'The next story is unwritten.',type:'reveal',intro:'A registration line. A team. A world. Almost twenty years of friendship, and a lifetime you want to keep sharing.',button:'Turn the page',done:'There is room for the next ordinary evening. The next unexpected detour. The next thing you leave each other to find.',future:'One little hope for the life ahead.'}
];
const IDS=new Set(ITEMS.map(x=>x.id));
const CHAPTERS=[
 {title:'I · The Door That Remembers',intro:'At the gate, a cartographer has left a map with no final destination. Its first ink comes from the ways two friends have already found each other.',ids:['eighty-eight','teammates','rescue','firsts','totems'],gift:'The Compass of Recognition',line:'It points toward a familiar face, wherever the road begins.'},
 {title:'II · The River Without a Clock',intro:'Past the gate, the river refuses to measure progress. It asks whether the travelers can spend a little time without making it useful.',ids:['waterfall','two-rods','homeward','slow-down','question'],gift:'The Hour That Belongs to You',line:'No deadline is written on it. There is room to stay.'},
 {title:'III · The House of Small Magic',intro:'A quiet house holds gravel, hand-worked treasures, and letters waiting to be opened. Here, magic is something one friend leaves for another.',ids:['gravel','handmade','small-tradition','unfinished','later-letter'],gift:'The Key to an Unfinished Room',line:'One corner remains open for an idea you have not had yet.'},
 {title:'IV · The Country Not Yet Drawn',intro:'Beyond the last inked road, the parchment is warm and empty. It asks for possibilities rather than promises.',ids:['ordinary-tuesday','unmapped','next-chapter','postcard','open-door'],gift:'The Map of What Comes Next',line:'It has no final destination. You get to keep making it together.'}
];
const CLUES={
 'eighty-eight':'A familiar number has saved a place.',waterfall:'The long way up hides a much simpler answer.',totems:'Two markers would rather not stay apart.',teammates:'Two colors remember how to take turns.',gravel:'Look in the least remarkable box.',handmade:'An idea, a pair of hands, and someone in mind.','two-rods':'Somewhere beside the water, two places wait.',rescue:'A number remembers a Saturday.',firsts:'A photograph still has room for another first.',homeward:'A small light points toward home.','ordinary-tuesday':'An ordinary evening is missing two ingredients.',unmapped:'Beyond the ink, three horizons are possible.','next-chapter':'Three words could begin a new chapter.',postcard:'A postcard has arrived from a day that hasn’t happened.','small-tradition':'A ritual is waiting to happen once.',unfinished:'The unfinished corner is deliberate.','slow-down':'The river has forgotten how to count minutes.',question:'Turn over a question for the walk.','later-letter':'A folded page is waiting for your words.','open-door':'The last door opens onto an unwritten story.'};
const blank=()=>({format:KEY,kept:{},seen:[],completed:[]});
function validate(s){
 if(!s||Array.isArray(s)||s.format!==KEY||!s.kept||typeof s.kept!=='object'||Array.isArray(s.kept)||!Array.isArray(s.seen))throw Error('Invalid wonder journal');
 const complete=s.completed===undefined?[]:s.completed;
 if(!Array.isArray(complete)||complete.length>20||new Set(complete).size!==complete.length||complete.some(id=>!IDS.has(id)))throw Error('Invalid map discoveries');
 if(Object.keys(s.kept).length>20||s.seen.length>20||new Set(s.seen).size!==s.seen.length)throw Error('Too many entries');
 const clean=blank();
 for(const [k,v] of Object.entries(s.kept)){if(!IDS.has(k)||typeof v!=='string'||v.length>600)throw Error('Invalid wonder note');clean.kept[k]=v;}
 for(const id of s.seen){if(!IDS.has(id))throw Error('Unknown wonder');clean.seen.push(id);}clean.completed=[...complete];return clean;
}
let state=blank(),temporary=false,dlg=null,opener=null,current=null,observer=null,questActor=null;
try{const saved=localStorage.getItem(KEY);if(saved)state=validate(JSON.parse(saved));}catch{temporary=true;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));temporary=false;}catch{temporary=true;}}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function announce(text){const n=dlg?.querySelector('.ew-status');if(n)n.textContent=text;}
function note(item,host){
 const label=el('label','ew-note-label',item.future||'Keep a thought');const box=el('textarea');box.maxLength=600;box.rows=3;box.placeholder=item.placeholder||'Just a few words, if you like.';box.value=state.kept[item.id]||'';label.append(box);host.append(label);
 const row=el('div','ew-actions');row.append(button('Keep on this device',()=>{state.kept[item.id]=box.value.trim();persist();announce(temporary?'Kept for this visit. Export before leaving.':'Kept on this device. Nothing was sent.');}));
 row.append(button('Clear this thought',()=>{if(!box.value&&!state.kept[item.id])return;if(!confirm('Clear this thought on this device? Other notes will stay.'))return;delete state.kept[item.id];box.value='';persist();announce('This thought was cleared.');},'ew-subtle'));host.append(row);
 host.append(el('p','ew-local','Your words stay in this browser. Export a copy to carry them with you. Nothing is sent to the other person.'));
 return box;
}
function scene(host){const n=el('div','ew-window');n.setAttribute('role','img');n.setAttribute('aria-label','Illustrated Gordtopia landscape, an imagined view');host.append(n);return n;}
function open(id){
 questActor?.destroy();questActor=null;
 const item=ITEMS.find(x=>x.id===id);if(!item)return;ensure();if(!dlg.open)opener=document.activeElement;current=id;const body=dlg.querySelector('.ew-body');body.replaceChildren();announce('');
 if(!state.seen.includes(id)){state.seen.push(id);persist();}
 const chapter=CHAPTERS.find(c=>c.ids.includes(id));
 body.append(el('p','ew-eyebrow',chapter.title),el('h2','',item.title),el('p','ew-intro',item.intro));
 const stage=el('div','ew-play'),answer=el('p','ew-answer');answer.setAttribute('aria-live','polite');const after=el('div','ew-after');after.hidden=true;body.append(stage,answer,after);
 const feedback=el('section','story-progress');feedback.hidden=true;feedback.setAttribute('role','status');stage.before(feedback);
 let completed=false;const mark=()=>{if(state.completed.includes(id))return;state.completed.push(id);persist();const count=chapter.ids.filter(x=>state.completed.includes(x)).length,all=state.completed.length===20,chapterDone=count===5;feedback.hidden=false;feedback.classList.add('new-discovery');feedback.append(el('span','progress-sigil','✓'),el('div','',all?'All twenty discoveries found. The next story is still yours.':chapterDone?chapter.gift+' revealed. '+chapter.line:'Discovery found · '+count+' / 5 in this chapter. A little ink returns to the map.'));window.GordtopiaSound?.play(all?'final':chapterDone?'chapter':'discovery');announce(all?'All twenty discoveries found. A final page awaits on the map.':chapterDone?chapter.gift+' revealed. '+chapter.line:'Discovery found. '+count+' of five in this chapter.');if(chapterDone){const host=el('div','ew-quest-acting');feedback.after(host);questActor=window.GordtopiaVignettes?.mount(host,'quest',{compact:true,hideButton:true});questActor?.caption(chapter.gift+'. We found it together.');questActor?.play();}};
 const finish=(text=item.done)=>{answer.textContent=text||'';if(!completed){completed=true;mark();after.hidden=false;note(item,after);}};
 if(item.type==='pair'){
  const pressed=new Set();[item.a,item.b].forEach((s,i)=>{const b=button(s,()=>{pressed.add(i);b.setAttribute('aria-pressed','true');if(pressed.size===2)finish();else answer.textContent='There is room for the other person.';},'ew-token');b.setAttribute('aria-pressed','false');stage.append(b);});
 }else if(item.type==='branch'){
  item.options.forEach((s,i)=>stage.append(button(s,()=>finish(item.answers[i]),'ew-choice')));
 }else if(item.type==='meet'){
  const track=el('div','ew-meeting');const a=el('span','ew-person ew-gordon','Gordon'),b=el('span','ew-person ew-eric','Eric');track.append(a,b);stage.append(track);
  const label=el('label','', 'Bring the paths together');const range=el('input');range.type='range';range.min='0';range.max='100';range.value='0';label.append(range);stage.append(label);
  range.oninput=()=>{const v=+range.value;a.style.transform=`translateX(${v*.32}%)`;b.style.transform=`translateX(${-v*.32}%)`;track.style.gap=`${Math.max(0,100-v)}px`;if(v>=96)finish();};
 }else if(item.type==='rhythm'){
  let next=0;const seq=[0,1,0,1];const row=el('div','ew-rhythm');['Blue','Yellow'].forEach((s,i)=>row.append(button(s,()=>{if(completed)return;if(i===seq[next]){next++;answer.textContent=next<4?`${next%2?'Yellow':'Blue'} has the next turn. No hurry.`:'';}else{answer.textContent=`Try ${seq[next]?'yellow':'blue'} next. No need to start over.`;}if(next===4){row.classList.add('ew-in-sync');finish();}},'ew-color ew-color-'+i)));stage.append(row,el('p','ew-local','One person can take both turns. This is a playful duet, not a live connection.'));
 }else if(item.type==='peel'){
  let n=0;const next=button('Look inside',()=>{answer.textContent=item.layers[n++];next.textContent=n===1?'A little further':'One last look';if(n===item.layers.length){next.remove();finish(item.layers[n-1]);}},'ew-reveal');stage.append(next);
 }else if(item.type==='order'){
  let n=0;item.options.forEach(s=>{const b=button(s,()=>{if(s===item.order[n]){b.disabled=true;n++;answer.textContent=s+'.';if(n===3)finish();}else answer.textContent=n===0?'An idea comes first.':'There is a little making to do first.';},'ew-choice');stage.append(b);});
 }else if(item.type==='reveal'){
  stage.append(button(item.button,()=>{stage.replaceChildren();if(item.image){const img=el('img','ew-memory');img.src=item.image;img.alt=item.alt;stage.append(img);}finish();},'ew-reveal'));
 }else if(item.type==='light'){
  const view=scene(stage);view.style.filter='brightness(.35) saturate(.8)';const label=el('label','','A little more light');const range=el('input');range.type='range';range.min='0';range.max='100';range.value='0';label.append(range);stage.append(label);range.oninput=()=>{view.style.filter=`brightness(${.35+Number(range.value)*.007}) saturate(1)`;if(+range.value>80)finish();};
 }else if(item.type==='mix'||item.type==='words'){
  const chosen=new Set(),max=item.type==='words'?3:2;item.options.forEach(s=>{const b=button(s,()=>{if(chosen.has(s))chosen.delete(s);else if(chosen.size<max)chosen.add(s);else{answer.textContent=`Choose up to ${max}. Tap one again to make room.`;return;}stage.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(chosen.has(x.textContent))));answer.textContent=[...chosen].join(' + ');if(chosen.size===max){finish([...chosen].join(' + ')+'. '+item.done);const box=after.querySelector('textarea');if(box&&!box.value)box.value=[...chosen].join(' + ');}},'ew-choice');b.setAttribute('aria-pressed','false');stage.append(b);});
 }else if(item.type==='horizon'){
  scene(stage);item.options.forEach(s=>stage.append(button(s,()=>{finish(s+'. '+item.done);const box=after.querySelector('textarea');if(box&&!box.value)box.value=s;},'ew-choice')));
 }else if(item.type==='postcard'){
  scene(stage);stage.append(button('Begin the postcard',()=>finish('An imagined postcard, waiting for a real day.'),'ew-reveal'));
 }else if(item.type==='still'){
  scene(stage);stage.append(button('Nothing else for a moment',()=>finish(),'ew-reveal'));stage.append(el('p','ew-local','Stay as long or as briefly as you like.'));
 }else if(item.type==='question'){
  let n=0;stage.append(button('Turn over a question',()=>finish(item.options[n++%item.options.length]),'ew-reveal'));
 }else if(item.type==='letter'){
  after.hidden=false;completed=true;const box=note(item,after);const fold=button('Fold this note',()=>{box.hidden=!box.hidden;fold.textContent=box.hidden?'Open your note':'Fold this note';mark();announce(box.hidden?'A folded page joins the map. It is not password-protected.':'Your words, just as you left them.');},'ew-reveal');stage.append(fold);if(box.value){box.hidden=true;fold.textContent='Open your note';}
 }
 const bottom=el('div','ew-bottom');bottom.append(button('Return to the unfinished map',cabinet,'ew-subtle'));body.append(bottom);
 if(!dlg.open)dlg.showModal();dlg.querySelector('.ew-close').focus();
}
function cabinet(){questActor?.destroy();questActor=null;ensure();if(!dlg.open)opener=document.activeElement;current=null;const body=dlg.querySelector('.ew-body');body.replaceChildren();announce('');body.append(el('p','ew-eyebrow','An optional story within Gordtopia'),el('h2','','The Cartographer’s Unfinished Map'),el('p','ew-intro','Four corners of a story. A little ink returns with every discovery. Choose any place that catches your eye.'),el('p','ew-local','An imagined story map, not the Atlas of Minecraft coordinates. Your own discoveries stay on this device.'));
 const map=el('div','story-map');map.setAttribute('aria-label','Four illustrated story regions');const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 100 66.667');svg.setAttribute('aria-hidden','true');const points=[[30,20],[77,29],[76,65],[22,63]];points.forEach(([x,y],i)=>{const line=document.createElementNS(ns,'path');line.setAttribute('d',`M50 28.667 Q${(50+x)/2} ${28.667+8} ${x} ${y*2/3}`);line.setAttribute('pathLength','100');const n=CHAPTERS[i].ids.filter(id=>state.completed.includes(id)).length;line.style.strokeDashoffset=String(100-n*20);svg.append(line)});map.append(svg);const tabs=el('div','story-tabs');tabs.setAttribute('aria-label','Choose a story chapter');const focus=el('section','story-focus');focus.id='story-chapter-focus';
 function select(i,move=false){const chapter=CHAPTERS[i],count=chapter.ids.filter(id=>state.completed.includes(id)).length;map.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));tabs.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));focus.replaceChildren(el('h3','',chapter.title),el('p','ew-intro',chapter.intro),el('p','ew-local',count+' / 5 discoveries found. Choose any; come and go as you like.'));const grid=el('div','ew-cabinet');chapter.ids.forEach(id=>{const item=ITEMS.find(x=>x.id===id),found=state.completed.includes(id);const b=button('',()=>open(id),'ew-cabinet-item');b.dataset.wonder=id;b.append(el('span','',found?'✓ '+item.label:item.label),el('small','',CLUES[id]));grid.append(b)});focus.append(grid);if(count===5)focus.append(el('p','ew-keepsake',chapter.gift+'. '+chapter.line));if(move){focus.querySelector('h3').tabIndex=-1;focus.querySelector('h3').focus({preventScroll:true});focus.scrollIntoView({behavior:document.body.classList.contains('no-motion')?'instant':'smooth',block:'nearest'})}}
 CHAPTERS.forEach((c,i)=>{const count=c.ids.filter(id=>state.completed.includes(id)).length;const hotspot=button(count===5?'✓':String(i+1),()=>select(i,true));hotspot.style.left=points[i][0]+'%';hotspot.style.top=points[i][1]+'%';hotspot.setAttribute('aria-label',c.title+', '+count+' of five found');hotspot.classList.toggle('is-inked',count>0);map.append(hotspot);const tab=button('',()=>select(i),'story-tab');tab.append(el('span','',c.title),el('small','',count===5?'✓ Keepsake found':count+' / 5 discoveries'));tabs.append(tab)});body.append(map,tabs,focus);select(Math.max(0,CHAPTERS.findIndex(c=>c.ids.some(id=>!state.completed.includes(id)))));
 const oracle=el('details','ew-oracle-fold');oracle.append(el('summary','','Let a friendly roll choose'));const box=el('div','ew-oracle'),face=el('output','ew-die','?'),hint=el('p','ew-oracle-hint','A twenty-sided roll can suggest a place.');face.setAttribute('aria-label','Oracle roll');let chosen=null;const follow=button('Follow this clue',()=>{if(chosen)open(chosen.id)},'ew-subtle');follow.hidden=true;const acting=el('div','ew-quest-acting');box.append(face,button('Roll for a little wonder',()=>{const r=new Uint32Array(1);globalThis.crypto.getRandomValues(r);const roll=1+r[0]%20;face.value=String(roll);face.textContent=String(roll);chosen=ITEMS[roll-1];hint.textContent=CLUES[chosen.id];follow.hidden=false;if(!questActor)questActor=window.GordtopiaVignettes?.mount(acting,'quest',{compact:true,hideButton:true});questActor?.caption('Rolled '+roll+'. '+CLUES[chosen.id]);questActor?.play();announce('Rolled '+roll+'. '+CLUES[chosen.id]);}),hint,follow);oracle.append(box,acting);body.append(oracle);
 if(state.completed.length===20){const final=el('section','ew-finale');final.append(el('p','ew-eyebrow','The cartographer leaves one final page'),el('h3','','The destination was never the end.'),el('p','','Almost twenty years have given the map its roots. The life ahead is still yours to imagine. Take a little rest, choose a little wonder, and leave room for the other person’s idea.'),el('p','','The map stays unfinished on purpose.'),button('Write a hope for the next chapter',()=>open('open-door'),'ew-reveal'));body.append(final);}
 const backup=el('details','ew-backup');backup.append(el('summary','','Keep a copy of your map and thoughts'));const actions=el('div','ew-actions');actions.append(button('Export map and thoughts',exportFile));const lab=el('label','ew-import','Import map and thoughts');const file=el('input');file.type='file';file.accept='application/json';file.onchange=async()=>{const f=file.files[0];if(!f)return;try{if(f.size>50000)throw Error();const incoming=validate(JSON.parse(await f.text()));if(!confirm('Merge these thoughts? Imported thoughts with the same title replace those on this device. Export first to keep both versions.'))return;state=validate({format:KEY,kept:{...state.kept,...incoming.kept},seen:[...new Set([...state.seen,...incoming.seen])],completed:[...new Set([...state.completed,...incoming.completed])]});persist();cabinet();announce('Map and thoughts imported. No messages sent.');}catch{announce('This is not a valid wonder-journal export. Nothing changed.');}finally{file.value='';}};lab.append(file);actions.append(lab);backup.append(actions,el('p','ew-local','Sharing the website does not share your private map journal. Export carries a copy.'));body.append(backup);
 if(!dlg.open)dlg.showModal();dlg.querySelector('.ew-close').focus();
}
function exportFile(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='gordtopia-little-wonders.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ensure(){if(dlg)return;dlg=el('dialog','ew-dialog');dlg.setAttribute('aria-label','Little wonders for Eric and Gordon');const close=button('Close',()=>dlg.close(),'ew-close');const body=el('div','ew-body'),status=el('p','ew-status');status.setAttribute('role','status');dlg.append(close,body,status);document.body.append(dlg);dlg.addEventListener('close',()=>{questActor?.destroy();questActor=null;if(opener?.isConnected)opener.focus();else document.querySelector('#main')?.focus();});}
function mount(route){
 const main=document.querySelector('#main');if(!main)return;const active=route||document.body.dataset.realm||'arrival';if(main.querySelector('.ew-rail'))return;
 const rail=el('aside','ew-rail');rail.setAttribute('aria-label','Optional hidden quest clues');rail.append(el('span','ew-rail-title','A margin note catches the light…'));
 const local=ITEMS.filter(x=>x.route===active),unread=local.filter(x=>!state.completed.includes(x.id));(unread.length?unread:local).slice(0,2).forEach(item=>rail.append(button(item.label,()=>open(item.id),'ew-found')));rail.append(button('Inspect the unfinished map',cabinet,'ew-all'));main.append(rail);
}
window.GordtopiaWonders={mount,open,cabinet,items:ITEMS.map(({id,label,route})=>({id,label,route})),chapters:CHAPTERS.map(({title,ids})=>({title,ids:[...ids]})),getState:()=>JSON.parse(JSON.stringify(state)),validateState:validate,importState:s=>{state=validate(s);persist();},destroy:()=>{observer?.disconnect();dlg?.remove();dlg=null;document.querySelectorAll('.ew-rail').forEach(x=>x.remove());}};
function init(){mount();const main=document.querySelector('#main');if(main){observer=new MutationObserver(()=>mount());observer.observe(main,{childList:true});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
