(()=>{'use strict';
const styles=[
{id:'home',icon:'▣',name:'Overworld',object:'The home lantern',line:'Oak, river light, and a place kept for both of you.',paper:'#e6d6ab',grid:'#c6b58a',selected:'#ae421f'},
{id:'nether',icon:'◆',name:'Nether',object:'The portal ember',line:'Blackstone, quartz, and a warm glow on the other side.',paper:'#e6cecb',grid:'#bda3aa',selected:'#742956'},
{id:'ggp',icon:'✿',name:'GGP Grove',object:'The cherry petal',line:'Make room. Grow together. A little GGP in our own world.',paper:'#f6e6f0',grid:'#d7b7ce',selected:'#2449ce'},
{id:'dnd',icon:'⬡',name:'D&D',object:'The twenty-sided die',line:'Every map a quest. Every act of care worth remembering.',paper:'#eddfbd',grid:'#bdaa80',selected:'#823b27'},
{id:'stoughton',icon:'❀',name:'Stoughton',object:'The painted flower',line:'A little Norwegian-American color from Eric’s Wisconsin home.',paper:'#f5e8ce',grid:'#cdb89b',selected:'#245b86'}];
const key='gordtopia-view-v1';let skin='home',discovered=['home'],busy=false,clocks=[],idle=0,doneEntry=null,noticeClock=0;
try{const s=JSON.parse(localStorage.getItem(key)||'{}');if(styles.some(x=>x.id===s.skin))skin=s.skin;if(Array.isArray(s.discovered))discovered=[...new Set(['home',...s.discovered.filter(x=>styles.some(y=>y.id===x))])]}catch{}
const current=()=>styles.find(x=>x.id===skin);
function persist(){try{localStorage.setItem(key,JSON.stringify({skin,discovered}))}catch{}}
function updateButtons(){document.querySelectorAll('[data-world-skin]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.worldSkin===skin));b.classList.toggle('discovered',discovered.includes(b.dataset.worldSkin))});document.querySelectorAll('.current-world').forEach(e=>e.textContent=current().name);const counter=document.querySelector('#style-discoveries');if(counter)counter.textContent=discovered.length+' / 5 worlds discovered';}
function apply(id,announce=true){if(!styles.some(s=>s.id===id))return;const fresh=!discovered.includes(id);skin=id;if(fresh)discovered.push(id);document.body.dataset.skin=skin;persist();updateButtons();window.dispatchEvent(new Event('gordtopia-style'));if(announce){const e=document.getElementById('style-live');if(e){clearTimeout(noticeClock);noticeClock=setTimeout(()=>e.textContent='',6500);e.textContent=(fresh?'New world discovered. ':'')+current().name+'. '+current().line;}document.body.classList.remove('world-shimmer');void document.body.offsetWidth;document.body.classList.add('world-shimmer');setTimeout(()=>document.body.classList.remove('world-shimmer'),900)}}
const buttons=()=>styles.map(s=>`<button class="world-object" data-world-skin="${s.id}" aria-pressed="${s.id===skin}" title="${s.object}: ${s.line}"><span aria-hidden="true">${s.icon}</span><b>${s.name}</b><small>${s.object}</small></button>`).join('');
function bind(host){host.querySelectorAll('[data-world-skin]').forEach(b=>b.onclick=()=>apply(b.dataset.worldSkin));updateButtons()}
const dlg=document.createElement('dialog');dlg.id='world-chest';dlg.setAttribute('aria-labelledby','world-chest-title');dlg.innerHTML=`<button class="close" aria-label="Close world styles">×</button><p class="eyebrow">Five little objects. Five different worlds.</p><h2 id="world-chest-title">What does this one do?</h2><p>Touch an object and see your world change. Your map, plans and field notes stay right where you left them.</p><div class="world-objects">${buttons()}</div><p id="style-discoveries"></p><p class="muted">These are visual interpretations. The Nether look does not change your coordinates or connect to the server.</p><button id="replay-entry">Replay our entrance →</button>`;document.body.append(dlg);dlg.querySelector('.close').onclick=()=>dlg.close();bind(dlg);document.getElementById('world-style').onclick=()=>dlg.showModal();document.getElementById('replay-entry').onclick=()=>{dlg.close();location.hash='arrival';setTimeout(()=>document.getElementById('friendship-stage')?.scrollIntoView({behavior:document.body.classList.contains('no-motion')?'instant':'smooth',block:'center'}),80)};
const live=document.createElement('div');live.id='style-live';live.setAttribute('role','status');live.setAttribute('aria-live','polite');document.body.append(live);
function stop(){clocks.forEach(clearTimeout);clocks=[];clearInterval(idle);idle=0;}
function mounted(route){stop();if(busy){busy=false;doneEntry=null;}document.querySelectorAll('.world-tool-tray').forEach(e=>{e.innerHTML=`<div><span class="eyebrow">Our world, a different light</span><b class="current-world"></b></div><div class="world-objects">${buttons()}</div>`;bind(e)});if(route==='arrival'){const pair=document.querySelector('.friend-pair');if(pair){pair.dataset.frame='0';idle=setInterval(()=>{if(document.hidden||document.body.classList.contains('no-motion')||busy)return;pair.dataset.frame='1';clocks.push(setTimeout(()=>pair.dataset.frame='0',1400))},6500)}}updateButtons()}
function finish(){if(!busy)return;const cb=doneEntry;busy=false;doneEntry=null;stop();document.querySelector('.friendship-stage')?.classList.remove('entering');const skip=document.getElementById('skip-entry');if(skip)skip.hidden=true;cb?.();setTimeout(()=>{const h=document.querySelector('.workspace h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}},30)}
function enter({motion,done}){if(busy)return;busy=true;doneEntry=done;stop();const stage=document.getElementById('friendship-stage'),pair=stage?.querySelector('.friend-pair');if(!motion||document.hidden||!stage||!pair){finish();return}stage.scrollIntoView({behavior:'smooth',block:'center'});stage.classList.add('entering');const skip=document.getElementById('skip-entry');skip.hidden=false;skip.onclick=finish;const line=stage.querySelector('.stage-line');const frame=(n,text)=>{pair.dataset.frame=String(n);line.textContent=text;};frame(0,'Ready, friend?');clocks.push(setTimeout(()=>frame(1,'Always. Together.'),420));clocks.push(setTimeout(()=>frame(2,'One… two…'),1100));clocks.push(setTimeout(()=>frame(3,'Gordtopia, here we come!'),1550));clocks.push(setTimeout(()=>stage.classList.add('through'),2000));clocks.push(setTimeout(finish,2600));}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&busy)finish()});document.getElementById('motion').addEventListener('click',()=>{if(busy)finish()});
window.GordtopiaMagic={enter,mounted,palette:current,styles:styles.map(s=>s.id)};apply(skin,false);
})();
