const $=s=>document.querySelector(s), all=s=>[...document.querySelectorAll(s)];
const samples=[
{label:'01 / THE LEARNING SCOOP',title:'Make it read.',url:'https://gordonusc.github.io/the-cabinet/ctin-290-recap/#attention',frame:'Working CTIN 290 visual field guide',try:'Try the contrast controls. Watch where your eye goes.',connect:'You talk about learning by building.',why:'Here, a student changes a picture and sees the consequence. The vocabulary follows the experience.',state:'BUILT + PUBLIC',limit:'A working learning guide. Its effect on learning has not been measured.',recipe:[['A student should be able to see the idea.','Gordon asked for a welcoming, ungraded recap: show unfamiliar terms, let students practice, and make it usable on phones.'],['Turn the explanation into a controllable scene.','The guide links composition terms to live visual changes, examples, practice prompts and an offline edition. You are using the actual published guide above.'],['The feedback changes the artifact.','Gordon and his student assistant supplied classroom feedback. The revised guide distinguishes attention from optical focus and asks students to explain a visible tradeoff.'],['Did understanding transfer?','A useful next check: can a student apply a term to a new image? A working control and a successful page load cannot answer that.']]},
{label:'02 / THE POSSIBILITY SCOOP',title:'Who could this help?',url:'https://gordonusc.github.io/the-cabinet/alan/ggp/index.html#donors',frame:'Working GGP donor directory prototype',try:'Explore a program. Try the comparison controls.',connect:'You connect philanthropic intent to possibility.',why:'This prototype lets a donor explore programs and inspect evidence. That is close to the bridge between people and institutions in your university essay.',state:'PUBLIC PROTOTYPE · NOT A LAUNCHED SERVICE',limit:'Donor-first testing is the proposed starting point. Public-facing scale, staffing and upkeep remain decisions to make.',recipe:[['Make giving easier to understand.','Gordon wanted donors to see opportunities, compare them and understand the evidence—not navigate a social network.'],['Connect research to a working interface.','The prototype provides donor, student and educator perspectives. These are connected concept experiences, not proof that a maintained public service exists.'],['Listen before increasing the scope.','Partner feedback brought the plan back to a smaller donor pilot, explicit maintenance effort, testing and a joint decision before expansion.'],['What is the ongoing cost of being correct?','Test donor comprehension and relevance. Track corrections, source freshness, review time and coordination effort before promising a larger service.']]},
{label:'03 / THE HUMAN SCOOP',title:'Love, made useful.',url:'https://gordonusc.github.io/the-cabinet/love-made-useful/',frame:'Love, made useful: Joe and Gordon’s public visual story',try:'Explore the story. Notice how the design changes with its purpose.',connect:'A system can also make room for care.',why:'Joe’s first app and our learning together belong to a human story. This piece gives that story a form we can share and return to.',state:'BUILT + PUBLIC',limit:'A personal visual story. Its existence does not establish app readiness or financial outcomes.',recipe:[['Make the investment in learning feel human.','Gordon asked for a visual story for Joe about our evolving craft and what we are trying to make possible together.'],['Choose a form that carries the feeling.','This is an editorial, interactive story rather than an operational report. It uses the same making tools for a different emotional purpose.'],['Taste comes from specific feedback.','Gordon repeatedly challenged generic layouts and word walls. His direction is part of the work: show the relationship and make the design earn its place.'],['Does the recipient feel seen?','The next evidence is Joe’s response—not an automated score for delight. The story is a shared artifact, not a prediction about income or retirement.']]}
];let sample=0,recipeIndex=0,sound=false,ctx;
function select(selector,attr,value){all(selector).forEach(b=>b.setAttribute('aria-pressed',b.dataset[attr]===String(value)))}
function notes(seq=[330,440,550],force=false){if(!sound&&!force)return;try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();seq.forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.095;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.045,t+.018);g.gain.exponentialRampToValueAtTime(.001,t+.3);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.32)})}catch(e){$('#sound').textContent='Sound unavailable'}}
function showRecipe(i){recipeIndex=i;select('[data-recipe]','recipe',i);const r=samples[sample].recipe[i];$('#recipe-title').textContent=r[0];$('#recipe-copy').textContent=r[1];$('#recipe-icon').textContent=['↗','◎','↻','?'][i]}
function showSample(i){sample=i;const s=samples[i];select('[data-sample]','sample',i);for(const [id,key] of Object.entries({'sample-label':'label','sample-title':'title','try-instruction':'try','connection-title':'connect','connection':'why','state':'state','limit':'limit'}))$('#'+id).textContent=s[key];$('#note-number').textContent='0'+(i+1);$('#artifact').src=s.url;$('#artifact').title=s.frame;$('#open-original').href=s.url;showRecipe(recipeIndex);notes([[330,440,550],[293.66,369.99,440],[261.63,329.63,523.25]][i]);}
all('[data-sample]').forEach(b=>b.onclick=()=>showSample(+b.dataset.sample));all('[data-recipe]').forEach(b=>b.onclick=()=>{showRecipe(+b.dataset.recipe);notes()});showRecipe(0);
$('#recipe').onclick=()=>{const open=$('#recipe-panel').hidden;$('#recipe-panel').hidden=!open;$('#recipe').setAttribute('aria-expanded',open);$('#recipe b').textContent=open?'−':'＋';notes()};
const layerCopy=['Useful language can clarify an idea. By itself, it does not show whether the experience works.','The current Astra work includes usable websites, learning experiments and visual stories. Jordan can inspect an artifact instead of taking a description on trust.','Gordon directs the purpose and taste. Astra builds and checks. Darby brings continuity and review when available. Human feedback sends the work around again. Earlier agent work also used tools; this is not exclusive to one model.'];
all('[data-layer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.layer;select('[data-layer]','layer',i);$('#mix-scene').dataset.layer=i;$('#layer-copy').textContent=layerCopy[i];notes()});
const tests=[['Can a student explain a new image?','A transfer task: point to a feature and explain its effect.','Preparation, compute, review and revision time.'],['Does the next task take less total effort?','Compare a similar task, including corrections and handoffs.','Human review and rework as well as tool spend.'],['Can someone see why a recommendation was made?','Trace the claim to its source; identify what is uncertain.','Verification effort, stale information and consequential mistakes.']];
function showReturn(i){select('[data-return]','return',i);['test-title','test-evidence','test-cost'].forEach((id,j)=>$('#'+id).textContent=tests[i][j])}showReturn(0);all('[data-return]').forEach(b=>b.onclick=()=>{showReturn(+b.dataset.return);notes()});
$('#sound').onclick=()=>{sound=!sound;$('#sound').setAttribute('aria-pressed',sound);$('#sound').textContent=sound?'♫ Sound on':'♫ Sound off';if(sound)notes();else ctx?.suspend()};
function sprinkles(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<15;i++){let s=document.createElement('span');s.className='spark';s.textContent=['✦','·','✧'][i%3];s.style.left=(20+Math.random()*60)+'vw';s.style.top=(15+Math.random()*35)+'vh';s.style.color=['#b4d283','#e4a8c5','#efbc80'][i%3];document.body.append(s);setTimeout(()=>s.remove(),1700)}}
$('#dessert').onclick=()=>{$('#dessert-room').showModal();sprinkles();notes([261.63,329.63,392,523.25])};$('#close-dessert').onclick=()=>$('#dessert-room').close();$('#dessert-room').addEventListener('close',()=>{$('#dessert-video').pause();ctx?.suspend()});$('#chime').onclick=()=>notes([261.63,329.63,392,523.25,659.25],true);
$('#copy-note').onclick=async()=>{const body=`Jordan + Gordon — our next experiment\n\nStarting point: ${samples[sample].title}\n${$('#napkin').value.trim()||'What could we try together, and what evidence would tell us it helped?'}\n\n${location.href.split('#')[0]}`;try{await navigator.clipboard.writeText(body);$('#note-status').textContent='Copied. Ready to paste into our conversation; nothing sent.';notes()}catch(e){$('#note-status').textContent='Copy unavailable here. Select your note above and copy it manually.'}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){ctx?.suspend();$('#dessert-video').pause()}});
