(()=>{'use strict';const $=s=>document.querySelector(s);const data=JSON.parse($('#lessonData').textContent);const state={attention:'equal',paths:'door',placement:'center',depth:'deep',context:'wide',trace:false,grid:false};
function part(id,sel){return $('#scene-'+id).querySelector(sel)}
function describe(id,text){$('#note-'+id).textContent=text;$('#scene-'+id).setAttribute('aria-label',text)}
function apply(id){if(id==='attention'){let v=state.attention;part(id,'.door').style.fill=v==='door'?'#fff9bc':'#9cae9b';part(id,'.friend-b').style.filter=v==='friend'?'drop-shadow(0 0 11px #fff49a)':'none';part(id,'.back').style.opacity=v==='friend'?'.45':'1';describe(id,v==='door'?'The doorway is now much lighter than the wall around it. Its contrast can give a small element stronger emphasis.':v==='friend'?'The blue friend is highlighted while the distant scenery is quieter. This changes emphasis without moving the character.':'A quieter doorway competes less strongly. Notice your own first look; the image does not force every viewer to agree.')}
if(id==='paths'){let door=state.paths==='door';part(id,'.path').setAttribute('d',door?'M90 420 526 260H585L285 420Z':'M90 420 434 302H488L285 420Z');part(id,'.trace').setAttribute('d',door?'M190 395 551 268':'M190 395 461 306');part(id,'.trace').style.opacity=state.trace?'1':'0';describe(id,door?'The path aims toward the doorway. The optional dashed overlay traces one possible route for your eye.':'The path now ends near the blue friend. The route and destination change together.')}
if(id==='placement'){let x=state.placement==='center'?360:480;part(id,'.friend-b').setAttribute('transform',`translate(${x} 240)`);part(id,'.grid').style.opacity=state.grid?'.55':'0';describe(id,x===360?'The blue friend is centered. Centering may create a strong emphasis; it is not automatically a mistake.':'The blue friend sits near the right third. More space opens on the left. Compare what that space contributes.')}
if(id==='depth'){let s=$('#sharp').value;['front','mid','back'].forEach(k=>part(id,'.'+k).style.filter=state.depth==='shallow'&&k!==s?'url(#soft-depth)':'none');describe(id,state.depth==='deep'?'Deep focus: near, middle, and far layers are sharp. The objects have not moved.':'Shallow focus: the '+({front:'foreground plant',mid:'middle-ground friends',back:'background house'}[s])+' stays sharp while the other layers soften. Position and sharpness are different variables.')}
if(id==='context'){let v=state.context;part(id,'.world').setAttribute('transform',v==='close'?'translate(-460 -220) scale(2.1)':'');part(id,'.back').style.opacity=v==='isolate'?'.26':'1';part(id,'.friend-a').style.opacity=v==='isolate'?'.36':'1';part(id,'.front').style.opacity=v==='isolate'?'.3':'1';part(id,'.friend-b').style.filter=v==='isolate'?'drop-shadow(0 0 12px #fff7a0)':'none';describe(id,v==='close'?'Closer framing: the blue friend is easier to inspect, but less of the route and setting is visible.':v==='isolate'?'Focal isolation: light and reduced background emphasis make the blue friend stand out. This illustrates the course shorthand “Blue Lock (visual).”':'A broad view shows the people, route, and destination together. It can establish their spatial relationship.')}
}
document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>{let id=b.dataset.demo;state[id]=b.dataset.value;document.querySelectorAll(`[data-demo="${id}"]`).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));apply(id)}));
$('#traceToggle').onclick=()=>{state.trace=!state.trace;$('#traceToggle').setAttribute('aria-pressed',state.trace);$('#traceToggle').textContent=state.trace?'Hide guide overlay':'Show guide overlay';apply('paths')};
$('#gridToggle').onclick=()=>{state.grid=!state.grid;$('#gridToggle').setAttribute('aria-pressed',state.grid);$('#gridToggle').textContent=state.grid?'Hide thirds grid':'Show thirds grid';apply('placement')};$('#sharp').onchange=()=>apply('depth');
$('#gap').oninput=()=>{let n=Number($('#gap').value);part('space','.friend-b').setAttribute('transform',`translate(${254+n} 240)`);$('#gapValue').textContent=n<140?'Closer together':n>260?'Farther apart':'Open space between them';describe('space',`The people are ${n<140?'closer together':n>260?'farther apart':'separated by open space'}. What reading does that suggest to you, and what else would you need to know?`)};
document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{let l=data.lessons.find(x=>x.id===b.dataset.q),i=Number(b.dataset.answer);document.querySelectorAll(`[data-q="${l.id}"]`).forEach(x=>{x.classList.remove('selected','chosen-fit');x.setAttribute('aria-pressed',String(x===b))});b.classList.add(i===l.correct?'chosen-fit':'selected');$('#feedback-'+l.id).textContent=l.feedback[i]}));
function studio(){let gap=Number($('#studioGap').value),v=$('#studioLight').value,p=$('#studioPalette').value;part('studio','.friend-b').setAttribute('transform',`translate(${254+gap} 240)`);part('studio','.door').style.fill=v==='door'?'#fff9bc':'#ead397';part('studio','.mid').style.filter=v==='together'?'drop-shadow(0 0 9px #fff6ac)':'none';part('studio','.back').style.opacity=v==='together'?'.65':'1';const svg=$('#scene-studio');const colors={garden:['#cceee7','#96c4b9','#f6dfb6','#526aa4','#f28159'],night:['#2d3558','#485878','#69748b','#474678','#c9a2be'],sun:['#ffdaa0','#dab586','#fbe9bb','#887dc0','#ef8054']}[p];svg.querySelector('rect').setAttribute('fill',colors[0]);part('studio','.back > path').setAttribute('fill',colors[1]);part('studio','.world > path').setAttribute('fill',colors[2]);part('studio','.back > rect').setAttribute('fill',colors[3]);part('studio','.back > path:nth-of-type(2)').setAttribute('fill',colors[4]);svg.setAttribute('aria-label',`Your scene: friends ${gap<140?'closer together':gap>260?'farther apart':'separated by open space'}; emphasis on ${v}; ${p} palette.`);}
['studioGap','studioLight','studioPalette'].forEach(id=>$('#'+id).addEventListener('input',studio));studio();
function download(text,type,name){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('#saveScene').onclick=()=>{let s=$('#scene-studio').cloneNode(true);s.setAttribute('xmlns','http://www.w3.org/2000/svg');download(new XMLSerializer().serializeToString(s),'image/svg+xml','My-CTIN-290-scene.svg')};
const fields=['intent','change','noticed'];fields.forEach(id=>{try{$('#'+id).value=localStorage.getItem('ctin290-recap-'+id)||''}catch(e){}$('#'+id).addEventListener('input',()=>{try{localStorage.setItem('ctin290-recap-'+id,$('#'+id).value);$('#saveState').textContent='Notes saved in this browser only. Use “Save my reflection” to keep a separate copy. Nothing is submitted.'}catch(e){$('#saveState').textContent='Browser storage is unavailable. Use “Save my reflection” before leaving to keep your notes.'}})});
$('#saveReflection').onclick=()=>download('CTIN 290 · My visual experiment\nOptional reflection, not submitted or graded.\n\n'+fields.map((id,i)=>['My intention','I changed / because','My viewer noticed / I now notice'][i]+':\n'+$('#'+id).value).join('\n\n'),'text/plain;charset=utf-8','My-CTIN-290-reflection.txt');
$('#viewerMode').onclick=()=>{document.body.classList.add('viewer');$('#viewerBanner').hidden=false;$('#exitViewer').focus()};$('#exitViewer').onclick=()=>{document.body.classList.remove('viewer');$('#viewerBanner').hidden=true;$('#viewerMode').focus()};
$('#termSearch').oninput=()=>{let q=$('#termSearch').value.trim().toLowerCase(),n=0;document.querySelectorAll('.term-entry').forEach(e=>{e.hidden=!e.textContent.toLowerCase().includes(q);if(!e.hidden)n++});$('#termResult').textContent=q?(n?`${n} matching terms. Open one to explore.`:'No term found. Try a shorter word, like “focus” or “space”.'):'Open any term for its meaning and a place to try it.'};
document.querySelectorAll('.load-video').forEach(b=>b.onclick=()=>{const slot=b.parentElement.querySelector('.video-slot');if(slot.firstChild){slot.replaceChildren();b.textContent='Play here';return}const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(b.dataset.video)+'?cc_load_policy=1&rel=0';frame.title=b.dataset.title+' video player';frame.allow='encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;slot.append(frame);b.textContent='Close player'});
$('#printGuide').onclick=()=>window.print();$('#offlineSave').onclick=async()=>{const note=$('#offlineStatus');if(!('serviceWorker'in navigator)||!/^https?:$/.test(location.protocol)){note.textContent='Use the downloadable PDF for phone access or open the downloaded HTML in a desktop browser. Offline browser storage is unavailable here.';return}try{note.textContent='Saving the guide and illustrated PDF for this browser…';await navigator.serviceWorker.register('./sw.js');const reg=await navigator.serviceWorker.ready;const ready=await caches.open('ctin290-recap-v1');await ready.addAll(['./','./style.css','./app.js','./assets/bigwalk4.jpg','./assets/wilmot1.jpg','./CTIN-290-Visual-Field-Guide.pdf']);note.textContent='Saved for offline use in this browser. Videos still need internet. Keep the downloaded PDF too: devices can clear browser storage.'}catch(e){note.textContent='This browser could not save the full offline copy. Download the PDF or complete pack instead; the guide is still available online.'}};
['attention','paths','placement','depth','context'].forEach(apply);
})();
